// GENERATED BY ANON — DO NOT EDIT. Overwritten every run (plan §9).
// Edit curation in rules/mapping-rules.yaml; views/styles live in views.dsl.

group "Core Library" {
    toyCommon = container "Toy.Common" ".NET assembly: Toy.Common." ".NET assembly" {
        tags ".NET assembly,Container,csharp"
    }
    toyDomain = container "Toy.Domain" ".NET assembly: Toy.Domain." ".NET assembly" {
        tags ".NET assembly,Container,csharp"
    }
}
group "Messaging" {
    toyMessaging = container "Toy.Messaging" ".NET assembly: Toy.Messaging." ".NET assembly" {
        tags ".NET assembly,Container,csharp"
    }
}
group "Web Frontend" {
    toyWeb = container "Toy.Web" ".NET assembly: Toy.Web." ".NET assembly" {
        tags ".NET assembly,Container,csharp"
    }
}
