// GENERATED BY ANON — DO NOT EDIT. Overwritten every run (plan §9).
// Edit curation in rules/mapping-rules.yaml; views/styles live in views.dsl.

!impliedRelationships false
toyDomain -> toyCommon "Uses" ".NET project reference" {
    tags "Relationship,confidence:low,declared,project_ref"
}
toyMessaging -> toyCommon "Uses" ".NET project reference" {
    tags "Relationship,confidence:low,declared,project_ref"
}
toyWeb -> toyDomain "Uses" ".NET project reference" {
    tags "Relationship,confidence:low,declared,project_ref"
}
toyWeb -> toyMessaging "Uses" ".NET project reference" {
    tags "Relationship,confidence:low,declared,project_ref"
}
