"""Tests for view_intents.py — the §6.1 generator-neutral view-intents compiler.

Covers:
  - load_intents: absent file -> {}; present file round-trips the YAML document.
  - compile_intents: exact deterministic golden DSL for scoped (container/systemContext/
    component) views and a filtered view; selector lowering ("*" wildcard vs quoted tags);
    autolayout on/off; banner present.
  - validate_intents: flags an over-budget view, a dangling filtered base, an empty include,
    and an unknown type. Clean intents -> no warnings.
  - Determinism: same input -> byte-identical string; author list order preserved (not sorted).
"""
from __future__ import annotations

from pathlib import Path

from anon import view_intents


# ---------------------------------------------------------------------------
# load_intents
# ---------------------------------------------------------------------------

def test_load_intents_absent_returns_empty(tmp_path: Path):
    assert view_intents.load_intents(tmp_path / "does-not-exist.yaml") == {}


def test_load_intents_reads_yaml(tmp_path: Path):
    p = tmp_path / "view-intents.yaml"
    p.write_text(
        "views:\n"
        "  - key: containers\n"
        "    type: container\n"
        "    include: ['*']\n",
        encoding="utf-8",
    )
    data = view_intents.load_intents(p)
    assert data == {"views": [{"key": "containers", "type": "container", "include": ["*"]}]}


def test_load_intents_empty_file_returns_empty(tmp_path: Path):
    p = tmp_path / "view-intents.yaml"
    p.write_text("", encoding="utf-8")
    assert view_intents.load_intents(p) == {}


# ---------------------------------------------------------------------------
# compile_intents — golden DSL
# ---------------------------------------------------------------------------

_BANNER = (
    "// GENERATED BY ANON — DO NOT EDIT. Overwritten every run (plan §9).\n"
    "// Edit view intents in rules/view-intents.yaml; styles live in views.dsl.\n"
)


def _sample_intents() -> dict:
    return {
        "views": [
            {
                "key": "context",
                "type": "systemContext",
                "title": "System Context",
                "include": ["*"],
                "autolayout": "tb",
            },
            {
                "key": "containers",
                "type": "container",
                "title": "Containers",
                "include": ["*"],
                "exclude": ["external"],
                "budget": 25,
                "autolayout": "lr",
            },
            {
                "key": "messaging",
                "type": "filtered",
                "base": "containers",
                "include": ["messaging", "Relationship"],
            },
        ]
    }


def test_compile_intents_golden():
    out = view_intents.compile_intents(_sample_intents())
    expected = _BANNER.rstrip("\n") + "\n" + "\n".join([
        'systemContext system "context" "System Context" {',
        '    include *',
        '    autolayout tb',
        '}',
        'container system "containers" "Containers" {',
        '    include *',
        '    exclude "external"',
        '    autolayout lr',
        '}',
        'filtered "containers" include "messaging,Relationship" "messaging"',
    ]) + "\n"
    assert out == expected


def test_compile_intents_filtered_exclude_mode():
    intents = {
        "views": [
            {"key": "base", "type": "container"},
            {"key": "internal", "type": "filtered", "base": "base",
             "mode": "exclude", "exclude": ["external"]},
        ]
    }
    out = view_intents.compile_intents(intents)
    assert 'filtered "base" exclude "external" "internal"' in out


def test_compile_intents_autolayout_false_omits_line():
    intents = {"views": [{"key": "c", "type": "container", "autolayout": False}]}
    out = view_intents.compile_intents(intents)
    assert "autolayout" not in out
    # a container view with no explicit include still gets the wildcard default.
    assert "    include *" in out


def test_compile_intents_custom_scope_and_system_identifier():
    intents = {"views": [{"key": "ctx", "type": "systemContext"}]}
    out = view_intents.compile_intents(intents, system_identifier="ctrlApp")
    assert 'systemContext ctrlApp "ctx"' in out
    # explicit per-view scope overrides the system identifier default.
    intents2 = {"views": [{"key": "comp", "type": "component", "scope": "orderProcessor"}]}
    out2 = view_intents.compile_intents(intents2, system_identifier="ctrlApp")
    assert 'component orderProcessor "comp"' in out2


def test_compile_intents_banner_present():
    out = view_intents.compile_intents(_sample_intents())
    assert out.startswith("// GENERATED BY ANON")


def test_compile_intents_empty_is_banner_only():
    assert view_intents.compile_intents({}) == _BANNER.rstrip("\n") + "\n"
    assert view_intents.compile_intents({"views": []}) == _BANNER.rstrip("\n") + "\n"


def test_compile_intents_skips_unknown_type():
    intents = {"views": [
        {"key": "good", "type": "container"},
        {"key": "bad", "type": "nonsense"},
    ]}
    out = view_intents.compile_intents(intents)
    assert "good" in out
    assert "nonsense" not in out and '"bad"' not in out


def test_compile_intents_preserves_author_order():
    # keys deliberately reverse-alphabetical to prove order is preserved, not sorted.
    intents = {"views": [
        {"key": "zebra", "type": "container"},
        {"key": "alpha", "type": "container"},
    ]}
    out = view_intents.compile_intents(intents)
    assert out.index('"zebra"') < out.index('"alpha"')


def test_compile_intents_is_lf_only():
    out = view_intents.compile_intents(_sample_intents())
    assert "\r" not in out


# ---------------------------------------------------------------------------
# Determinism / idempotence
# ---------------------------------------------------------------------------

def test_compile_intents_idempotent():
    intents = _sample_intents()
    assert view_intents.compile_intents(intents) == view_intents.compile_intents(intents)


# ---------------------------------------------------------------------------
# validate_intents
# ---------------------------------------------------------------------------

def _facts_with_n_containers(n: int) -> dict:
    return {
        "targets": [
            {"id": f"csharp:csproj:src/C{i}/C{i}.csproj", "container_id": f"container:c{i}"}
            for i in range(n)
        ]
    }


def test_validate_flags_over_budget():
    intents = {"views": [
        {"key": "containers", "type": "container", "include": ["*"], "budget": 3},
    ]}
    warnings = view_intents.validate_intents(intents, _facts_with_n_containers(5))
    assert any("budget" in w and "containers" in w for w in warnings)


def test_validate_does_not_flag_within_budget():
    intents = {"views": [
        {"key": "containers", "type": "container", "include": ["*"], "budget": 25},
    ]}
    warnings = view_intents.validate_intents(intents, _facts_with_n_containers(5))
    assert warnings == []


def test_validate_flags_dangling_filtered_base():
    intents = {"views": [
        {"key": "containers", "type": "container", "include": ["*"]},
        {"key": "messaging", "type": "filtered", "base": "nonexistent",
         "include": ["messaging"]},
    ]}
    warnings = view_intents.validate_intents(intents, {})
    assert any("nonexistent" in w and "messaging" in w for w in warnings)


def test_validate_accepts_valid_filtered_base():
    intents = {"views": [
        {"key": "containers", "type": "container", "include": ["*"]},
        {"key": "messaging", "type": "filtered", "base": "containers",
         "include": ["messaging"]},
    ]}
    assert view_intents.validate_intents(intents, {}) == []


def test_validate_flags_empty_include():
    intents = {"views": [{"key": "containers", "type": "container", "include": []}]}
    warnings = view_intents.validate_intents(intents, {})
    assert any("empty 'include'" in w for w in warnings)


def test_validate_flags_unknown_type():
    intents = {"views": [{"key": "weird", "type": "nonsense"}]}
    warnings = view_intents.validate_intents(intents, {})
    assert any("unknown type" in w for w in warnings)


def test_validate_empty_intents_no_warnings():
    assert view_intents.validate_intents({}, {}) == []
    assert view_intents.validate_intents({"views": []}, {}) == []
