// GENERATED BY ANON — DO NOT EDIT. Overwritten every run (plan §9).
// Edit curation in rules/mapping-rules.yaml; views/styles live in views.dsl.

abslCheck = container "absl_check" "Build target group: absl_check." "C/C++" {
    tags "Container,cpp,needs-curation"
}
abslLog = container "absl_log" "Build target group: absl_log." "C/C++" {
    tags "Container,cpp,needs-curation"
}
abslVlogIsOn = container "absl_vlog_is_on" "Build target group: absl_vlog_is_on." "C/C++" {
    tags "Container,cpp,needs-curation"
}
algorithm = container "algorithm" "Build target group: algorithm." "C/C++" {
    tags "Container,cpp,needs-curation"
}
algorithmContainer = container "algorithm_container" "Build target group: algorithm_container." "C/C++" {
    tags "Container,cpp,needs-curation"
}
any = container "any" "Build target group: any." "C/C++" {
    tags "Container,cpp,needs-curation"
}
anyInvocable = container "any_invocable" "Build target group: any_invocable." "C/C++" {
    tags "Container,cpp,needs-curation"
}
atomicHook = container "atomic_hook" "Build target group: atomic_hook." "C/C++" {
    tags "Container,cpp,needs-curation"
}
badAnyCast = container "bad_any_cast" "Build target group: bad_any_cast." "C/C++" {
    tags "Container,cpp,needs-curation"
}
badAnyCastImpl = container "bad_any_cast_impl" "Build target group: bad_any_cast_impl." "C/C++" {
    tags "Container,cpp,needs-curation"
}
badOptionalAccess = container "bad_optional_access" "Build target group: bad_optional_access." "C/C++" {
    tags "Container,cpp,needs-curation"
}
badVariantAccess = container "bad_variant_access" "Build target group: bad_variant_access." "C/C++" {
    tags "Container,cpp,needs-curation"
}
base = container "base" "Build target group: base." "C/C++" {
    tags "Container,cpp,needs-curation"
}
baseInternal = container "base_internal" "Build target group: base_internal." "C/C++" {
    tags "Container,cpp,needs-curation"
}
bindFront = container "bind_front" "Build target group: bind_front." "C/C++" {
    tags "Container,cpp,needs-curation"
}
bits = container "bits" "Build target group: bits." "C/C++" {
    tags "Container,cpp,needs-curation"
}
boundedUtf8LengthSequence = container "bounded_utf8_length_sequence" "Build target group: bounded_utf8_length_sequence." "C/C++" {
    tags "Container,cpp,needs-curation"
}
btree = container "btree" "Build target group: btree." "C/C++" {
    tags "Container,cpp,needs-curation"
}
charset = container "charset" "Build target group: charset." "C/C++" {
    tags "Container,cpp,needs-curation"
}
check = container "check" "Build target group: check." "C/C++" {
    tags "Container,cpp,needs-curation"
}
city = container "city" "Build target group: city." "C/C++" {
    tags "Container,cpp,needs-curation"
}
civilTime = container "civil_time" "Build target group: civil_time." "C/C++" {
    tags "Container,cpp,needs-curation"
}
cleanup = container "cleanup" "Build target group: cleanup." "C/C++" {
    tags "Container,cpp,needs-curation"
}
cleanupInternal = container "cleanup_internal" "Build target group: cleanup_internal." "C/C++" {
    tags "Container,cpp,needs-curation"
}
commonPolicyTraits = container "common_policy_traits" "Build target group: common_policy_traits." "C/C++" {
    tags "Container,cpp,needs-curation"
}
compare = container "compare" "Build target group: compare." "C/C++" {
    tags "Container,cpp,needs-curation"
}
compressedTuple = container "compressed_tuple" "Build target group: compressed_tuple." "C/C++" {
    tags "Container,cpp,needs-curation"
}
config = container "config" "Build target group: config." "C/C++" {
    tags "Container,cpp,needs-curation"
}
containerCommon = container "container_common" "Build target group: container_common." "C/C++" {
    tags "Container,cpp,needs-curation"
}
containerMemory = container "container_memory" "Build target group: container_memory." "C/C++" {
    tags "Container,cpp,needs-curation"
}
cord = container "cord" "Build target group: cord." "C/C++" {
    tags "Container,cpp,needs-curation"
}
cordInternal = container "cord_internal" "Build target group: cord_internal." "C/C++" {
    tags "Container,cpp,needs-curation"
}
cordzFunctions = container "cordz_functions" "Build target group: cordz_functions." "C/C++" {
    tags "Container,cpp,needs-curation"
}
cordzHandle = container "cordz_handle" "Build target group: cordz_handle." "C/C++" {
    tags "Container,cpp,needs-curation"
}
cordzInfo = container "cordz_info" "Build target group: cordz_info." "C/C++" {
    tags "Container,cpp,needs-curation"
}
cordzSampleToken = container "cordz_sample_token" "Build target group: cordz_sample_token." "C/C++" {
    tags "Container,cpp,needs-curation"
}
cordzStatistics = container "cordz_statistics" "Build target group: cordz_statistics." "C/C++" {
    tags "Container,cpp,needs-curation"
}
cordzUpdateScope = container "cordz_update_scope" "Build target group: cordz_update_scope." "C/C++" {
    tags "Container,cpp,needs-curation"
}
cordzUpdateTracker = container "cordz_update_tracker" "Build target group: cordz_update_tracker." "C/C++" {
    tags "Container,cpp,needs-curation"
}
coreHeaders = container "core_headers" "Build target group: core_headers." "C/C++" {
    tags "Container,cpp,needs-curation"
}
crc32c = container "crc32c" "Build target group: crc32c." "C/C++" {
    tags "Container,cpp,needs-curation"
}
crcCordState = container "crc_cord_state" "Build target group: crc_cord_state." "C/C++" {
    tags "Container,cpp,needs-curation"
}
crcCpuDetect = container "crc_cpu_detect" "Build target group: crc_cpu_detect." "C/C++" {
    tags "Container,cpp,needs-curation"
}
crcInternal = container "crc_internal" "Build target group: crc_internal." "C/C++" {
    tags "Container,cpp,needs-curation"
}
debugging = container "debugging" "Build target group: debugging." "C/C++" {
    tags "Container,cpp,needs-curation"
}
debuggingInternal = container "debugging_internal" "Build target group: debugging_internal." "C/C++" {
    tags "Container,cpp,needs-curation"
}
decodeRustPunycode = container "decode_rust_punycode" "Build target group: decode_rust_punycode." "C/C++" {
    tags "Container,cpp,needs-curation"
}
demangleInternal = container "demangle_internal" "Build target group: demangle_internal." "C/C++" {
    tags "Container,cpp,needs-curation"
}
demangleRust = container "demangle_rust" "Build target group: demangle_rust." "C/C++" {
    tags "Container,cpp,needs-curation"
}
dieIfNull = container "die_if_null" "Build target group: die_if_null." "C/C++" {
    tags "Container,cpp,needs-curation"
}
dynamicAnnotations = container "dynamic_annotations" "Build target group: dynamic_annotations." "C/C++" {
    tags "Container,cpp,needs-curation"
}
endian = container "endian" "Build target group: endian." "C/C++" {
    tags "Container,cpp,needs-curation"
}
errnoSaver = container "errno_saver" "Build target group: errno_saver." "C/C++" {
    tags "Container,cpp,needs-curation"
}
examineStack = container "examine_stack" "Build target group: examine_stack." "C/C++" {
    tags "Container,cpp,needs-curation"
}
exponentialBiased = container "exponential_biased" "Build target group: exponential_biased." "C/C++" {
    tags "Container,cpp,needs-curation"
}
failureSignalHandler = container "failure_signal_handler" "Build target group: failure_signal_handler." "C/C++" {
    tags "Container,cpp,needs-curation"
}
fastTypeId = container "fast_type_id" "Build target group: fast_type_id." "C/C++" {
    tags "Container,cpp,needs-curation"
}
fixedArray = container "fixed_array" "Build target group: fixed_array." "C/C++" {
    tags "Container,cpp,needs-curation"
}
flags = container "flags" "Build target group: flags." "C/C++" {
    tags "Container,cpp,needs-curation"
}
flagsCommandlineflag = container "flags_commandlineflag" "Build target group: flags_commandlineflag." "C/C++" {
    tags "Container,cpp,needs-curation"
}
flagsCommandlineflagInternal = container "flags_commandlineflag_internal" "Build target group: flags_commandlineflag_internal." "C/C++" {
    tags "Container,cpp,needs-curation"
}
flagsConfig = container "flags_config" "Build target group: flags_config." "C/C++" {
    tags "Container,cpp,needs-curation"
}
flagsInternal = container "flags_internal" "Build target group: flags_internal." "C/C++" {
    tags "Container,cpp,needs-curation"
}
flagsMarshalling = container "flags_marshalling" "Build target group: flags_marshalling." "C/C++" {
    tags "Container,cpp,needs-curation"
}
flagsParse = container "flags_parse" "Build target group: flags_parse." "C/C++" {
    tags "Container,cpp,needs-curation"
}
flagsPathUtil = container "flags_path_util" "Build target group: flags_path_util." "C/C++" {
    tags "Container,cpp,needs-curation"
}
flagsPrivateHandleAccessor = container "flags_private_handle_accessor" "Build target group: flags_private_handle_accessor." "C/C++" {
    tags "Container,cpp,needs-curation"
}
flagsProgramName = container "flags_program_name" "Build target group: flags_program_name." "C/C++" {
    tags "Container,cpp,needs-curation"
}
flagsReflection = container "flags_reflection" "Build target group: flags_reflection." "C/C++" {
    tags "Container,cpp,needs-curation"
}
flagsUsage = container "flags_usage" "Build target group: flags_usage." "C/C++" {
    tags "Container,cpp,needs-curation"
}
flagsUsageInternal = container "flags_usage_internal" "Build target group: flags_usage_internal." "C/C++" {
    tags "Container,cpp,needs-curation"
}
flatHashMap = container "flat_hash_map" "Build target group: flat_hash_map." "C/C++" {
    tags "Container,cpp,needs-curation"
}
flatHashSet = container "flat_hash_set" "Build target group: flat_hash_set." "C/C++" {
    tags "Container,cpp,needs-curation"
}
functionRef = container "function_ref" "Build target group: function_ref." "C/C++" {
    tags "Container,cpp,needs-curation"
}
graphcyclesInternal = container "graphcycles_internal" "Build target group: graphcycles_internal." "C/C++" {
    tags "Container,cpp,needs-curation"
}
hasOstreamOperator = container "has_ostream_operator" "Build target group: has_ostream_operator." "C/C++" {
    tags "Container,cpp,needs-curation"
}
hash = container "hash" "Build target group: hash." "C/C++" {
    tags "Container,cpp,needs-curation"
}
hashContainerDefaults = container "hash_container_defaults" "Build target group: hash_container_defaults." "C/C++" {
    tags "Container,cpp,needs-curation"
}
hashFunctionDefaults = container "hash_function_defaults" "Build target group: hash_function_defaults." "C/C++" {
    tags "Container,cpp,needs-curation"
}
hashPolicyTraits = container "hash_policy_traits" "Build target group: hash_policy_traits." "C/C++" {
    tags "Container,cpp,needs-curation"
}
hashtableDebug = container "hashtable_debug" "Build target group: hashtable_debug." "C/C++" {
    tags "Container,cpp,needs-curation"
}
hashtableDebugHooks = container "hashtable_debug_hooks" "Build target group: hashtable_debug_hooks." "C/C++" {
    tags "Container,cpp,needs-curation"
}
hashtablezSampler = container "hashtablez_sampler" "Build target group: hashtablez_sampler." "C/C++" {
    tags "Container,cpp,needs-curation"
}
ifConstexpr = container "if_constexpr" "Build target group: if_constexpr." "C/C++" {
    tags "Container,cpp,needs-curation"
}
inlinedVector = container "inlined_vector" "Build target group: inlined_vector." "C/C++" {
    tags "Container,cpp,needs-curation"
}
inlinedVectorInternal = container "inlined_vector_internal" "Build target group: inlined_vector_internal." "C/C++" {
    tags "Container,cpp,needs-curation"
}
int128 = container "int128" "Build target group: int128." "C/C++" {
    tags "Container,cpp,needs-curation"
}
kernelTimeoutInternal = container "kernel_timeout_internal" "Build target group: kernel_timeout_internal." "C/C++" {
    tags "Container,cpp,needs-curation"
}
layout = container "layout" "Build target group: layout." "C/C++" {
    tags "Container,cpp,needs-curation"
}
leakCheck = container "leak_check" "Build target group: leak_check." "C/C++" {
    tags "Container,cpp,needs-curation"
}
log = container "log" "Build target group: log." "C/C++" {
    tags "Container,cpp,needs-curation"
}
logEntry = container "log_entry" "Build target group: log_entry." "C/C++" {
    tags "Container,cpp,needs-curation"
}
logFlags = container "log_flags" "Build target group: log_flags." "C/C++" {
    tags "Container,cpp,needs-curation"
}
logGlobals = container "log_globals" "Build target group: log_globals." "C/C++" {
    tags "Container,cpp,needs-curation"
}
logInitialize = container "log_initialize" "Build target group: log_initialize." "C/C++" {
    tags "Container,cpp,needs-curation"
}
logInternalAppendTruncated = container "log_internal_append_truncated" "Build target group: log_internal_append_truncated." "C/C++" {
    tags "Container,cpp,needs-curation"
}
logInternalCheckImpl = container "log_internal_check_impl" "Build target group: log_internal_check_impl." "C/C++" {
    tags "Container,cpp,needs-curation"
}
logInternalCheckOp = container "log_internal_check_op" "Build target group: log_internal_check_op." "C/C++" {
    tags "Container,cpp,needs-curation"
}
logInternalConditions = container "log_internal_conditions" "Build target group: log_internal_conditions." "C/C++" {
    tags "Container,cpp,needs-curation"
}
logInternalConfig = container "log_internal_config" "Build target group: log_internal_config." "C/C++" {
    tags "Container,cpp,needs-curation"
}
logInternalFlags = container "log_internal_flags" "Build target group: log_internal_flags." "C/C++" {
    tags "Container,cpp,needs-curation"
}
logInternalFnmatch = container "log_internal_fnmatch" "Build target group: log_internal_fnmatch." "C/C++" {
    tags "Container,cpp,needs-curation"
}
logInternalFormat = container "log_internal_format" "Build target group: log_internal_format." "C/C++" {
    tags "Container,cpp,needs-curation"
}
logInternalGlobals = container "log_internal_globals" "Build target group: log_internal_globals." "C/C++" {
    tags "Container,cpp,needs-curation"
}
logInternalLogImpl = container "log_internal_log_impl" "Build target group: log_internal_log_impl." "C/C++" {
    tags "Container,cpp,needs-curation"
}
logInternalLogSinkSet = container "log_internal_log_sink_set" "Build target group: log_internal_log_sink_set." "C/C++" {
    tags "Container,cpp,needs-curation"
}
logInternalMessage = container "log_internal_message" "Build target group: log_internal_message." "C/C++" {
    tags "Container,cpp,needs-curation"
}
logInternalNullguard = container "log_internal_nullguard" "Build target group: log_internal_nullguard." "C/C++" {
    tags "Container,cpp,needs-curation"
}
logInternalNullstream = container "log_internal_nullstream" "Build target group: log_internal_nullstream." "C/C++" {
    tags "Container,cpp,needs-curation"
}
logInternalProto = container "log_internal_proto" "Build target group: log_internal_proto." "C/C++" {
    tags "Container,cpp,needs-curation"
}
logInternalStrip = container "log_internal_strip" "Build target group: log_internal_strip." "C/C++" {
    tags "Container,cpp,needs-curation"
}
logInternalStructured = container "log_internal_structured" "Build target group: log_internal_structured." "C/C++" {
    tags "Container,cpp,needs-curation"
}
logInternalVoidify = container "log_internal_voidify" "Build target group: log_internal_voidify." "C/C++" {
    tags "Container,cpp,needs-curation"
}
logSeverity = container "log_severity" "Build target group: log_severity." "C/C++" {
    tags "Container,cpp,needs-curation"
}
logSink = container "log_sink" "Build target group: log_sink." "C/C++" {
    tags "Container,cpp,needs-curation"
}
logSinkRegistry = container "log_sink_registry" "Build target group: log_sink_registry." "C/C++" {
    tags "Container,cpp,needs-curation"
}
logStreamer = container "log_streamer" "Build target group: log_streamer." "C/C++" {
    tags "Container,cpp,needs-curation"
}
logStructured = container "log_structured" "Build target group: log_structured." "C/C++" {
    tags "Container,cpp,needs-curation"
}
lowLevelHash = container "low_level_hash" "Build target group: low_level_hash." "C/C++" {
    tags "Container,cpp,needs-curation"
}
mallocInternal = container "malloc_internal" "Build target group: malloc_internal." "C/C++" {
    tags "Container,cpp,needs-curation"
}
memory = container "memory" "Build target group: memory." "C/C++" {
    tags "Container,cpp,needs-curation"
}
meta = container "meta" "Build target group: meta." "C/C++" {
    tags "Container,cpp,needs-curation"
}
noDestructor = container "no_destructor" "Build target group: no_destructor." "C/C++" {
    tags "Container,cpp,needs-curation"
}
nodeHashMap = container "node_hash_map" "Build target group: node_hash_map." "C/C++" {
    tags "Container,cpp,needs-curation"
}
nodeHashSet = container "node_hash_set" "Build target group: node_hash_set." "C/C++" {
    tags "Container,cpp,needs-curation"
}
nodeSlotPolicy = container "node_slot_policy" "Build target group: node_slot_policy." "C/C++" {
    tags "Container,cpp,needs-curation"
}
nonTemporalArmIntrinsics = container "non_temporal_arm_intrinsics" "Build target group: non_temporal_arm_intrinsics." "C/C++" {
    tags "Container,cpp,needs-curation"
}
nonTemporalMemcpy = container "non_temporal_memcpy" "Build target group: non_temporal_memcpy." "C/C++" {
    tags "Container,cpp,needs-curation"
}
nullability = container "nullability" "Build target group: nullability." "C/C++" {
    tags "Container,cpp,needs-curation"
}
numeric = container "numeric" "Build target group: numeric." "C/C++" {
    tags "Container,cpp,needs-curation"
}
numericRepresentation = container "numeric_representation" "Build target group: numeric_representation." "C/C++" {
    tags "Container,cpp,needs-curation"
}
optional = container "optional" "Build target group: optional." "C/C++" {
    tags "Container,cpp,needs-curation"
}
overload = container "overload" "Build target group: overload." "C/C++" {
    tags "Container,cpp,needs-curation"
}
periodicSampler = container "periodic_sampler" "Build target group: periodic_sampler." "C/C++" {
    tags "Container,cpp,needs-curation"
}
poison = container "poison" "Build target group: poison." "C/C++" {
    tags "Container,cpp,needs-curation"
}
prefetch = container "prefetch" "Build target group: prefetch." "C/C++" {
    tags "Container,cpp,needs-curation"
}
prettyFunction = container "pretty_function" "Build target group: pretty_function." "C/C++" {
    tags "Container,cpp,needs-curation"
    properties {
        "structurizr.inspection.model.element.disconnected" "ignore"
    }
}
randomBitGenRef = container "random_bit_gen_ref" "Build target group: random_bit_gen_ref." "C/C++" {
    tags "Container,cpp,needs-curation"
}
randomDistributions = container "random_distributions" "Build target group: random_distributions." "C/C++" {
    tags "Container,cpp,needs-curation"
}
randomInternalDistributionCaller = container "random_internal_distribution_caller" "Build target group: random_internal_distribution_caller." "C/C++" {
    tags "Container,cpp,needs-curation"
}
randomInternalDistributionTestUtil = container "random_internal_distribution_test_util" "Build target group: random_internal_distribution_test_util." "C/C++" {
    tags "Container,cpp,needs-curation"
}
randomInternalFastUniformBits = container "random_internal_fast_uniform_bits" "Build target group: random_internal_fast_uniform_bits." "C/C++" {
    tags "Container,cpp,needs-curation"
}
randomInternalFastmath = container "random_internal_fastmath" "Build target group: random_internal_fastmath." "C/C++" {
    tags "Container,cpp,needs-curation"
}
randomInternalGenerateReal = container "random_internal_generate_real" "Build target group: random_internal_generate_real." "C/C++" {
    tags "Container,cpp,needs-curation"
}
randomInternalIostreamStateSaver = container "random_internal_iostream_state_saver" "Build target group: random_internal_iostream_state_saver." "C/C++" {
    tags "Container,cpp,needs-curation"
}
randomInternalMockHelpers = container "random_internal_mock_helpers" "Build target group: random_internal_mock_helpers." "C/C++" {
    tags "Container,cpp,needs-curation"
}
randomInternalNonsecureBase = container "random_internal_nonsecure_base" "Build target group: random_internal_nonsecure_base." "C/C++" {
    tags "Container,cpp,needs-curation"
}
randomInternalPcgEngine = container "random_internal_pcg_engine" "Build target group: random_internal_pcg_engine." "C/C++" {
    tags "Container,cpp,needs-curation"
}
randomInternalPlatform = container "random_internal_platform" "Build target group: random_internal_platform." "C/C++" {
    tags "Container,cpp,needs-curation"
}
randomInternalPoolUrbg = container "random_internal_pool_urbg" "Build target group: random_internal_pool_urbg." "C/C++" {
    tags "Container,cpp,needs-curation"
}
randomInternalRanden = container "random_internal_randen" "Build target group: random_internal_randen." "C/C++" {
    tags "Container,cpp,needs-curation"
}
randomInternalRandenEngine = container "random_internal_randen_engine" "Build target group: random_internal_randen_engine." "C/C++" {
    tags "Container,cpp,needs-curation"
}
randomInternalRandenHwaes = container "random_internal_randen_hwaes" "Build target group: random_internal_randen_hwaes." "C/C++" {
    tags "Container,cpp,needs-curation"
}
randomInternalRandenHwaesImpl = container "random_internal_randen_hwaes_impl" "Build target group: random_internal_randen_hwaes_impl." "C/C++" {
    tags "Container,cpp,needs-curation"
}
randomInternalRandenSlow = container "random_internal_randen_slow" "Build target group: random_internal_randen_slow." "C/C++" {
    tags "Container,cpp,needs-curation"
}
randomInternalSaltedSeedSeq = container "random_internal_salted_seed_seq" "Build target group: random_internal_salted_seed_seq." "C/C++" {
    tags "Container,cpp,needs-curation"
}
randomInternalSeedMaterial = container "random_internal_seed_material" "Build target group: random_internal_seed_material." "C/C++" {
    tags "Container,cpp,needs-curation"
}
randomInternalTraits = container "random_internal_traits" "Build target group: random_internal_traits." "C/C++" {
    tags "Container,cpp,needs-curation"
}
randomInternalUniformHelper = container "random_internal_uniform_helper" "Build target group: random_internal_uniform_helper." "C/C++" {
    tags "Container,cpp,needs-curation"
}
randomInternalWideMultiply = container "random_internal_wide_multiply" "Build target group: random_internal_wide_multiply." "C/C++" {
    tags "Container,cpp,needs-curation"
}
randomRandom = container "random_random" "Build target group: random_random." "C/C++" {
    tags "Container,cpp,needs-curation"
}
randomSeedGenException = container "random_seed_gen_exception" "Build target group: random_seed_gen_exception." "C/C++" {
    tags "Container,cpp,needs-curation"
}
randomSeedSequences = container "random_seed_sequences" "Build target group: random_seed_sequences." "C/C++" {
    tags "Container,cpp,needs-curation"
}
rawHashMap = container "raw_hash_map" "Build target group: raw_hash_map." "C/C++" {
    tags "Container,cpp,needs-curation"
}
rawHashSet = container "raw_hash_set" "Build target group: raw_hash_set." "C/C++" {
    tags "Container,cpp,needs-curation"
}
rawLoggingInternal = container "raw_logging_internal" "Build target group: raw_logging_internal." "C/C++" {
    tags "Container,cpp,needs-curation"
}
sampleRecorder = container "sample_recorder" "Build target group: sample_recorder." "C/C++" {
    tags "Container,cpp,needs-curation"
}
scopedSetEnv = container "scoped_set_env" "Build target group: scoped_set_env." "C/C++" {
    tags "Container,cpp,needs-curation"
}
span = container "span" "Build target group: span." "C/C++" {
    tags "Container,cpp,needs-curation"
}
spinlockWait = container "spinlock_wait" "Build target group: spinlock_wait." "C/C++" {
    tags "Container,cpp,needs-curation"
}
stacktrace = container "stacktrace" "Build target group: stacktrace." "C/C++" {
    tags "Container,cpp,needs-curation"
}
status = container "status" "Build target group: status." "C/C++" {
    tags "Container,cpp,needs-curation"
}
statusor = container "statusor" "Build target group: statusor." "C/C++" {
    tags "Container,cpp,needs-curation"
}
strFormat = container "str_format" "Build target group: str_format." "C/C++" {
    tags "Container,cpp,needs-curation"
}
strFormatInternal = container "str_format_internal" "Build target group: str_format_internal." "C/C++" {
    tags "Container,cpp,needs-curation"
}
strerror = container "strerror" "Build target group: strerror." "C/C++" {
    tags "Container,cpp,needs-curation"
}
stringView = container "string_view" "Build target group: string_view." "C/C++" {
    tags "Container,cpp,needs-curation"
}
strings = container "strings" "Build target group: strings." "C/C++" {
    tags "Container,cpp,needs-curation"
}
stringsInternal = container "strings_internal" "Build target group: strings_internal." "C/C++" {
    tags "Container,cpp,needs-curation"
}
symbolize = container "symbolize" "Build target group: symbolize." "C/C++" {
    tags "Container,cpp,needs-curation"
}
synchronization = container "synchronization" "Build target group: synchronization." "C/C++" {
    tags "Container,cpp,needs-curation"
}
throwDelegate = container "throw_delegate" "Build target group: throw_delegate." "C/C++" {
    tags "Container,cpp,needs-curation"
}
time = container "time" "Build target group: time." "C/C++" {
    tags "Container,cpp,needs-curation"
}
timeZone = container "time_zone" "Build target group: time_zone." "C/C++" {
    tags "Container,cpp,needs-curation"
}
typeTraits = container "type_traits" "Build target group: type_traits." "C/C++" {
    tags "Container,cpp,needs-curation"
}
utf8ForCodePoint = container "utf8_for_code_point" "Build target group: utf8_for_code_point." "C/C++" {
    tags "Container,cpp,needs-curation"
}
utility = container "utility" "Build target group: utility." "C/C++" {
    tags "Container,cpp,needs-curation"
}
variant = container "variant" "Build target group: variant." "C/C++" {
    tags "Container,cpp,needs-curation"
}
vlogConfigInternal = container "vlog_config_internal" "Build target group: vlog_config_internal." "C/C++" {
    tags "Container,cpp,needs-curation"
}
vlogIsOn = container "vlog_is_on" "Build target group: vlog_is_on." "C/C++" {
    tags "Container,cpp,needs-curation"
}
