"""Stage P7 — deterministic deployment DSL generation (plan §9.3).

Reads the top-level ``deployment`` facet of the curated/enriched fact model and
emits two **machine-owned** DSL fragments that are overwritten every run:

  - ``ws.deployment_dsl``       (``generated/generated-deployment.dsl``)
    MODEL statements only: ``deploymentEnvironment { deploymentNode / containerInstance /
    infrastructureNode }`` blocks.

  - ``ws.deployment_views_dsl`` (``generated/generated-deployment-views.dsl``)
    VIEW statements only: one ``deployment system "…" { include *; autolayout lr }``
    per environment.

Both files are **always written** (unconditionally !include'd by the orchestrator's
workspace.dsl scaffold). When there are no deployment facts, a banner-only comment file
is emitted so the includes stay valid.

Returns a run-report dict::

    {"deployment_nodes": int, "envs": list[str], "views": list[str]}
"""
from __future__ import annotations

import logging
from typing import Any

from ..ids import SlugRegistry
from ..paths import Workspace

log = logging.getLogger("anon.generate_deployment")

_BANNER = ("// GENERATED BY ANON — DO NOT EDIT. Overwritten every run (plan §9).\n"
           "// Edit curation in rules/mapping-rules.yaml; views/styles live in views.dsl.\n")


def _dsl_str(s: str) -> str:
    """Wrap *s* in double-quotes, escaping backslashes and inner double-quotes."""
    return '"' + (s or "").replace("\\", "\\\\").replace('"', '\\"') + '"'


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _target_id_to_container_id(facts: dict[str, Any]) -> dict[str, str]:
    """Build a mapping from build-target id -> container_id (for packages edge resolution)."""
    return {t["id"]: t.get("container_id", t["id"]) for t in facts.get("targets", [])}


def _normalize(s: str) -> str:
    """Lowercase, alphanumeric-only key for high-confidence name matching (e.g.
    ``basket-api`` and the ``basketAPI`` container both normalize to ``basketapi``)."""
    return "".join(ch for ch in (s or "").lower() if ch.isalnum())


def _container_name_index(facts: dict[str, Any]) -> dict[str, str]:
    """``normalized name -> container_id`` for UNAMBIGUOUS deployment-image binding.

    A container is indexed under its display name and its id-suffix; a normalized key that
    would map to two different containers is dropped (ambiguous → not bound, never guessed).
    This recovers the image→container link when the deployment extractor produced no
    ``packages`` Dockerfile edge, but only on an exact normalized-name correspondence — a
    real, deterministic signal (the compose service name IS the project name), not a fuzzy
    guess. Ambiguous or absent matches leave the node unbound (handled honestly downstream)."""
    index: dict[str, str | None] = {}
    for t in facts.get("targets", []):
        cid = t.get("container_id")
        if not cid:
            continue
        keys = {_normalize(t.get("container_name", "")), _normalize(cid.split(":")[-1])}
        for key in keys:
            if not key:
                continue
            if key in index and index[key] != cid:
                index[key] = None  # collision → ambiguous, do not bind
            elif key not in index:
                index[key] = cid
    return {k: v for k, v in index.items() if v is not None}


# Human technology labels for common infrastructure images (deterministic, name-keyed).
_INFRA_TECH = (
    ("postgres", "PostgreSQL"), ("postgre", "PostgreSQL"), ("redis", "Redis"),
    ("rabbit", "RabbitMQ"), ("eventbus", "Message broker"), ("kafka", "Apache Kafka"),
    ("mongo", "MongoDB"), ("mysql", "MySQL"), ("mssql", "SQL Server"),
    ("sqlserver", "SQL Server"), ("sql", "SQL database"), ("elastic", "Elasticsearch"),
    ("nginx", "nginx"), ("seq", "Seq (logging)"), ("vault", "HashiCorp Vault"),
)


def _infra_technology(name: str) -> str:
    n = (name or "").lower()
    for needle, tech in _INFRA_TECH:
        if needle in n:
            return tech
    return "Infrastructure"


def _runtime_edge_technology(kind: str) -> str:
    return {"calls": "Synchronous call", "reads": "Reads from",
            "publishes": "Publishes to", "runtime_config": "Configuration"}.get(kind, "Runtime")


def _emit_container_instance(lines: list[str], container_ident: str) -> None:
    """Emit a containerInstance, exempt from the disconnected-element inspection: deployment
    relationships in this model are node-level, so an instance is only auto-connected when a
    peer container is co-deployed — a partial deployment legitimately leaves it edge-less."""
    lines.append(f'        containerInstance {container_ident} {{')
    lines.append("            properties {")
    lines.append('                "structurizr.inspection.model.element.disconnected" "ignore"')
    lines.append("            }")
    lines.append("        }")


def _group_by_env(nodes: list[dict], edges: list[dict]) -> dict[str, dict]:
    """Group deployment nodes and edges by environment.

    Nodes / edges without an ``env`` field land in the ``"default"`` environment.
    Returns ``{env_name: {"nodes": [...], "edges": [...]}}`` for non-env-kind nodes only.
    """
    envs: dict[str, dict] = {}

    def _env_entry(env_name: str) -> dict:
        return envs.setdefault(env_name, {"nodes": [], "edges": []})

    for node in nodes:
        if node.get("kind") == "env":
            # env nodes are the grouping construct, not rendered inside themselves
            continue
        env_name = node.get("env") or "default"
        _env_entry(env_name)["nodes"].append(node)

    for edge in edges:
        env_name = edge.get("env") or "default"
        _env_entry(env_name)["edges"].append(edge)

    return envs


# ---------------------------------------------------------------------------
# DSL emission
# ---------------------------------------------------------------------------

def _emit_deployment_dsl(
    envs: dict[str, dict],
    facts: dict[str, Any],
    slugs: SlugRegistry,
    all_edges: list[dict],
) -> tuple[str, set[str]]:
    """Emit the MODEL fragment: deploymentEnvironment blocks with nodes inside.

    Returns ``(dsl_text, renderable_envs)`` — the set of environments that have at least one
    node Structurizr will actually draw (a bound container instance or an infrastructure node).
    An env with only empty, unbound image nodes would render as an *empty* deployment view
    (``views.view.empty``), so the caller skips emitting a view for it."""
    renderable_envs: set[str] = set()
    t2c = _target_id_to_container_id(facts)
    name_index = _container_name_index(facts)
    # `packages` edges are environment-agnostic Dockerfile facts emitted WITHOUT an env,
    # so _group_by_env files them all under 'default'. Resolve them from the GLOBAL edge
    # list keyed by source image, so an image node in a non-default env still binds its
    # containerInstance (otherwise multi-env deployments lose all container bindings).
    packages_by_source: dict[str, list[str]] = {}
    for edge in all_edges:
        if edge.get("kind") == "packages":
            packages_by_source.setdefault(edge.get("source"), []).append(edge.get("target"))
    lines: list[str] = [_BANNER]

    for env_name in sorted(envs):
        env_data = envs[env_name]
        env_node_ids = {n["id"] for n in env_data["nodes"]}
        env_label = env_name.capitalize() if env_name != "default" else "Default"
        lines.append(f'deploymentEnvironment {_dsl_str(env_label)} {{')

        # Sort nodes for determinism: infra/env last, image first
        def _node_sort_key(n: dict) -> tuple:
            return (n.get("kind", ""), n["id"])

        for node in sorted(env_data["nodes"], key=_node_sort_key):
            nid = node["id"]
            ident = slugs.assign(nid)
            nname = node.get("name") or nid
            node_kind = node.get("kind", "image")
            # Description + technology on every node (Structurizr deployment inspections flag a
            # node/infra missing either). Deterministic fallbacks; honest about what we know.
            if node_kind == "infra":
                desc = node.get("description") or f"Infrastructure service `{nname}`."
                tech = node.get("technology") or _infra_technology(nname)
            else:
                desc = node.get("description") or f"Runtime service (container image) `{nname}`."
                tech = node.get("technology") or "Container image"
            tech_arg = f" {_dsl_str(tech)}"

            if node_kind == "infra":
                renderable_envs.add(env_name)  # infra nodes always render

            if node_kind == "image":
                lines.append(f'    {ident} = deploymentNode {_dsl_str(nname)} {_dsl_str(desc)}{tech_arg} {{')
                # containerInstance binding: first the explicit `packages` Dockerfile edges
                # (target build id -> container), else a high-confidence exact normalized-name
                # match (compose service name == project/container name). An image with no
                # binding is a genuine extraction coverage gap, not a guess — exempt it from the
                # empty/no-view inspections (a runtime node we can't yet map to a build container).
                bound = False
                for build_target_id in sorted(packages_by_source.get(nid, [])):
                    container_id = t2c.get(build_target_id)
                    if container_id:
                        _emit_container_instance(lines, slugs.assign(container_id))
                        bound = True
                if not bound:
                    matched = name_index.get(_normalize(nname))
                    if matched:
                        _emit_container_instance(lines, slugs.assign(matched))
                        bound = True
                if bound:
                    renderable_envs.add(env_name)  # a bound image node renders
                if not bound:
                    lines.append("        properties {")
                    lines.append('            "structurizr.inspection.model.deploymentnode.empty" "ignore"')
                    lines.append('            "structurizr.inspection.model.element.noview" "ignore"')
                    lines.append("        }")
                lines.append("    }")

            elif node_kind == "infra":
                # An infrastructureNode is NOT a valid direct child of deploymentEnvironment
                # (Structurizr grammar) — it must be nested inside a deploymentNode. Wrap each
                # infra in a host deploymentNode; the infra identifier stays global so runtime
                # edges (imageNode -> infraNode) still resolve. Both carry description+technology.
                host_ident = slugs.assign(nid + "/host")
                lines.append(f'    {host_ident} = deploymentNode {_dsl_str(nname)} '
                             f'{_dsl_str("Deployment host for " + nname + ".")}{tech_arg} {{')
                lines.append(f'        {ident} = infrastructureNode {_dsl_str(nname)} '
                             f'{_dsl_str(desc)}{tech_arg} {{')
                # An infra endpoint with no runtime edge is an extraction coverage boundary
                # (nothing in the facts connects to it), not a model defect — exempt it from
                # the disconnected-element inspection rather than dropping the node.
                lines.append('            properties {')
                lines.append('                "structurizr.inspection.model.element.disconnected" "ignore"')
                lines.append("            }")
                lines.append("        }")
                lines.append("    }")

        # runtime edges between deployment nodes (calls/reads/publishes) and the service->infra
        # configuration edges (runtime_config) that bind an image to its database / broker — the
        # latter connect the infrastructure nodes so they are not flagged disconnected (§9.3).
        _runtime_kinds = {"calls", "reads", "publishes", "runtime_config"}
        for edge in sorted(env_data["edges"], key=lambda e: (e["source"], e["target"], e["kind"])):
            if edge.get("kind") not in _runtime_kinds:
                continue
            src_id, tgt_id = edge["source"], edge["target"]
            if src_id == tgt_id:
                continue  # drop degenerate self-loops (e.g. a service's own runtime_config)
            # Both endpoints must be nodes actually emitted in THIS environment block;
            # otherwise the relationship would reference an undefined identifier and the
            # Structurizr deployment DSL would fail to parse. Skip rather than mint a
            # fallback id for a node that is never rendered here.
            if src_id not in env_node_ids or tgt_id not in env_node_ids:
                log.debug("deployment env %s: skipping %s edge %s -> %s (endpoint not a node in this env)",
                          env_name, edge.get("kind"), src_id, tgt_id)
                continue
            si = slugs.assign(src_id)
            ti = slugs.assign(tgt_id)
            label = edge.get("kind") or "Uses"
            tech = _runtime_edge_technology(edge.get("kind", ""))
            # technology (2nd positional) clears model.relationship.technology on deployment edges
            lines.append(f'    {si} -> {ti} {_dsl_str(label)} {_dsl_str(tech)}')

        lines.append("}")

    return "\n".join(lines) + "\n", renderable_envs


def _emit_views_dsl(envs: dict[str, dict], system_ident: str,
                    renderable_envs: set[str]) -> str:
    """Emit the VIEW fragment: one deployment view per environment that has renderable content.

    An environment whose nodes are all empty/unbound would render as an *empty* deployment view
    (the ``views.view.empty`` inspection); those are skipped (the model nodes still exist)."""
    lines: list[str] = [_BANNER]
    for env_name in sorted(envs):
        if env_name not in renderable_envs:
            continue
        env_label = env_name.capitalize() if env_name != "default" else "Default"
        view_key = f"deployment-{env_name}"
        lines.append(f'deployment {system_ident} {_dsl_str(env_label)} {_dsl_str(view_key)} {{')
        lines.append("    include *")
        lines.append("    autolayout lr")
        lines.append("}")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def run(ws: Workspace, facts: dict[str, Any], slugs: SlugRegistry) -> dict[str, Any]:
    """Generate deployment DSL files and return a run-report dict.

    ``facts`` is the curated/enriched fact model (targets carry ``container_id``; may
    carry a top-level ``deployment`` facet).  ``slugs`` is a :class:`SlugRegistry`
    already populated with the build-container identifiers, so that
    ``slugs.assign(container_id)`` returns the SAME identifier as in
    ``generated-components.dsl``.

    Always writes both ``ws.deployment_dsl`` and ``ws.deployment_views_dsl``.
    """
    ws.deployment_dsl.parent.mkdir(parents=True, exist_ok=True)

    deploy = facts.get("deployment") or {}
    raw_nodes: list[dict] = deploy.get("nodes") or []
    raw_edges: list[dict] = deploy.get("edges") or []

    if not raw_nodes:
        # No deployment facts — write banner-only files (still valid !includes)
        ws.deployment_dsl.write_text(_BANNER, encoding="utf-8", newline="")
        ws.deployment_views_dsl.write_text(_BANNER, encoding="utf-8", newline="")
        log.info("no deployment facts — wrote banner-only deployment DSL files")
        return {"deployment_nodes": 0, "envs": [], "views": []}

    envs = _group_by_env(raw_nodes, raw_edges)

    # system identifier: the orchestrator uses the variable name 'system' in workspace.dsl
    system_ident = "system"

    model_dsl, renderable_envs = _emit_deployment_dsl(envs, facts, slugs, raw_edges)
    views_dsl = _emit_views_dsl(envs, system_ident, renderable_envs)

    ws.deployment_dsl.write_text(model_dsl, encoding="utf-8", newline="")
    ws.deployment_views_dsl.write_text(views_dsl, encoding="utf-8", newline="")

    env_names = sorted(envs.keys())
    view_keys = [f"deployment-{e}" for e in sorted(renderable_envs)]
    log.info("deployment DSL: %d nodes, envs=%s", len(raw_nodes), env_names)
    return {
        "deployment_nodes": len(raw_nodes),
        "envs": env_names,
        "views": view_keys,
    }
