"""Machine-owned documentation + decision records for the generated model (plan §9),
plus the engine §1 per-container DATASHEETS and the guided tour (``arch datasheet``).

Structurizr's workspace inspections flag a software system that *has containers but no
documentation / no decisions* as an ERROR (``model.softwaresystem.documentation`` /
``model.softwaresystem.decisions``). Anon already knows enough — the container set,
the edge count, the coverage stratum, and *how* the model was produced — to attach an
honest, generated overview page and a baseline ADR explaining the build-graph-is-truth
invariant. Both are written into ``generated/docs`` / ``generated/adrs`` (machine-owned,
overwritten every run, never hand-edited, §9) and attached via ``!docs`` / ``!adrs`` in the
scaffolded ``workspace.dsl``.

**Datasheets (engine plan §1).** A datasheet is a cited reference-manual entry per
container — explicitly NOT an essay. The headline value is the always-available L0/L1
content: *named* fan-in/out with evidence layers, what the container owns, and its
health/coverage. The "public surface" field is CONDITIONAL on L2 and is honestly
``"L2 not extracted"`` when absent — never guessed (§1.1). The guided tour is a
deterministic structural walk by **salience** (weight + a seam boost for
``interop``/``contract``/boundary edges, §1.1) with a separate exhaustive
**critical-seams** list so a low-weight-but-critical edge is never buried by the
traversal heuristic. Honesty numbers are single-sourced (§0.4): container confidence
from :func:`confidence.container_confidence`, strata from
:func:`scorecard.element_strata`, the lift from the generator's two-step
``build_containers`` → ``build_container_edges`` — one lift, one truth.

Determinism: the content is a pure function of the facts (container names/descriptions,
counts) plus the run's commit/date carried in ``provenance``. These files are **not** part
of the byte-identical golden set (§18.4) — they document the model, they are not the model.
"""
from __future__ import annotations

import argparse
import re
from typing import Any

from .. import confidence, salience as _salience_mod, scorecard
from ..config import load_yaml
from ..ids import SlugRegistry
from ..jsonio import dump_json, load_json
from ..model import content_hash
from ..paths import Workspace, resolve_workspace

# A Structurizr ADR is parsed by the Markdown decision importer: id from the filename's
# leading number, title from the first `#` heading, status from the `## Status` section.
_ADR_FILENAME = "0001-build-graph-is-the-source-of-structural-truth.md"


def _provenance_date(facts: dict[str, Any]) -> str:
    """A YYYY-MM-DD date for the ADR, taken from the run's provenance (never `Date.now`)."""
    gen = (facts.get("provenance", {}) or {}).get("generated_at", "")
    if isinstance(gen, str) and len(gen) >= 10 and gen[4] == "-" and gen[7] == "-":
        return gen[:10]
    return "unknown"


def _overview_md(system_name: str, containers: list[tuple[str, str]],
                 n_targets: int, n_edges: int, l0_pct: float | None) -> str:
    lines = [
        "# System overview",
        "",
        f"`{system_name}` — a C4 architecture model generated by **Anon** from the build "
        "graph, refined by source-level evidence. This page is regenerated on every run.",
        "",
        "## Containers",
        "",
        f"The model groups **{n_targets} build target(s)** into **{len(containers)} "
        f"container(s)** connected by **{n_edges} relationship(s)**.",
        "",
    ]
    for name, desc in containers:
        lines.append(f"- **{name}** — {desc}")
    lines += [
        "",
        "## How this model was produced",
        "",
        "Structure (containers and their dependencies) is extracted **deterministically** from "
        "the build graph — CMake / MSBuild / `.sln` / `.csproj` link and reference edges — then "
        "refined, never replaced, by source-level evidence (symbols, includes, interop). Names "
        "and descriptions may be enriched by a language model, but **no relationship or element "
        "is ever invented by an LLM**. See the architecture decision records for the governing "
        "invariants.",
        "",
    ]
    if l0_pct is not None:
        lines += [
            "## Coverage",
            "",
            f"Build-graph (L0) coverage of this model: **{l0_pct:.0f}%**. Findings derived below "
            "the L0 floor are downgraded to advisory rather than asserted.",
            "",
        ]
    return "\n".join(lines) + "\n"


def _adr_md(system_name: str, date: str) -> str:
    return (
        "# 1. The build graph is the source of structural truth\n"
        "\n"
        f"Date: {date}\n"
        "\n"
        "## Status\n"
        "\n"
        "Accepted\n"
        "\n"
        "## Context\n"
        "\n"
        f"This architecture model of `{system_name}` is generated, not hand-drawn. A generated "
        "model is only trustworthy if its structure is reproducible and evidence-backed rather "
        "than inferred.\n"
        "\n"
        "## Decision\n"
        "\n"
        "The build graph (CMake / MSBuild / `.sln` / `.csproj` targets and their declared "
        "link/reference dependencies) is treated as the source of structural truth. Source-level "
        "analysis (symbols, includes, interop) *refines* that structure — corroborating, "
        "weighting, and naming — but never adds a relationship that has no build or source "
        "evidence. Language-model enrichment touches names and descriptions only.\n"
        "\n"
        "## Consequences\n"
        "\n"
        "The same inputs produce a byte-identical model, so the diagram can be diffed and "
        "reviewed like code. Dependencies that exist at runtime but are invisible to the build "
        "graph (e.g. reflection, dynamic loading) are not shown unless a later evidence layer "
        "surfaces them; the coverage report makes that boundary explicit.\n"
    )


def run(ws: Workspace, facts: dict[str, Any], containers: list[tuple[str, str]],
        n_edges: int, *, l0_pct: float | None = None) -> dict[str, Any]:
    """Write the generated overview doc + baseline ADR. Always writes at least one file into
    each directory so the ``!docs`` / ``!adrs`` includes in ``workspace.dsl`` resolve."""
    system_name = ws.repo.name or "System"
    n_targets = len(facts.get("targets", []))
    ws.docs_dir.mkdir(parents=True, exist_ok=True)
    ws.adrs_dir.mkdir(parents=True, exist_ok=True)
    (ws.docs_dir / "01-overview.md").write_text(
        _overview_md(system_name, containers, n_targets, n_edges, l0_pct),
        encoding="utf-8", newline="")
    (ws.adrs_dir / _ADR_FILENAME).write_text(
        _adr_md(system_name, _provenance_date(facts)), encoding="utf-8", newline="")
    return {"docs": 1, "adrs": 1}


# ======================================================================= datasheets (§1)

# datasheets/3 (datasheet-enrichment plan §4.6): adds a top-level `system` datasheet and
# nests a `components` list (the build-target members) inside each multi-member container,
# on top of the datasheets/2 narrative / metrics / technology / footprint / vitals / risk /
# tests blocks. Additive for readers; the schema string is bumped because the top-level and
# per-row key sets are part of the GUI/agent contract.
DATASHEETS_SCHEMA = "datasheets/3"
TOUR_SCHEMA = "datasheets-tour/1"
_SURFACE_CAP = 25          # public-surface symbols per datasheet (a manual, not a dump)
_TECH_CAP = 15             # package names per technology fingerprint (a manual, not a dump)
_TEST_CAP = 10             # test targets listed per datasheet
_TOUR_MAX_HOPS = 10
_CONF_RANK = {"high": 0, "medium": 1, "low": 2}

# The pinned test-target heuristic (datasheet plan §6.3): a name or path SEGMENT
# `test`/`tests` (delimited — `Contest.csproj` does not match). A *proxy* for test
# adjacency, honestly labeled as such — never called "coverage".
_TEST_SEGMENT = re.compile(r"(^|[/._\-])tests?($|[/._\-])", re.IGNORECASE)


def _is_test_target(t: dict[str, Any]) -> bool:
    name = t.get("name") or ""
    path = (t.get("path") or "").replace("\\", "/")
    return bool(_TEST_SEGMENT.search(name) or _TEST_SEGMENT.search(path))


def _lift(facts: dict[str, Any]):
    """The generator's two-step container lift — imported lazily because
    ``generate_structurizr`` imports this module at its top (a top-level import here
    would be circular)."""
    from .generate_structurizr import (_container_description,
                                       build_container_edges, build_containers)
    containers = build_containers(facts)
    t2c = {m: c.cid for c in containers.values() for m in c.members}
    cedges = build_container_edges(facts, t2c)
    return containers, t2c, cedges, _container_description


def _edge_layer_set(rel: dict[str, Any]) -> set[str]:
    return {layer for layer in (confidence._LAYER_OF.get(e.get("type"))
                                for e in rel.get("evidence", []) or []) if layer}


def _l2_ran(facts: dict[str, Any]) -> bool:
    """Did any symbol/include-level extraction contribute evidence to this run?"""
    return any(e.get("type") in ("symbol_use", "include")
               for r in facts.get("relationships", []) or []
               for e in r.get("evidence", []) or [])


def _pair_detail(facts: dict[str, Any], t2c: dict[str, str]):
    """Per container pair: evidence layers + the strongest contributing confidence —
    so a datasheet's fan-in line can say "(weight 7, L1 project_ref + L2 symbol_use)"."""
    layers: dict[tuple[str, str], set[str]] = {}
    conf: dict[tuple[str, str], str] = {}
    for r in facts.get("relationships", []) or []:
        cs, ct = t2c.get(r.get("source")), t2c.get(r.get("target"))
        if not cs or not ct or cs == ct:
            continue
        key = (cs, ct)
        layers.setdefault(key, set()).update(_edge_layer_set(r))
        c = r.get("confidence")
        if c in _CONF_RANK and _CONF_RANK[c] < _CONF_RANK.get(conf.get(key, "low"), 99):
            conf[key] = c
        conf.setdefault(key, c if c in _CONF_RANK else "low")
    return layers, conf


def _fan_entry(direction_key: str, other: str, other_name: str, e: dict[str, Any],
               layers: set[str], conf: str) -> dict[str, Any]:
    return {direction_key: other, "name": other_name, "weight": e["weight"],
            "kind": e.get("kind") or "uses", "declared": bool(e["declared"]),
            "evidence_layers": sorted(layers), "confidence": conf}


def _dominant_signal(members: list[dict[str, Any]]) -> str | None:
    """The most common ``grouped_by.signal`` among members (ties broken by name)."""
    counts: dict[str, int] = {}
    for t in members:
        sig = (t.get("grouped_by") or {}).get("signal")
        if sig:
            counts[sig] = counts.get(sig, 0) + 1
    if not counts:
        return None
    return sorted(counts.items(), key=lambda kv: (-kv[1], kv[0]))[0][0]


# --------------------------------------------- datasheets/2 blocks (enrichment plan §7)

def _container_metrics(members: list[dict[str, Any]]) -> dict[str, Any]:
    """Sum the metrics/1 per-language rows over the container's members at render time —
    container totals are never stored twice (plan §3.1). Honest absence when no member
    carries source metrics (e.g. an external/package container, or a pre-1.3 artifact)."""
    langs: dict[str, dict[str, int]] = {}
    todo = 0
    engine = None
    for t in members:
        m = t.get("metrics") or {}
        for row in m.get("by_language") or []:
            agg = langs.setdefault(row.get("language", "?"),
                                   {"files": 0, "blank": 0, "comment": 0, "code": 0})
            for k in ("files", "blank", "comment", "code"):
                agg[k] += row.get(k, 0) or 0
        todo += m.get("todo_count", 0) or 0
        engine = engine or m.get("engine")
    if not langs:
        return {"available": False, "reason": "no source metrics extracted",
                "engine": None, "total": None, "todo_count": 0, "by_language": []}
    by_language = [{"language": lang, **vals} for lang, vals in sorted(langs.items())]
    total = {k: sum(r[k] for r in by_language)
             for k in ("files", "blank", "comment", "code")}
    return {"available": True, "engine": engine, "total": total,
            "todo_count": todo, "by_language": by_language}


def _container_technology(members: list[dict[str, Any]]) -> dict[str, Any]:
    """The §6.1 technology fingerprint: DIRECT package refs stamped on member targets
    (survives curation's drop_external). Capped — a manual, not a lockfile dump."""
    pkgs = sorted({p for t in members for p in (t.get("package_refs") or []) if p})
    return {"packages": pkgs[:_TECH_CAP], "packages_total": len(pkgs)}


def _tests_index(facts: dict[str, Any]) -> tuple[set[str], dict[str, set[str]]]:
    """``(test_target_ids, target_id -> test ids that depend on it)`` — pure L0 (§6.3).

    Computed from the EXTRACTED facts when the caller can supply them (see
    :func:`build_datasheets` ``tests_facts``): the common curation pattern *excludes*
    test projects from the model, which would otherwise empty this signal exactly where
    it matters."""
    test_ids = {t["id"] for t in facts.get("targets", []) or []
                if t.get("id") and _is_test_target(t)}
    tested_by: dict[str, set[str]] = {}
    for r in facts.get("relationships", []) or []:
        if r.get("source") in test_ids and r.get("target"):
            tested_by.setdefault(r["target"], set()).add(r["source"])
    return test_ids, tested_by


def _tests_block(member_ids: list[str], test_ids: set[str],
                 tested_by: dict[str, set[str]]) -> dict[str, Any]:
    refs = sorted({src for m in member_ids for src in tested_by.get(m, set())})
    with_tests = sum(1 for m in member_ids if tested_by.get(m))
    return {"test_targets": refs[:_TEST_CAP], "test_targets_total": len(refs),
            "members_with_tests": with_tests,
            "members": len(member_ids),
            "note": "adjacency proxy from the build graph (a test target that "
                    "references the member) — NOT coverage"}


def _risk_echo(risk_report: dict[str, Any] | None, accept_hashes: set[str],
               cid: str) -> dict[str, Any]:
    """ECHO of risk-report.json — the datasheet never recomputes a risk number (§0.4).
    A report computed from different facts is refused as stale, never half-trusted.
    *accept_hashes* holds the hash of every facts tier currently on disk (enriched /
    curated / extracted): `arch risk` reads the curated tier while the datasheets read
    the enriched one, and within one run those are the same model."""
    if not risk_report:
        return {"available": False, "reason": "no risk-report.json — run `arch risk`"}
    if risk_report.get("derived_from_hash") not in accept_hashes:
        return {"available": False,
                "reason": "risk-report.json was computed from different facts — re-run"}
    mine = [f for f in risk_report.get("findings", []) or []
            if cid in (f.get("elements") or [])]
    kinds = sorted({f.get("kind", "?") for f in mine})
    echo: dict[str, Any] = {"available": True,
                            "in_cycle": "cycle" in kinds, "hub": "hub" in kinds,
                            "finding_kinds": kinds,
                            "instability_I": None, "abstractness_A": None,
                            "distance_D": None}
    for f in mine:
        si = f.get("severity_inputs") or {}
        if f.get("kind") == "main-sequence":
            echo["instability_I"] = si.get("instability_I")
            echo["abstractness_A"] = si.get("abstractness_A")
            echo["distance_D"] = f.get("severity")
        elif f.get("kind") == "hub" and echo["instability_I"] is None:
            echo["instability_I"] = si.get("instability_I")
    return echo


def _footprint(measurements: dict[str, Any] | None, member_ids: set[str],
               facts_hash: str) -> dict[str, Any]:
    """Join the Class-V measurements sidecar (plan §5) — timestamped by design, never
    part of any hash; absence is the normal case, staleness is a checkable join."""
    if not measurements:
        return {"available": False,
                "reason": "no measurements.json — run `arch measure` after a build"}
    rows = [r for r in measurements.get("targets", []) or []
            if r.get("id") in member_ids and r.get("found")]
    stale = measurements.get("derived_from_hash") != facts_hash
    if not rows:
        return {"available": False, "stale": stale,
                "reason": "no build artifacts found for this container's members"}
    return {"available": True,
            "size_bytes": sum(r.get("size_bytes", 0) or 0 for r in rows),
            "artifacts": len(rows),
            "measured_at": measurements.get("measured_at"),
            "commit": measurements.get("commit"),
            "stale": stale}


def _cite_universe(facts: dict[str, Any], containers) -> set[str]:
    """Every id a narrative key point may cite: element ids, container ids, and both
    raw `rel:` ids and bare `source->target` edge keys (target- and container-level)."""
    ids: set[str] = {cid for cid in containers}
    for t in facts.get("targets", []) or []:
        if t.get("id"):
            ids.add(t["id"])
        # ADR cites (informative-llm-narratives §2.3): the `adr:<id>` tags adr.run stamped on
        # targets are first-class citable ids, so a decision key point resolves.
        for tag in (t.get("tags") or []):
            if isinstance(tag, str) and tag.startswith("adr:"):
                ids.add(tag)
    t2c = {m: c.cid for c in containers.values() for m in c.members}
    for r in facts.get("relationships", []) or []:
        s, t = r.get("source"), r.get("target")
        if not s or not t:
            continue
        if r.get("id"):
            ids.add(r["id"])
        ids.add(f"{s}->{t}")
        cs, ct = t2c.get(s), t2c.get(t)
        if cs and ct:
            ids.add(f"{cs}->{ct}")
    return ids


def _norm_key_points(raw: Any) -> list[dict[str, Any]]:
    """Normalize override/LLM key points to ``[{text, cites[]}]`` (≤5, plan §4.2)."""
    out = []
    for kp in (raw or [])[:5]:
        if isinstance(kp, str):
            out.append({"text": kp, "cites": []})
        elif isinstance(kp, dict) and kp.get("text"):
            cites = [str(c) for c in (kp.get("cites") or []) if c]
            out.append({"text": str(kp["text"]), "cites": cites})
    return out


def _narrative_block(cid: str, overrides: dict[str, Any] | None,
                     proposed: dict[str, Any] | None, facts_hash: str,
                     cite_universe: set[str]) -> dict[str, Any]:
    """The Class-N narrative (plan §4): human override (hand tier, wins forever) >
    LLM proposal carried in the enriched facts > honest absence. A human override is
    never machine-rejected — unresolvable citations become a `stale_citations` warning,
    not a hard fail (§4.4)."""
    ov = ((overrides or {}).get("narratives") or {}).get(cid)
    if isinstance(ov, dict) and (ov.get("abstract_md") or ov.get("key_points")):
        kps = _norm_key_points(ov.get("key_points"))
        bad = sorted({c for kp in kps for c in kp["cites"] if c not in cite_universe})
        return {"source": "human", "abstract_md": str(ov.get("abstract_md") or ""),
                "key_points": kps, "model_id": None, "derived_from_hash": None,
                "stale": False, "stale_citations": bad, "reason": ""}
    rec = (proposed or {}).get(cid)
    if isinstance(rec, dict) and rec.get("error"):
        return {"source": "none", "abstract_md": "", "key_points": [], "model_id": None,
                "derived_from_hash": None, "stale": False, "stale_citations": [],
                "reason": f"llm-narrative-failed: {rec['error']}"}
    if isinstance(rec, dict) and rec.get("abstract_md"):
        return {"source": "llm", "abstract_md": rec["abstract_md"],
                "key_points": _norm_key_points(rec.get("key_points")),
                "model_id": rec.get("model_id"),
                "derived_from_hash": rec.get("derived_from_hash"),
                "stale": rec.get("derived_from_hash") != facts_hash,
                # informative-llm-narratives §4/§3: surface the band + method for the GUI
                # char-meter and the "agentic" provenance chip (advisory; default omitted).
                "size_band": rec.get("size_band"),
                "method": rec.get("method", "deterministic"),
                "stale_citations": [], "reason": ""}
    return {"source": "none", "abstract_md": "", "key_points": [], "model_id": None,
            "derived_from_hash": None, "stale": False, "stale_citations": [],
            "reason": "no LLM narrative on this run and no hand-written override "
                      "(rules/datasheet-overrides.yaml)"}


_OVERRIDES_HEADER = (
    "# rules/datasheet-overrides.yaml — hand-owned (datasheet-enrichment plan §4.4).\n"
    "# Per-container narrative overrides: they WIN over any LLM proposal, survive\n"
    "# every run, and are never machine-rejected (an unresolvable citation renders\n"
    "# as a warning). Accepting a GUI/LLM proposal copies it here — from then on it\n"
    "# is yours. NOTE: this file is rewritten whole on GUI accept (comments above\n"
    "# this header are not preserved).\n")


def accept_narrative(ws: Workspace, container_id: str, *,
                     abstract_md: str | None = None,
                     key_points: list[dict[str, Any]] | None = None) -> dict[str, Any]:
    """Accept a narrative into the hand-owned overrides file (plan §4.4 / §8): the
    GUI's one-click "accept LLM proposal" (no body → copy the current proposal from
    the enriched facts) or an edited human narrative (body supplied). Returns
    ``{"new_text", "accepted"}`` for the caller to write through its reviewed-write
    path; raises ``KeyError`` (no such proposal) / ``ValueError`` (no propose run)."""
    import yaml as _yaml
    if abstract_md is None:
        if not ws.enriched_facts.exists():
            raise ValueError("no enriched facts — run with --llm-propose first")
        enriched = load_json(ws.enriched_facts)
        # The proposal may live at any altitude: container, component (target), or the
        # single system record (informative-llm-narratives §6.2/§6.3 — same accept path).
        rec = (enriched.get("containers_narrative") or {}).get(container_id) \
            or (enriched.get("components_narrative") or {}).get(container_id)
        sysrec = enriched.get("system_narrative") or {}
        if not rec and sysrec.get("element_id") == container_id:
            rec = sysrec
        if not isinstance(rec, dict) or not rec.get("abstract_md"):
            raise KeyError(container_id)
        abstract_md = rec["abstract_md"]
        key_points = rec.get("key_points") or []
    existing = load_yaml(ws.datasheet_overrides)
    narratives = existing.setdefault("narratives", {})
    narratives[container_id] = {
        "abstract_md": abstract_md,
        "key_points": [{"text": kp["text"], "cites": list(kp["cites"])}
                       for kp in _norm_key_points(key_points)],
    }
    body = _yaml.safe_dump(existing, sort_keys=True, allow_unicode=True,
                           default_flow_style=False)
    return {"new_text": _OVERRIDES_HEADER + body, "accepted": container_id}


def reset_narrative(ws: Workspace, container_id: str) -> dict[str, Any]:
    """Reset to the LLM proposal (informative-llm-narratives §6.1): remove the hand-owned
    override for *container_id* so the element falls back to its LLM proposal (or honest
    absence). Returns ``{"new_text", "accepted"}``; raises ``KeyError`` when there is no
    override to remove."""
    import yaml as _yaml
    existing = load_yaml(ws.datasheet_overrides)
    narratives = existing.get("narratives") or {}
    if container_id not in narratives:
        raise KeyError(container_id)
    del narratives[container_id]
    if not narratives:
        existing.pop("narratives", None)
    body = _yaml.safe_dump(existing, sort_keys=True, allow_unicode=True,
                           default_flow_style=False)
    return {"new_text": _OVERRIDES_HEADER + body, "accepted": container_id}


def git_vitals(repo, facts: dict[str, Any], containers) -> tuple[dict[str, Any] | None, str | None]:
    """Per-container git vitals (plan §6.4), CONDITIONAL on committed history exactly
    like risk's churn detector: the window is anchored to the HEAD commit's date (never
    wall-clock), authors are a COUNT (names never leave git — an egress/privacy hazard
    with no architectural value). Returns ``(per_cid, degraded_reason)``; out-of-tree /
    no-history is the normal absent answer, not an error."""
    from .risk import CHURN_WINDOW_DAYS, _git
    import datetime as _dt
    inside = _git(repo, "rev-parse", "--is-inside-work-tree")
    if not inside or inside.strip() != "true":
        return None, "not a git repository"
    shallow = _git(repo, "rev-parse", "--is-shallow-repository")
    if shallow and shallow.strip() == "true":
        return None, "shallow clone — history truncated"
    head_date = _git(repo, "log", "-1", "--format=%cI")
    if not head_date or not head_date.strip():
        return None, "no commits"
    head = _dt.datetime.fromisoformat(head_date.strip())
    since = (head - _dt.timedelta(days=CHURN_WINDOW_DAYS)).isoformat()
    log = _git(repo, "log", f"--since={since}", "--name-only",
               "--format=\x01%H\x01%aE\x01%cI", timeout=300)
    if log is None:
        return None, "git log failed"
    prefix = (_git(repo, "rev-parse", "--show-prefix") or "").strip()

    by_id = {t["id"]: t for t in facts.get("targets", []) or [] if t.get("id")}
    dir_to_cid: list[tuple[str, str]] = []
    for cid, c in containers.items():
        for tid in c.members:
            path = (by_id.get(tid, {}).get("path") or "").replace("\\", "/")
            d = path.rsplit("/", 1)[0] if "/" in path else path
            if d:
                dir_to_cid.append((prefix + d.rstrip("/") + "/", cid))
    dir_to_cid.sort(key=lambda x: (-len(x[0]), x[0]))

    commits: dict[str, int] = {}
    authors: dict[str, set[str]] = {}
    last: dict[str, str] = {}
    cur_author = cur_date = ""
    touched: set[str] = set()

    def _flush() -> None:
        for cid in touched:
            commits[cid] = commits.get(cid, 0) + 1
            if cur_author:
                authors.setdefault(cid, set()).add(cur_author)
            # git log is newest-first: the FIRST commit touching a container is its
            # most recent touch.
            last.setdefault(cid, cur_date)

    for line in log.splitlines() + ["\x01end\x01\x01"]:
        if line.startswith("\x01"):
            _flush()
            touched = set()
            parts = line.split("\x01")
            cur_author = parts[2] if len(parts) > 2 else ""
            cur_date = (parts[3] if len(parts) > 3 else "")[:10]
            continue
        f = line.strip().replace("\\", "/")
        if not f:
            continue
        for d, cid in dir_to_cid:
            if f.startswith(d):
                touched.add(cid)
                break

    per: dict[str, Any] = {}
    for cid in containers:
        per[cid] = {"available": True, "window_days": CHURN_WINDOW_DAYS,
                    "window_anchor": head_date.strip()[:10],
                    "churn_commits": commits.get(cid, 0),
                    "last_touched": last.get(cid),
                    "authors": len(authors.get(cid, set()))}
    return per, None


def system_identity(facts: dict[str, Any],
                    overrides: dict[str, Any] | None = None) -> tuple[str, str]:
    """``(system_id, system_name)`` for the whole software system — a deterministic pure
    function of the facts (so enrich's system-narrative pass and the datasheet builder
    agree on the id) with a hand override via ``rules/datasheet-overrides.yaml`` `system:`.
    Name defaults to the repo basename; the id is a stable ``system:<slug>``."""
    repo = ((facts.get("provenance") or {}).get("repo")) or ""
    name = re.split(r"[\\/]", repo.rstrip("\\/"))[-1] if repo else ""
    ov = (overrides or {}).get("system") or {}
    name = (ov.get("name") or name or "System").strip() or "System"
    slug = re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-") or "system"
    return f"system:{slug}", name


def _component_sheet(t: dict[str, Any], owner_cid: str, *, facts: dict[str, Any],
                     by_id: dict[str, dict[str, Any]], t2c: dict[str, str], containers,
                     comp_narratives: dict[str, Any], narrative_anchor: str,
                     cites: set[str], test_ids: set[str], tested_by: dict[str, set[str]],
                     measurements: dict[str, Any] | None, facts_hash: str,
                     overrides: dict[str, Any] | None = None) -> dict[str, Any]:
    """One component datasheet (plan §4.6): a build-target member rendered with the same
    block vocabulary as its container but at target altitude — its own metrics/technology,
    target→target fan-in/out (cross-container hops flagged), owned L2 components, tests,
    and the LLM narrative IF this component was salient enough to get one (else honest
    absence). Reuses the container block builders with a single-member list."""
    tid = t["id"]
    fan_in, fan_out = [], []
    for r in facts.get("relationships", []) or []:
        s, tt = r.get("source"), r.get("target")
        w = r.get("weight", 1) or 1
        if tt == tid and s in by_id:
            oc = t2c.get(s)
            fan_in.append({"from": s, "name": by_id[s].get("name", s), "weight": w,
                           "cross_container": oc != owner_cid,
                           "container": containers[oc].name if oc in containers else None})
        if s == tid and tt in by_id:
            oc = t2c.get(tt)
            fan_out.append({"to": tt, "name": by_id[tt].get("name", tt), "weight": w,
                            "cross_container": oc != owner_cid,
                            "container": containers[oc].name if oc in containers else None})
    fan_in.sort(key=lambda x: (-x["weight"], x["from"]))
    fan_out.sort(key=lambda x: (-x["weight"], x["to"]))
    l2_components = sorted({(comp.get("name") or comp.get("id"))
                            for comp in (t.get("components") or [])
                            if comp.get("name") or comp.get("id")})
    tags = t.get("tags") or []
    return {
        "id": tid,
        "name": t.get("llm_name") or t.get("name") or tid,
        "narrative": _narrative_block(tid, overrides, comp_narratives, narrative_anchor, cites),
        "purpose": {"text": t.get("description") or "",
                    "responsibilities": [r for r in (t.get("responsibilities") or []) if r][:3],
                    "enriched": bool(t.get("llm_name"))},
        "owns": {"path": (t.get("path") or "").replace("\\", "/"),
                 "namespaces": sorted(t.get("namespaces") or []),
                 "components": l2_components[:_SURFACE_CAP]},
        "metrics": _container_metrics([t]),
        "technology": _container_technology([t]),
        "fan_in": fan_in[:_TECH_CAP],
        "fan_out": fan_out[:_TECH_CAP],
        "footprint": _footprint(measurements, {tid}, facts_hash),
        "tests": _tests_block([tid], test_ids, tested_by),
        "health": {"language": t.get("language"),
                   "naming_confidence": t.get("naming_confidence"),
                   "needs_curation": "needs-curation" in tags,
                   "external": "external" in tags},
    }


def _system_sheet(facts: dict[str, Any], containers, cedges,
                  by_id: dict[str, dict[str, Any]], *, system_id: str, system_name: str,
                  sys_narratives: dict[str, Any], narrative_anchor: str, cites: set[str],
                  measurements: dict[str, Any] | None, facts_hash: str, l2: bool,
                  enriched: bool, overrides: dict[str, Any] | None = None) -> dict[str, Any]:
    """The whole-system datasheet (plan §4.6): the system narrative (synthesized 'what it
    does') over aggregate code metrics + a technology union + structural counts. Surfaced
    on the context view. Reuses the container metric/technology aggregators over ALL
    targets — system totals are never stored twice (§3.1)."""
    all_members = list(by_id.values())
    internal = [cid for cid in containers
                if not ({"external", "person"} & containers[cid].tags)]
    comp_total = sum(1 for c in containers.values()
                     for m in c.members if m in by_id and len(c.members) >= 2)
    langs = sorted({row.get("language", "") for t in all_members
                    for row in (t.get("metrics") or {}).get("by_language", []) or []} - {""})
    return {
        "id": system_id,
        "name": system_name,
        "narrative": _narrative_block(system_id, overrides, sys_narratives,
                                      narrative_anchor, cites | {system_id}),
        "metrics": _container_metrics(all_members),
        "technology": _container_technology(all_members),
        "counts": {"containers": len(containers),
                   "internal_containers": len(internal),
                   "external_containers": len(containers) - len(internal),
                   "components": comp_total,
                   "edges": len(cedges),
                   "languages": langs},
        "footprint": _footprint(measurements, set(by_id), facts_hash),
        "health": {"l2_extracted": l2, "enriched": enriched},
    }


def build_datasheets(facts: dict[str, Any], *,
                     layering_rules: dict[str, Any] | None = None,
                     risk_report: dict[str, Any] | None = None,
                     vitals: dict[str, Any] | None = None,
                     vitals_reason: str | None = None,
                     measurements: dict[str, Any] | None = None,
                     overrides: dict[str, Any] | None = None,
                     tests_facts: dict[str, Any] | None = None,
                     accept_hashes: set[str] | None = None) -> dict[str, Any]:
    """The machine-readable datasheet set (engine §1.6 — the GUI/agent API contract;
    datasheets/2 per the enrichment plan §7).

    Pure function of its inputs: every fan-in/out line cites its evidence layers, the
    public surface is honestly conditional on L2, and all honesty numbers come from the
    shipped single-source functions (§0.4). The datasheets/2 side inputs are gathered by
    :func:`run_datasheets` (risk report, git vitals, measurements sidecar, the hand-owned
    narrative overrides) and ECHOED here — risk numbers are never recomputed, a stale
    risk report / measurement is flagged, never half-trusted."""
    containers, t2c, cedges, container_description = _lift(facts)
    by_id = {t["id"]: t for t in facts.get("targets", []) or [] if t.get("id")}
    conf_c = confidence.container_confidence(facts)
    strata_c = scorecard.container_strata(facts)
    pair_layers, pair_conf = _pair_detail(facts, t2c)
    l2 = _l2_ran(facts)
    prov = facts.get("provenance") or {}
    enriched = prov.get("enrich_mode") not in (None, "no-llm")

    # datasheets/2 inputs (enrichment plan §7). Test adjacency reads the EXTRACTED facts
    # when supplied — curation usually excludes test projects from the model, and the
    # signal must survive that.
    facts_hash = content_hash(facts)
    risk_accept = (accept_hashes or set()) | {facts_hash}
    test_ids, tested_by = _tests_index(tests_facts or facts)
    cites = _cite_universe(facts, containers)
    narratives_proposed = facts.get("containers_narrative") or {}
    components_narrative = facts.get("components_narrative") or {}
    system_narrative = facts.get("system_narrative") or {}
    # LLM narratives are generated from the CURATED facts but stored in the enriched
    # file; their staleness anchor is the source hash enrich stamped, not this file's.
    narrative_anchor = prov.get("enrich_source_hash") or facts_hash

    # containers involved in a layering violation, for the health drift field.
    violating: set[str] = set()
    if layering_rules and (layering_rules.get("forbidden") or []):
        from .drift_report import check_layering
        for f in check_layering(facts, layering_rules):
            if f["status"] == "VIOLATION":
                for s, t in f["edges"]:
                    violating.update(c for c in (t2c.get(s), t2c.get(t)) if c)

    # public surface: symbols OTHERS use from this container (evidence on incoming
    # edges with visibility public) + member-provided COM identities.
    provided: dict[str, set[str]] = {}
    for r in facts.get("relationships", []) or []:
        ct = t2c.get(r.get("target"))
        if not ct:
            continue
        for e in r.get("evidence", []) or []:
            if e.get("type") in ("symbol_use", "include") and e.get("visibility") == "public":
                detail = e.get("detail")
                if detail:
                    provided.setdefault(ct, set()).add(detail)

    rows = []
    for cid in sorted(containers):
        c = containers[cid]
        members = [by_id[m] for m in sorted(c.members) if m in by_id]
        fan_in = [_fan_entry("from", s, containers[s].name if s in containers else s, e,
                             pair_layers.get((s, t), set()),
                             pair_conf.get((s, t), "low"))
                  for (s, t), e in sorted(cedges.items()) if t == cid]
        fan_in.sort(key=lambda x: (-x["weight"], x["from"]))
        fan_out = [_fan_entry("to", t, containers[t].name if t in containers else t, e,
                              pair_layers.get((s, t), set()),
                              pair_conf.get((s, t), "low"))
                   for (s, t), e in sorted(cedges.items()) if s == cid]
        fan_out.sort(key=lambda x: (-x["weight"], x["to"]))

        symbols = sorted(provided.get(cid, set()))
        for t in members:
            symbols += sorted(t.get("com_provides", []) or [])
        symbols = sorted(set(symbols))[:_SURFACE_CAP]
        if symbols:
            surface = {"available": True, "reason": "", "symbols": symbols}
        elif not l2:
            surface = {"available": False, "reason": "L2 not extracted", "symbols": []}
        else:
            surface = {"available": False,
                       "reason": "L2 ran — no public symbols observed in evidence",
                       "symbols": []}

        member_ids = sorted(c.members)
        if vitals is not None and cid in vitals:
            vit = vitals[cid]
        else:
            vit = {"available": False,
                   "reason": vitals_reason or "git vitals not computed"}
        # Component datasheets (plan §4.6) only for MULTI-member containers — a
        # single-member (model-Y) container already IS its one component, so a nested
        # sheet would just duplicate it. Matches build_containers' model-X materialization.
        components = []
        if len(members) >= 2:
            components = [_component_sheet(
                t, cid, facts=facts, by_id=by_id, t2c=t2c, containers=containers,
                comp_narratives=components_narrative, narrative_anchor=narrative_anchor,
                cites=cites, test_ids=test_ids, tested_by=tested_by,
                measurements=measurements, facts_hash=facts_hash, overrides=overrides)
                for t in members]
        rows.append({
            "id": cid,
            "name": c.name,
            "components": components,
            "narrative": _narrative_block(cid, overrides, narratives_proposed,
                                          narrative_anchor, cites),
            "purpose": {"text": c.description or container_description(c),
                        "enriched": enriched,
                        "grouped_by": _dominant_signal(members)},
            "owns": {"members": member_ids,
                     "paths": sorted({(t.get("path") or "").replace("\\", "/")
                                      for t in members if t.get("path")}),
                     "namespaces": sorted({ns for t in members
                                           for ns in (t.get("namespaces") or [])})},
            "metrics": _container_metrics(members),
            "technology": _container_technology(members),
            "fan_in": fan_in,
            "fan_out": fan_out,
            "public_surface": surface,
            "footprint": _footprint(measurements, set(member_ids), facts_hash),
            "vitals": vit,
            "risk": _risk_echo(risk_report, risk_accept, cid),
            "tests": _tests_block(member_ids, test_ids, tested_by),
            "health": {"coverage_stratum": strata_c.get(cid, "none"),
                       "mean_confidence": conf_c.get(cid),
                       "needs_curation": "needs-curation" in c.tags,
                       "external": "external" in c.tags or "person" in c.tags,
                       "drift": "violating" if cid in violating else "stable"},
        })
    system_id, system_name = system_identity(facts, overrides)
    # `system_narrative` is a single flat record; _narrative_block (shared with containers/
    # components) keys by id, so wrap it as {system_id: record} for the lookup.
    sys_narratives = {system_id: system_narrative} if system_narrative else {}
    system = _system_sheet(facts, containers, cedges, by_id, system_id=system_id,
                           system_name=system_name, sys_narratives=sys_narratives,
                           narrative_anchor=narrative_anchor, cites=cites,
                           measurements=measurements, facts_hash=facts_hash, l2=l2,
                           enriched=enriched, overrides=overrides)
    return {"schema": DATASHEETS_SCHEMA, "derived_from_hash": facts_hash,
            "l2_extracted": l2, "system": system, "containers": rows}


def _fmt_bytes(n: int) -> str:
    """Deterministic human size: B / KiB / MiB with one decimal."""
    if n < 1024:
        return f"{n} B"
    if n < 1024 * 1024:
        return f"{n / 1024:.1f} KiB"
    return f"{n / (1024 * 1024):.1f} MiB"


def _render_narrative(n: dict[str, Any]) -> list[str]:
    """The plan-§4 narrative block: loud source chip, hard absence, cited bullets."""
    if n["source"] == "none":
        return [f"> _Narrative: {n['reason']}._", ""]
    if n["source"] == "human":
        chip = "Human-written (rules/datasheet-overrides.yaml)"
    else:
        chip = f"LLM-generated ({n['model_id'] or 'unknown model'})" \
               + (" · POSSIBLY STALE — facts changed since generation"
                  if n["stale"] else "")
    lines = [f"> **Narrative — {chip}**", ">"]
    for para in (n["abstract_md"] or "").strip().splitlines():
        lines.append(f"> {para}" if para else ">")
    for kp in n["key_points"]:
        cited = (" _(cites: " + ", ".join(f"`{c}`" for c in kp["cites"]) + ")_"
                 if kp["cites"] else "")
        lines.append(f"> - {kp['text']}{cited}")
    if n.get("stale_citations"):
        lines.append("> - ⚠ unresolvable citation(s): "
                     + ", ".join(f"`{c}`" for c in n["stale_citations"]))
    lines.append("")
    return lines


def render_datasheet(row: dict[str, Any]) -> str:
    """One container's datasheet as markdown — the §1.6 / enrichment-§7 specimen shape.
    Render order keeps the cited deterministic fields adjacent to the narrative so a
    plausible-but-wrong abstract never stands alone (plan §9 threat c)."""
    p = row["purpose"]
    qualifier = "name enriched; " if p["enriched"] else ""
    grouped = f"grouped by `{p['grouped_by']}`" if p["grouped_by"] else "ungrouped"
    members = row["owns"]["members"]
    lines = [f"## {row['name']}", ""]
    lines += _render_narrative(row["narrative"])
    lines += [f"**Purpose** — {p['text']} _({qualifier}{grouped})_", "",
              f"**Owns** — {len(members)} target(s): "
              + ", ".join(f"`{m}`" for m in members) + ".", ""]

    m = row["metrics"]
    if m["available"]:
        t = m["total"]
        lines += [f"**Metrics** — {t['files']} file(s): {t['code']} code / "
                  f"{t['comment']} comment / {t['blank']} blank line(s) · "
                  f"{m['todo_count']} TODO/FIXME/HACK marker(s) _({m['engine']})_.", ""]
        if len(m["by_language"]) > 1:
            lines += ["| Language | Files | Code | Comment | Blank |",
                      "|---|---:|---:|---:|---:|"]
            lines += [f"| {r['language']} | {r['files']} | {r['code']} | "
                      f"{r['comment']} | {r['blank']} |" for r in m["by_language"]]
            lines.append("")
    else:
        lines += [f"**Metrics** — _{m['reason']}._", ""]
    tech = row["technology"]
    if tech["packages"]:
        more = (f" (+{tech['packages_total'] - len(tech['packages'])} more)"
                if tech["packages_total"] > len(tech["packages"]) else "")
        lines += ["**Technology** — packages: "
                  + ", ".join(f"`{x}`" for x in tech["packages"]) + f"{more}.", ""]
    else:
        lines += ["**Technology** — _no package references in evidence._", ""]

    def _fan(label: str, entries: list[dict[str, Any]], key: str) -> str:
        if not entries:
            return f"**{label}** — _nothing in-model_."
        bits = []
        for e in entries:
            layers = "+".join(e["evidence_layers"]) or "L0"
            bits.append(f"`{e['name']}` (weight {e['weight']}, {layers} {e['kind']}"
                        f"{', declared' if e['declared'] else ''})")
        return f"**{label}** — " + ", ".join(bits) + "."

    lines += [_fan("Depended on by", row["fan_in"], "from"),
              _fan("Depends on", row["fan_out"], "to"), ""]
    s = row["public_surface"]
    if s["available"]:
        lines.append("**Public surface** — " + ", ".join(f"`{x}`" for x in s["symbols"])
                     + ".")
    else:
        lines.append(f"**Public surface** — _{s['reason']}; no symbol-level surface "
                     "available on this run._")
    fp = row["footprint"]
    if fp["available"]:
        stale = " · ⚠ STALE — the facts changed since this measurement" \
            if fp["stale"] else ""
        lines += ["", f"**Footprint** — {_fmt_bytes(fp['size_bytes'])} across "
                  f"{fp['artifacts']} artifact(s), measured {fp['measured_at'] or '?'} "
                  f"at commit `{(fp['commit'] or 'unknown')[:12]}`{stale}."]
    else:
        lines += ["", f"**Footprint** — _{fp['reason']}._"]
    h = row["health"]
    conf = f"{h['mean_confidence']:.2f}" if h["mean_confidence"] is not None else "—"
    lines += ["",
              f"**Health** — coverage {h['coverage_stratum']} · mean confidence {conf} · "
              + ("flagged `needs-curation`" if h["needs_curation"]
                 else "not flagged `needs-curation`")
              + f" · drift: {h['drift']}."]
    v = row["vitals"]
    if v.get("available"):
        last = v["last_touched"] or "not in window"
        lines.append(f"**Vitals** — {v['churn_commits']} commit(s) in the "
                     f"{v['window_days']} days before HEAD · last touched {last} · "
                     f"{v['authors']} author(s).")
    else:
        lines.append(f"**Vitals** — _{v.get('reason', 'unavailable')}._")
    r = row["risk"]
    if r.get("available"):
        if r["finding_kinds"]:
            extras = []
            if r["instability_I"] is not None:
                extras.append(f"I={r['instability_I']}")
            if r["abstractness_A"] is not None:
                extras.append(f"A={r['abstractness_A']}")
            if r["distance_D"] is not None:
                extras.append(f"D={r['distance_D']}")
            suffix = (" (" + ", ".join(extras) + ")") if extras else ""
            lines.append("**Risk** — findings: "
                         + ", ".join(f"`{k}`" for k in r["finding_kinds"])
                         + f"{suffix} _(echoed from risk-report.json)_.")
        else:
            lines.append("**Risk** — no findings for this container "
                         "_(echoed from risk-report.json)_.")
    else:
        lines.append(f"**Risk** — _{r.get('reason', 'unavailable')}._")
    te = row["tests"]
    if te["test_targets_total"]:
        lines.append(f"**Tests** — {te['test_targets_total']} test target(s) reference "
                     f"this container; {te['members_with_tests']}/{te['members']} "
                     f"member(s) referenced by a test _(adjacency proxy, not coverage)_.")
    else:
        lines.append("**Tests** — _no in-model test target references this container "
                     "(adjacency proxy, not coverage)._")
    lines.append("")
    return "\n".join(lines)


# ------------------------------------------------------------------- guided tour (§1.1)

def _salience(e: dict[str, Any], target_external: bool) -> tuple[int, list[str]]:
    """Salience = weight + seam boost (+10 interop/contract) + boundary boost (+5).
    Pure weight would walk a reader straight past a low-traffic-but-critical seam.
    Delegates to the shared :func:`salience.edge_salience` (dynamic-view plan §1a#3) so the
    guided tour and the candidate inbox compute salience identically."""
    return _salience_mod.edge_salience(e, target_external)


def build_tour(facts: dict[str, Any]) -> dict[str, Any]:
    """The deterministic entry-point → data-flow → dependents walk + the exhaustive
    critical-seams list (engine §1.1). Selection/order is a pure function of
    ``(salience, id)``; the seams list exists exactly because the walk heuristic can
    miss a critical low-weight edge (§1.7)."""
    containers, _t2c, cedges, _desc = _lift(facts)
    external = {cid for cid, c in containers.items()
                if {"external", "person"} & c.tags}
    internal = sorted(set(containers) - external)

    in_from_internal: dict[str, int] = {}
    in_from_external: dict[str, int] = {}
    out_weight: dict[str, int] = {}
    for (s, t), e in cedges.items():
        out_weight[s] = out_weight.get(s, 0) + e["weight"]
        if s in external:
            in_from_external[t] = in_from_external.get(t, 0) + e["weight"]
        else:
            in_from_internal[t] = in_from_internal.get(t, 0) + e["weight"]

    # entry points: the SHARED detector (dynamic-view plan §1a#3/§6) so the guided tour and
    # Source C's graph-walk agree on roots, then ranked by external fan-in / out-weight (the
    # place requests/data come IN). The detector folds in sdk-role / controller / executable
    # signals on top of the zero-in-degree heuristic the tour used historically.
    detected, _entry_reasons = _salience_mod.detect_entries(facts)
    entries = list(detected)
    entries.sort(key=lambda c: (-in_from_external.get(c, 0), -out_weight.get(c, 0), c))
    if not entries and internal:
        entries = sorted(internal,
                         key=lambda c: (-in_from_external.get(c, 0), c))[:1]

    walk: list[dict[str, Any]] = []
    visited: set[str] = set()
    cur = entries[0] if entries else None
    if cur:
        visited.add(cur)
    while cur is not None and len(walk) < _TOUR_MAX_HOPS:
        best: tuple[int, str] | None = None
        best_hop: dict[str, Any] | None = None
        for (s, t), e in sorted(cedges.items()):
            if s != cur or t in visited:
                continue
            sal, reasons = _salience(e, t in external)
            if best is None or (-sal, t) < (-best[0], best[1]):
                best = (sal, t)
                best_hop = {"from": s, "from_name": containers[s].name,
                            "to": t, "to_name": containers[t].name,
                            "weight": e["weight"], "kind": e.get("kind") or "uses",
                            "salience": sal, "salience_reasons": reasons}
        if best_hop is None:
            break
        walk.append(best_hop)
        cur = best_hop["to"]
        visited.add(cur)
        if cur in external:
            break  # the walk surfaced a boundary — a natural terminal

    last = walk[-1]["to"] if walk else (entries[0] if entries else None)
    dependents = sorted(s for (s, t) in cedges if t == last) if last else []

    seams = []
    for (s, t), e in sorted(cedges.items()):
        reasons = []
        if {"interop", "contract"} & e.get("tags", set()):
            reasons.append("interop/contract")
        if s in external or t in external:
            reasons.append("boundary-crossing")
        if reasons:
            seams.append({"source": s, "target": t, "weight": e["weight"],
                          "kind": e.get("kind") or "uses", "reasons": reasons})

    return {"schema": TOUR_SCHEMA, "derived_from_hash": content_hash(facts),
            "note": ("structural walk by salience (weight + seam/boundary boost); the "
                     "critical-seams list is exhaustive regardless of weight, because "
                     "the traversal heuristic alone could bury a critical edge (§1.7)"),
            "entry_points": entries, "walk": walk,
            "final_dependents": dependents, "critical_seams": seams}


def render_tour(tour: dict[str, Any]) -> str:
    lines = ["# Guided tour  (`arch datasheet --tour`)", "",
             f"> {tour['note']}", ""]
    if not tour["walk"]:
        lines += ["_No walkable edges — the model has no inter-container flow to tour._",
                  ""]
    else:
        lines.append(f"**Entry point(s):** {', '.join(tour['entry_points'])}")
        lines.append("")
        for i, hop in enumerate(tour["walk"], 1):
            why = f" — {', '.join(hop['salience_reasons'])}" \
                if hop["salience_reasons"] else ""
            lines.append(f"{i}. `{hop['from_name']}` → `{hop['to_name']}` "
                         f"(weight {hop['weight']}, {hop['kind']}, "
                         f"salience {hop['salience']}{why})")
        if tour["final_dependents"]:
            lines += ["", "**Depended on by:** "
                      + ", ".join(f"`{d}`" for d in tour["final_dependents"])]
    lines += ["", "## Critical seams (exhaustive — never buried by the walk)", ""]
    if not tour["critical_seams"]:
        lines.append("_None: no interop/contract/boundary-crossing edges in the model._")
    for s in tour["critical_seams"]:
        lines.append(f"- `{s['source']}` → `{s['target']}` (weight {s['weight']}, "
                     f"{s['kind']}): {', '.join(s['reasons'])}")
    return "\n".join(lines).rstrip() + "\n"


def run_datasheets(ws: Workspace, *,
                   facts: dict[str, Any] | None = None) -> dict[str, Any] | None:
    """The ``arch datasheet`` entry point: write ``generated/docs/datasheets.json``,
    one ``datasheets/<slug>.md`` per container, and the tour twins. Advisory,
    machine-owned, overwritten every run — never the hashed core (§9).

    Gathers the datasheets/2 side inputs (enrichment plan §7) and hands them to the
    pure :func:`build_datasheets`: the §3 risk report (echoed, staleness-guarded), the
    §6.4 git vitals (conditional on history — absence is the normal answer), the Class-V
    measurements sidecar (`arch measure`), and the hand-owned narrative overrides.

    *facts* pins the facts tier explicitly — the GUI's fast re-curate loop passes the
    freshly-written CURATED facts so newly-grouped containers get a datasheet, rather
    than the enrich-preferring default below shadowing them with a structurally stale
    enriched snapshot (the same reason ``layout.run_all_views`` takes a ``facts=``)."""
    if facts is None:
        for path in (ws.enriched_facts, ws.curated_facts, ws.extracted_facts):
            if path.exists():
                facts = load_json(path)
                break
        else:
            return None
    risk_report = load_json(ws.risk_report_json) if ws.risk_report_json.exists() else None
    measurements = load_json(ws.measurements_json) if ws.measurements_json.exists() else None
    overrides = load_yaml(ws.datasheet_overrides)
    containers, _t2c, _cedges, _desc = _lift(facts)
    vitals, vitals_reason = git_vitals(ws.repo, facts, containers)
    tests_facts = load_json(ws.extracted_facts) if ws.extracted_facts.exists() else None
    # Every facts tier currently on disk is an acceptable provenance for the risk echo:
    # `arch risk` reads the curated tier, the datasheets read the enriched one — within
    # one run those are the same model under different provenance stamps.
    accept_hashes = {content_hash(load_json(p))
                     for p in (ws.enriched_facts, ws.curated_facts, ws.extracted_facts)
                     if p.exists()}
    sheets = build_datasheets(facts, layering_rules=load_yaml(ws.layering_rules),
                              risk_report=risk_report, vitals=vitals,
                              vitals_reason=vitals_reason,
                              measurements=measurements, overrides=overrides,
                              tests_facts=tests_facts, accept_hashes=accept_hashes)
    tour = build_tour(facts)

    dump_json(sheets, ws.datasheets_json)
    ds_dir = ws.datasheets_tour_json.parent
    ds_dir.mkdir(parents=True, exist_ok=True)
    for old in ds_dir.glob("*.md"):  # machine-owned dir: drop sheets of gone containers
        old.unlink()
    slugs = SlugRegistry()
    for row in sheets["containers"]:
        (ds_dir / f"{slugs.assign(row['id'])}.md").write_text(
            render_datasheet(row), encoding="utf-8", newline="")
    dump_json(tour, ws.datasheets_tour_json)
    (ds_dir / "tour.md").write_text(render_tour(tour), encoding="utf-8", newline="")
    return {"containers": len(sheets["containers"]),
            "datasheets_json": str(ws.datasheets_json),
            "tour_hops": len(tour["walk"]),
            "critical_seams": len(tour["critical_seams"])}


def _main(argv: list[str] | None = None) -> int:  # pragma: no cover
    ap = argparse.ArgumentParser(prog="anon.stages.generate_docs",
                                 description=__doc__)
    ap.add_argument("--repo", required=True)
    ap.add_argument("--arch-dir")
    ap.add_argument("--rules-dir")
    ap.add_argument("--datasheet", action="store_true",
                    help="emit the §1 datasheets + tour (the arch datasheet path)")
    args = ap.parse_args(argv)
    ws = resolve_workspace(args.repo, args.arch_dir, args.rules_dir)
    if args.datasheet:
        result = run_datasheets(ws)
        if result is None:
            print("[datasheet] no fact model — run `arch run` first.")
            return 2
        print(f"[datasheet] {result['containers']} datasheet(s) -> "
              f"{result['datasheets_json']} (+ tour, {result['tour_hops']} hops)")
        return 0
    print("nothing to do (pass --datasheet)")
    return 2


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(_main())
