"""Stage 6 — deterministic Structurizr DSL generation (plan §9, nodes 5–6).

Aggregates curated/enriched build targets into C4 **containers** (by ``container_id``,
§7.4), lifts target->target edges to container->container edges (dropping intra-container
edges, merging parallel ones), and emits two **machine-owned** fragments that are
overwritten every run (§9):

  - ``generated/generated-components.dsl``    (container + nested component defs, tags §9.2)
  - ``generated/generated-relationships.dsl`` (container edges, with tags §9.2)

It also **scaffolds once** the hand-owned ``workspace.dsl`` and ``views.dsl`` (and never
touches them again — the three-tier lifecycle, §9.1). DSL identifiers derive from stable
ids via :class:`SlugRegistry` so ``same id -> same identifier`` and Structurizr's
layout-merge can re-attach saved positions (§9.1).

Additions over the foundation (task #4):
  - **element + relationship tagging (§9.2)** so filtered views can slice by tag.
  - the **deterministic cross-element naming reconciler (§8.3)** over each sibling set.
  - **element-budget DETECTION (advisory; §9.1/§1.1#1)**: Container view <=25, Component
    view <=20; over-budget views are detected and reported via ``over_budget_views`` (the
    run-report / CLI surface them as a warning). Enforcement (fail / auto-split) is opt-in
    at the CLI layer, not done here.

Container drill-down (plan ``2026-06-10-container-component-drilldown.md``, "D§N"):
  - **two model shapes, auto-selected** (D§2): shape **X** (container = curated theme,
    component = member build target) when the curated target count ``N`` exceeds
    ``MODEL_Y_MAX``; shape **Y** (container = build target, theme = cosmetic ``group{}``,
    component = namespace tier) when it fits. ``model_shape: x|y`` in mapping-rules pins.
  - **the component tier = build targets** (D§3, Model X): every multi-target container
    materializes one component per member target — the build graph one zoom below the
    curation grouping; the namespace tier moves to the opt-in deep path.
  - **component-altitude edges** (D§4): intra-container target->target edges (formerly
    discarded) emit as component->component; cross-container edges emit as the two
    component->container HALF-edges that Structurizr component views can actually render
    (the D§12.1 spike: ``include *`` never pulls a foreign component into a view, and the
    default implied-relationship strategy mints noisy duplicates — so both altitudes are
    explicit and the relationships fragment pins ``!impliedRelationships false``).
  - **namespace-tier interior edges** (D§4, gap-fill): the ``…/component:<ns>`` namespace->
    namespace ``symbol_use`` edges the Roslyn helper emits give a Model-Y module-container
    (and a D§5 ``expand`` promotion) its INTERIOR — without them the namespace tier rendered
    edgeless, since the target->target projection above carried only the inter-target
    altitude. Scoped to materialized components (excluded/aggregated namespaces drop their
    edges, never dangle); always intra-container, so no half-edge case arises.
  - **auto-drawn Component views** (D§7) for every container with >=1 materialized
    component; budgets stay advisory.
  - **the opt-in deep path** (D§5): an ``expand``-flagged target is promoted out of its
    theme container to a container of its own (namespaces — or classes with
    ``expand_classes`` / a ``code_view`` namespace filter — nested), the theme wrapping
    both as a cosmetic ``group{}``.
"""
from __future__ import annotations

import logging
import re
from collections import Counter
from dataclasses import dataclass, field
from typing import Any

from .. import view_intents
from ..config import load_mapping_rules
from ..ids import SlugRegistry
from ..jsonio import load_json
from ..paths import Workspace
from . import generate_deployment, generate_docs, scenario_candidates, scenarios

CONTAINER_BUDGET = 25   # plan §1.1 metric 1 / §16#10a
COMPONENT_BUDGET = 20
# D§2.3: auto-select Model Y iff the curated target count fits the top-view budget
# (Y's module-containers BECOME the top Container view). Generator constant, not user
# config — pin the shape via `model_shape: x|y` in mapping-rules.yaml instead.
MODEL_Y_MAX = CONTAINER_BUDGET

_BANNER = ("// GENERATED BY ANON — DO NOT EDIT. Overwritten every run (plan §9).\n"
           "// Edit curation in rules/mapping-rules.yaml; views/styles live in views.dsl.\n")

# convention classifier for the naming reconciler (§8.3 step 3).
_SNAKE = re.compile(r"^[a-z0-9]+(_[a-z0-9]+)+$")
_SPACED_TITLE = re.compile(r"^[A-Z][A-Za-z0-9]*( [A-Za-z0-9]+)+$")


def _dsl_str(s: str) -> str:
    return '"' + (s or "").replace("\\", "\\\\").replace('"', '\\"') + '"'


@dataclass
class Component:
    cid: str          # stable child id
    name: str
    description: str = ""
    tags: set[str] = field(default_factory=set)


@dataclass
class Container:
    cid: str
    name: str
    description: str = ""
    technology: str = ""
    tags: set[str] = field(default_factory=set)
    members: list[str] = field(default_factory=list)
    member_names: list[str] = field(default_factory=list)
    component_view: bool = False    # legacy §7.4 flag — reinterpreted by curate (D§6.2)
    code_view: str | None = None    # namespace-substring filter for a class/code drill-down (§9.1)
    expand_classes: bool = False    # promoted target shows its code[] tier, not namespaces (D§5)
    group: str | None = None        # cosmetic theme `group{}` label (D§2.2/D§5); not identity
    components: list[Component] = field(default_factory=list)


# --- C4 description/technology synthesis (model-completeness; §9.2) -------------
# Every emitted element/relationship gets a non-empty description + technology so the
# Structurizr `model.*.description` / `model.relationship.technology` inspections pass even
# in the deterministic --no-llm baseline. Hand-authored `descriptions:` (§7.4) override the
# fallbacks; the LLM enrichment path overrides them further. All synthesis is deterministic.

# Relationship technology by evidence kind, strongest structural signal first (§5/§6.2).
_EDGE_TECH = (
    ("project_ref", ".NET project reference"),
    ("package_ref", "NuGet package reference"),
    ("link", "Native link (static/shared library)"),
    ("interop", "Native interop (P/Invoke / COM / C++-CLI)"),
    ("contract", "Shared contract (IDL / .proto)"),
    ("include", "C/C++ include dependency"),
    ("symbol_use", "Symbol reference"),
    ("runtime", "Runtime call"),
)


def _edge_technology(e: dict[str, Any]) -> str:
    """A deterministic, human technology label for a container edge from its evidence tags."""
    tags = e.get("tags", set())
    for key, tech in _EDGE_TECH:
        if key in tags or any(t.startswith(key + ":") for t in tags):
            return tech
    return "Dependency"


def _container_description(c: "Container") -> str:
    """Hand-authored description if present, else a deterministic build-graph summary so the
    container is never description-less (Structurizr ``model.container.description``)."""
    if c.description:
        return c.description
    names = sorted(c.member_names or c.members)
    tech = c.technology or "Build target group"
    if not names:
        return tech
    shown = ", ".join(names[:3]) + (f" (+{len(names) - 3} more)" if len(names) > 3 else "")
    if len(names) == 1:
        return f"{tech}: {shown}."
    return f"{tech} grouping {len(names)} build targets: {shown}."


def _container_technology(c: "Container") -> str:
    """The curated technology, else a deterministic fallback from the element's tags so a
    container never trips the Structurizr ``model.container.technology`` inspection (§9.2)."""
    if c.technology:
        return c.technology
    if "contract" in c.tags:
        return "Interface contract"
    if "person" in c.tags:
        return "Person / actor"
    if "external" in c.tags:
        return "External system"
    if "csharp" in c.tags or "clr" in c.tags:
        return ".NET"
    if "cpp" in c.tags:
        return "C/C++"
    return "Software container"


def _component_description(comp: "Component") -> str:
    """Deterministic description for a component/code element from its tier tags (§6.3)."""
    if comp.description:
        return comp.description
    if "target" in comp.tags:
        return f"Build target `{comp.name}`."
    if "code" in comp.tags:
        return f"Class or type `{comp.name}`."
    if "source:namespace" in comp.tags:
        return f"Namespace `{comp.name}`."
    if "source:subdir" in comp.tags:
        return f"Source directory `{comp.name}`."
    return f"Component `{comp.name}`."


# --- element tag derivation (§9.2) ---------------------------------------------

def _element_tags(target: dict[str, Any]) -> set[str]:
    """Every element tag: language, technology, layer, needs-curation, external (§9.2)."""
    tags: set[str] = set()
    lang = target.get("language")
    if lang:
        tags.add(lang)
    tech = target.get("technology")
    if tech:
        tags.add(tech)
    for t in target.get("tags", []):
        # carry the curation/extraction tags filtered views key off (§9.2).
        if (t in ("needs-curation", "external", "person", "contract", "com", "clr")
                or t.startswith(("partial:", "layer:", "adr:", "interop:", "iac:", "runtime:"))):
            tags.add(t)
    if target.get("external"):
        tags.add("external")
    return tags


def _is_boundary_member(t: dict[str, Any]) -> bool:
    """A member target that belongs to the system BOUNDARY rather than the system under
    study: an external dependency (a transitive NuGet/package target) or a person. A
    container is only a boundary container — tagged ``external``/``person`` — when EVERY
    member is a boundary element; one bundled external package must not make a first-party
    container a boundary (and thus un-narratable). See :func:`build_containers`."""
    return bool(t.get("external")
                or {"external", "person"} & set(t.get("tags", []) or []))


def decide_model_shape(facts: dict[str, Any], rules: Any = None) -> tuple[str, int]:
    """The D§2.3 auto-select: ``(shape, N)`` where ``N`` = curated module-target count.

    Shape **Y** iff ``N <= MODEL_Y_MAX`` (Y's module-containers become the top Container
    view, so they must fit its budget), else **X**. ``model_shape: x|y`` in
    ``mapping-rules.yaml`` pins the shape (the D§2.3 anti-flapping valve); ``auto`` is the
    default. Boundary-promoted externals/persons are their own containers under either
    shape, so they don't count toward ``N``. Pure function of the curated facts + rules.
    """
    n = sum(1 for t in facts.get("targets", [])
            if not t.get("external") and not t.get("boundary_kind"))
    pin = getattr(rules, "model_shape", "auto") if rules is not None else "auto"
    if pin in ("x", "y"):
        return pin, n
    return ("y" if n <= MODEL_Y_MAX else "x"), n


def _nest_tier(c: Container, t: dict[str, Any]) -> None:
    """Nest one target's §6.3 child tier into container *c* (Model Y / promoted targets).

    A plain container shows the NAMESPACE component tier; a ``code_view`` container shows
    the CLASSES of the matching namespace(s) (the C4 code altitude) instead; an
    ``expand_classes`` promotion (D§5) shows every namespace's classes.
    """
    for comp in t.get("components", []) or []:
        if c.code_view:
            if c.code_view in comp.get("key", "") or c.code_view in comp.get("name", ""):
                for code in comp.get("code", []) or []:
                    c.components.append(Component(cid=code["id"],
                                                  name=code.get("name", code["id"]),
                                                  tags={"Component", "code"}))
            # a non-matching namespace contributes nothing to a code view (scoped, §9.1).
        elif c.expand_classes:
            for code in comp.get("code", []) or []:
                c.components.append(Component(cid=code["id"],
                                              name=code.get("name", code["id"]),
                                              tags={"Component", "code"}))
        else:
            ctags = {"Component"}
            if comp.get("source"):
                ctags.add(f"source:{comp['source']}")
            c.components.append(Component(cid=comp["id"], name=comp.get("name", comp["id"]),
                                          tags=ctags))


def _target_component(t: dict[str, Any]) -> Component:
    """One member build target as a C4 component (D§3.1, Model X).

    ``cid`` = the target id — the slug-stability key: the same target referenced as an
    edge endpoint or later promoted to a container resolves to the SAME identifier
    (D§9, the layout-merge precondition). The description is target-derived and
    deterministic (D§8): names are raw target names, no LLM.
    """
    name = t.get("name", t["id"])
    tech = t.get("technology") or t.get("type") or t.get("language") or ""
    desc = f"Build target {name} ({tech})." if tech else f"Build target {name}."
    return Component(cid=t["id"], name=name, description=desc,
                     tags={"Component", "target"} | _element_tags(t))


def _group_label(theme: str | None, parent: str | None) -> str | None:
    """The rendered ``group{}`` label for a theme that may sit under a cosmetic parent.

    v1 flattens the two tiers into one label (``"Middleware / PubSub"``) because
    ``Container.group`` is single-valued and nested ``group{}`` needs the
    ``structurizr.groupSeparator`` model property — the deferred spike
    (container-groups plan §4.2/§4.3). No parent → the theme label unchanged."""
    if theme and parent:
        return f"{parent} / {theme}"
    return theme or None


def build_containers(facts: dict[str, Any], shape: str = "x",
                     promote_expanded: bool = False) -> dict[str, Container]:
    """Aggregate curated targets into the C4 container/component hierarchy for *shape*.

    Model **X** (default): container = curated theme; each MULTI-target container
    materializes its member targets as components (D§3.1); single-target containers have
    nothing to drill. With *promote_expanded*, an ``expand``-flagged target (D§5) is
    promoted out of its theme to a container of its own (namespace/class tier nested),
    the theme wrapping both via a cosmetic ``group{}``.

    Model **Y**: every module target IS a container (cid = target id), its curated theme
    becomes its ``group`` label, and its namespace tier nests natively (D§2.2/D§3.2).
    Boundary-promoted externals/persons are their own containers under either shape.

    *shape*/*promote_expanded* are only passed by the generator's :func:`run` — the
    facts-level consumers (``query``/``serve``/confidence/datasheets) call
    ``build_containers(facts)`` and keep the pure curated ``container_id`` grouping:
    the model shape and the D§5 promotion are DSL-RENDERING choices, not facts
    (D§0.1#7 — the GUI inherits the emitted artifacts later; its API stays at the
    curated altitude until GUI Stage 3 takes this up).
    """
    containers: dict[str, Container] = {}
    member_targets: dict[str, list[dict[str, Any]]] = {}
    # every container's member target dicts (both the standalone and grouped paths) — so the
    # post-loop boundary pass can ask "are ALL members external?" before keeping the tag.
    members_by_cid: dict[str, list[dict[str, Any]]] = {}
    # X themes that lost a member to an expand promotion still wrap their remaining
    # members in the theme group, so the promoted sibling stays visually attached (D§5).
    # Value is ``(theme_name, container_parent)`` — with a parent tier present the two
    # flatten into one "Parent / Theme" group label (container-groups plan §4.2, v1:
    # single-level groups only; true nesting is the deferred groupSeparator spike).
    expanded_themes: dict[str, tuple[str, str | None]] = {}
    for t in facts.get("targets", []):
        tid = t["id"]
        grouped = t.get("container_id", tid) != tid
        # A module target stands alone as a container when the shape says so (Y) or the
        # curation asked for the deep path (expand, D§5). Boundary promotions keep their
        # existing single-target-container handling under either shape.
        standalone = ((shape == "y" or (promote_expanded and t.get("expand")))
                      and not t.get("boundary_kind"))
        if standalone:
            c = containers.get(tid)
            if c is None:
                c = Container(cid=tid, name=t.get("name", tid))
                containers[tid] = c
            c.members.append(tid)
            c.member_names.append(t.get("name", tid))
            members_by_cid.setdefault(tid, []).append(t)
            if t.get("technology"):
                c.technology = t["technology"]
            c.tags |= _element_tags(t)
            if grouped:
                # Model Y theme / D§5 promoted sibling: the group label is the theme,
                # prefixed by the cosmetic parent when one exists (flattened, plan §4.2).
                c.group = _group_label(t.get("container_name"),
                                       t.get("container_parent"))
                if t.get("expand"):
                    expanded_themes[t.get("container_id", tid)] = (
                        t.get("container_name", ""), t.get("container_parent"))
            if t.get("expand_classes"):
                c.expand_classes = True
            if t.get("code_view"):
                c.code_view = t["code_view"]
            _nest_tier(c, t)
            continue
        cid = t.get("container_id", tid)
        cname = t.get("container_name", t.get("name", cid))
        c = containers.get(cid)
        if c is None:
            c = Container(cid=cid, name=cname)
            containers[cid] = c
        c.members.append(tid)
        c.member_names.append(t.get("name", tid))
        if t.get("technology"):
            c.technology = t["technology"]
        # hand-authored container description (curate stamps it on every member, §7.4).
        if t.get("container_description") and not c.description:
            c.description = t["container_description"]
        c.tags |= _element_tags(t)
        if t.get("component_view"):
            c.component_view = True
        # Model X: a curated container whose members carry a cosmetic parent renders
        # inside that parent's `group{}` boundary (container-groups plan §4.1). Every
        # member carries the same label (stamped per-rule by curate), so first-set wins.
        if t.get("container_parent") and not c.group:
            c.group = t["container_parent"]
        member_targets.setdefault(cid, []).append(t)
        members_by_cid.setdefault(cid, []).append(t)
    # A container is a BOUNDARY (external/person) container only when EVERY member is a
    # boundary element. A first-party container that merely bundles a transitive external
    # package (e.g. an Aspire AppHost referencing Aspire.Hosting.AppHost) stays first-party
    # — and thus narratable; one external member must not tag the whole container external.
    for cid, c in containers.items():
        members = members_by_cid.get(cid)
        if members and not all(_is_boundary_member(m) for m in members):
            c.tags.discard("external")
            c.tags.discard("person")
    if shape != "y":
        # D§3.1: a multi-target container's members become its target-components — the
        # build graph one zoom below the curation grouping. The namespace tier is NOT
        # rendered here (it moved to the D§5 deep path); a single-target container
        # materializes nothing (nothing to drill, D§3.1 singleton resolution).
        for cid, ts in member_targets.items():
            c = containers[cid]
            if len(c.members) >= 2:
                for t in ts:
                    c.components.append(_target_component(t))
        for theme_cid, (theme_name, theme_parent) in expanded_themes.items():
            if theme_cid in containers and theme_name:
                containers[theme_cid].group = _group_label(theme_name, theme_parent)
    # deterministic component order within each container; pin each component's description
    # from its CLEAN (pre-reconciler) tier name so disambiguation (§8.3) can't leak the
    # "(owner)" qualifier into the description text.
    for c in containers.values():
        c.components.sort(key=lambda x: x.cid)
        for comp in c.components:
            comp.description = _component_description(comp)
    return containers


# --- relationship tags (§9.2) --------------------------------------------------

def _edge_tags(r: dict[str, Any]) -> set[str]:
    """Relationship tags: kind, evidence kinds, is_declared, confidence, drift (§9.2)."""
    tags: set[str] = set()
    if r.get("kind"):
        tags.add(f"kind:{r['kind']}")
    for ev in r.get("evidence", []):
        et = ev.get("type")
        if et:
            tags.add(et)  # link / include / symbol_use / project_ref / package_ref
    if r.get("is_declared_dependency"):
        tags.add("declared")
    conf = r.get("confidence")
    if conf:
        tags.add(f"confidence:{conf}")
    for t in r.get("tags", []):
        # drift / curation edge tags: new-dependency, suspicious-declared, private-link, ...
        tags.add(t)
    return tags


def build_container_edges(facts: dict[str, Any], target_to_container: dict[str, str]) -> dict:
    """Aggregate target edges into container edges (skip intra-container, merge parallel)."""
    edges: dict[tuple[str, str], dict[str, Any]] = {}
    for r in facts.get("relationships", []):
        cs = target_to_container.get(r["source"])
        ct = target_to_container.get(r["target"])
        if cs is None or ct is None or cs == ct:
            continue
        key = (cs, ct)
        e = edges.setdefault(key, {"kind": r.get("kind"), "weight": 0, "tags": set(),
                                   "declared": False})
        e["weight"] += r.get("weight", 0)
        e["declared"] = e["declared"] or r.get("is_declared_dependency", False)
        # a curated kind on any contributing edge wins as the merged label (deterministic:
        # first by sorted relationship order, see below).
        if r.get("kind") and not e["kind"]:
            e["kind"] = r["kind"]
        e["tags"] |= _edge_tags(r)
    return edges


def build_component_edges(facts: dict[str, Any], target_to_container: dict[str, str],
                          materialized: set[str]) -> dict:
    """Project target->target edges to the COMPONENT altitude (drill-down plan D§4.1).

    *materialized* is the set of target ids emitted as components (Model X: members of
    multi-target containers; empty under Model Y, where targets are containers and
    :func:`build_container_edges` already carries every edge). Per curated relationship:

      - **intra-container**, both endpoints materialized -> a component->component edge
        (the edges ``build_container_edges`` discards at its ``cs == ct`` skip — un-hidden
        here at the altitude where they are true).
      - **cross-container** -> the component->container HALF-edge for each materialized
        endpoint (``s -> parent(t)`` / ``parent(s) -> t``). Deviation from D§4.1's
        component->component, justified by the D§12.1 spike: a Structurizr component view's
        ``include *`` never pulls a FOREIGN component in, so a cross-boundary
        component->component edge renders nowhere; the half-edges render in each side's
        Component view, and the container view still shows only the explicit container
        edge (a component endpoint excludes an edge from that view).
      - neither endpoint materialized -> covered by the container edge; nothing emitted.

    No new structure is invented: every edge here is a re-projection of a curated
    relationship that already passed curate's significance rules (declared edges always
    kept; weak non-declared edges already dropped), so component and container altitudes
    can never disagree (D§4.1/Q10). Merge + ordering mirror ``build_container_edges``.
    """
    edges: dict[tuple[str, str], dict[str, Any]] = {}
    for r in facts.get("relationships", []):
        s, t = r["source"], r["target"]
        cs = target_to_container.get(s)
        ct = target_to_container.get(t)
        if cs is None or ct is None:
            continue
        pairs: list[tuple[str, str]] = []
        if cs == ct:
            if s != t and s in materialized and t in materialized:
                pairs.append((s, t))
        else:
            if s in materialized:
                pairs.append((s, ct))
            if t in materialized:
                pairs.append((cs, t))
        for key in pairs:
            e = edges.setdefault(key, {"kind": r.get("kind"), "weight": 0, "tags": set(),
                                       "declared": False})
            e["weight"] += r.get("weight", 0)
            e["declared"] = e["declared"] or r.get("is_declared_dependency", False)
            if r.get("kind") and not e["kind"]:
                e["kind"] = r["kind"]
            e["tags"] |= _edge_tags(r)
    return edges


def build_namespace_edges(facts: dict[str, Any], emitted_components: set[str]) -> dict:
    """Project the §6.3 component-altitude relationships to component->component edges.

    These are the ``…/component:<ns>`` relationships — the Roslyn helper's intra-project
    namespace->namespace ``symbol_use`` edges (``RoslynWorker.cs``; kept verbatim by curate,
    ``apply_mapping_rules`` D§6.3) that live one zoom BELOW the curation grid. They are the
    INTERIOR of a Model-Y module-container (and of a D§5 ``expand`` promotion): without them
    the namespace tier renders edgeless, because :func:`build_component_edges` only projects
    target->target edges (D§4 carried only the inter-target altitude — this closes that gap).

    *emitted_components* is the set of component cids actually materialized in the model
    (``{comp.cid for c in containers for comp in c.components}``). An edge is kept iff BOTH
    endpoints are emitted components: a namespace excluded or aggregated by curate
    (``_curate_components``) leaves no element to attach to, so its edges are honestly
    dropped rather than dangling — the same "validate endpoints against real components"
    guard the Roslyn helper applies on emission. The helper only emits INTRA-project ns
    edges, so both endpoints always share one owning target = one container; there is no
    cross-boundary case (and thus no D§4.1 half-edge complication) at this altitude.

    Merge + ordering mirror :func:`build_component_edges`; the disjoint key space
    (``/component:`` ids vs target/container ids) lets the caller merge the two dicts.
    """
    edges: dict[tuple[str, str], dict[str, Any]] = {}
    for r in facts.get("relationships", []):
        s, t = r["source"], r["target"]
        if "/component:" not in s or "/component:" not in t:
            continue
        if s == t or s not in emitted_components or t not in emitted_components:
            continue
        key = (s, t)
        e = edges.setdefault(key, {"kind": r.get("kind"), "weight": 0, "tags": set(),
                                   "declared": False})
        e["weight"] += r.get("weight", 0)
        e["declared"] = e["declared"] or r.get("is_declared_dependency", False)
        if r.get("kind") and not e["kind"]:
            e["kind"] = r["kind"]
        e["tags"] |= _edge_tags(r)
    return edges


# --- deterministic cross-element naming reconciler (§8.3) -----------------------

def _stable_qualifier(element_id: str) -> str:
    """A short, stable, human-ish qualifier derived from the stable id (§8.3 step 2).

    Uses the namespace + key segments of the id so the disambiguation is reproducible
    and edit-order-independent. e.g. ``csharp:csproj:src/Web/Toy.Web.csproj`` -> ``Web``.
    """
    # component/code child ids carry their OWNING element before "/component:" or "/code:";
    # qualify duplicate namespaces/classes by that owner so two modules' identically-named
    # namespaces read "cv (opencv_core)" / "cv (opencv_imgproc)" rather than colliding (§9.1).
    for sep in ("/component:", "/code:"):
        if sep in element_id:
            owner = element_id.split(sep, 1)[0]
            oseg = [s for s in owner.split(":") if s]
            okey = (oseg[-1] if oseg else owner).replace("\\", "/")
            oparts = [p for p in okey.split("/") if p]
            return oparts[-1] if oparts else owner
    segs = [s for s in element_id.split(":") if s]
    key = segs[-1] if segs else element_id
    key = key.replace("\\", "/")
    # prefer the parent folder of a path-like key (more informative than the basename).
    parts = [p for p in key.split("/") if p]
    if len(parts) >= 2:
        return parts[-2]
    return parts[-1] if parts else element_id


def _convention(name: str) -> str:
    if _SNAKE.match(name):
        return "snake"
    if _SPACED_TITLE.match(name):
        return "spaced"
    if " " not in name and name[:1].islower():
        return "camel"
    return "other"


def _mixed_convention_outliers(named: list[tuple[str, str]]) -> set[str]:
    """The ids the §8.3 reconciler flags ``needs-curation``: the *minority*-convention
    names among *named*, never the whole set. Empty when the names share a single
    convention (or are all ``other``). A single odd sibling must not taint its well-named
    peers, so only names outside the sole majority convention are flagged; on a tie for the
    majority (no clear house style) every conventioned name is an outlier. ``other``
    (unclassifiable) names are never flagged and never count toward the majority.
    Deterministic: depends only on the names, not their order."""
    conv = {eid: _convention(n) for eid, n in named}
    counts = Counter(c for c in conv.values() if c != "other")
    if len(counts) <= 1:
        return set()
    top = max(counts.values())
    leaders = [c for c, k in counts.items() if k == top]
    majority = leaders[0] if len(leaders) == 1 else None   # tie -> no house style
    return {eid for eid, c in conv.items() if c != "other" and c != majority}


def reconcile_names(siblings: list[tuple[str, str]],
                    name_overrides: dict[str, str]) -> tuple[dict[str, str], bool]:
    """Deterministic sibling-set naming reconciler (§8.3).

    *siblings* is a list of ``(element_id, current_name)``. Returns
    ``(id -> reconciled_name, mixed_conventions)``:
      1. ``name_overrides`` hard-win over any (LLM-)supplied name.
      2. disambiguate duplicate display names by appending a stable id-derived qualifier.
      3. report whether the surviving names mix conventions (caller tags `needs-curation`).
    Deterministic / golden-test-safe: results depend only on ids + names, not order.
    """
    resolved: dict[str, str] = {}
    for eid, name in siblings:
        resolved[eid] = name_overrides.get(eid, name)

    # (2) disambiguate duplicates deterministically.
    by_name: dict[str, list[str]] = {}
    for eid in sorted(resolved):              # sorted -> order-independent
        by_name.setdefault(resolved[eid], []).append(eid)
    for name, ids in by_name.items():
        if len(ids) <= 1:
            continue
        for eid in ids:
            # a pinned name is authoritative even if it now collides — do not mangle it.
            if eid in name_overrides:
                continue
            resolved[eid] = f"{name} ({_stable_qualifier(eid)})"

    # (3) mixed-convention detection over the surviving names. `mixed` stays a bool for the
    # public API (and unit tests); _apply_reconciler calls _mixed_convention_outliers
    # directly so it can flag only the outliers and skip external seams. Equivalent bool:
    # outliers exist iff >=2 distinct non-"other" conventions are present.
    mixed = bool(_mixed_convention_outliers(list(resolved.items())))
    return resolved, mixed


def _apply_reconciler(containers: dict[str, Container], name_overrides: dict[str, str]) -> None:
    """Run the §8.3 reconciler over the container sibling set and each component set.

    Naming is reconciled for *every* sibling, but the ``needs-curation`` mixed-convention
    flag is applied surgically: only to the minority-convention outliers, and never to an
    external/person boundary or contract seam. Those are auto-named from a filename or id
    (e.g. ``contract:proto:basket`` -> "basket"), not curated container names, so they must
    neither receive the flag nor taint the convention check for the hand-named containers
    around them (otherwise one lowercase seam paints a whole well-curated model yellow).
    """
    # containers are siblings of the system.
    sibs = [(c.cid, c.name) for c in containers.values()]
    resolved, _ = reconcile_names(sibs, name_overrides)
    for c in containers.values():
        c.name = resolved[c.cid]
    curated = [(c.cid, c.name) for c in containers.values()
               if not (c.tags & {"external", "person"})]
    for cid in _mixed_convention_outliers(curated):
        containers[cid].tags.add("needs-curation")
    # components are siblings within their container (same surgical, outlier-only flagging).
    for c in containers.values():
        if not c.components:
            continue
        cresolved, _ = reconcile_names([(comp.cid, comp.name) for comp in c.components],
                                       name_overrides)
        for comp in c.components:
            comp.name = cresolved[comp.cid]
        flagged = _mixed_convention_outliers([(comp.cid, comp.name) for comp in c.components])
        for comp in c.components:
            if comp.cid in flagged:
                comp.tags.add("needs-curation")


# --- the emission-normalized facts projection (dynamic-view plan §0.4#1) --------

def _emit_projection(facts: dict[str, Any], rules: Any) -> tuple[
        dict[str, Any], dict[str, "Container"], str, int, dict[str, str]]:
    """The one place the §0.4#1 emission-normalized facts shape is computed.

    Returns ``(facts_emitted, containers, shape, n_targets, target_to_container)``.
    ``facts_emitted`` is the curated facts with each target's ``container_id`` /
    ``container_name`` re-pointed at the EMITTED parent after the container lift (Model Y /
    a D§5 ``expand`` promotion) — the exact shape the downstream view stages bind against.
    The on-disk curated facts (and their determinism hash) are untouched: this is an
    in-memory projection only.

    The curated ``container_name`` is the AUTHORING CONTRACT for hand-owned inputs
    (scenarios.yaml steps say "Web Frontend", deployment image names bind by it) — so a
    SINGLE-member theme keeps its curated name on the emitted target (it aliases
    unambiguously). A multi-member theme's name is genuinely ambiguous at the emitted
    altitude: those targets carry the emitted container's name, and a scenario step
    addressing the theme name stays ``unresolved`` (honest; use the shape-stable
    build-target id instead — scenarios accept target ids directly).

    Factored out of :func:`run` so candidate validation (``scenario_candidates``) and
    ``arch scenarios`` share the EXACT same facts shape used by dynamic-view generation —
    no second/third mapping path (the inbox bait-and-switch this helper exists to prevent).
    """
    shape, n_targets = decide_model_shape(facts, rules)
    containers = build_containers(facts, shape=shape, promote_expanded=True)
    _apply_reconciler(containers, rules.name_overrides)

    # The emitted-parent map: a target that stands alone as a container (Model Y / D§5
    # promotion) IS its own parent; everything else lifts to its curated container.
    target_to_container = {
        t["id"]: (t["id"] if t["id"] in containers else t.get("container_id", t["id"]))
        for t in facts.get("targets", [])}

    if any(target_to_container[t["id"]] != t.get("container_id", t["id"])
           for t in facts.get("targets", [])):
        theme_size = Counter(t.get("container_id", t["id"]) for t in facts.get("targets", []))
        adjusted = []
        for t in facts.get("targets", []):
            pid = target_to_container[t["id"]]
            cur_cid = t.get("container_id", t["id"])
            if pid != cur_cid:
                t = dict(t)
                t["container_id"] = pid
                if theme_size[cur_cid] != 1:
                    t["container_name"] = containers[pid].name
            adjusted.append(t)
        facts_emitted = dict(facts)
        facts_emitted["targets"] = adjusted
    else:
        facts_emitted = facts
    return facts_emitted, containers, shape, n_targets, target_to_container


def emission_normalized_facts(facts: dict[str, Any], rules: Any) -> dict[str, Any]:
    """Public §0.4#1 helper: the emission-normalized facts projection for *facts*.

    The MANDATORY single shared entry point — ``arch scenarios`` /
    ``scenario_candidates.run`` import this so candidate validation uses the same
    target→container mapping as ``generate_structurizr.run``. ``facts_emitted`` varies
    with ``model_shape`` / ``expand``, so the curated-facts shape is NOT interchangeable
    with it. Returns the SAME object as ``facts`` when no target lifts (no spurious copy)."""
    facts_emitted, *_ = _emit_projection(facts, rules)
    return facts_emitted


# --- DSL emission --------------------------------------------------------------

def _emit_container_block(lines: list[str], c: Container, slugs: SlugRegistry,
                          connected: set[str], indent: str = "") -> None:
    ident = slugs.assign(c.cid)
    tags = sorted({"Container", *c.tags})
    lines.append(f'{indent}{ident} = container {_dsl_str(c.name)} '
                 f'{_dsl_str(_container_description(c))} '
                 f'{_dsl_str(_container_technology(c))} {{')
    lines.append(f'{indent}    tags {_dsl_str(",".join(tags))}')
    # A container with NO container-level dependency edge is an evidence-based leaf (the
    # build graph showed no in-model dependency — e.g. a single-library system, or a
    # standalone template project), not a modelling slip. Exempt it from the disconnected-
    # element inspection rather than inventing an edge we have no evidence for (§5/§9.2).
    if c.cid not in connected:
        lines.append(f"{indent}    properties {{")
        lines.append(f'{indent}        "structurizr.inspection.model.element.disconnected" "ignore"')
        lines.append(f"{indent}    }}")
    for comp in c.components:   # already sorted by cid in build_containers
        comp_ident = slugs.assign(comp.cid)
        comp_tags = sorted(comp.tags)
        # Multi-line block (see emit_relationships_dsl): a single-line
        # `{ tags ... }` is rejected by the Structurizr DSL 5.x parser. A non-empty
        # description clears the `model.component.description` inspection (§9.2).
        lines.append(f'{indent}    {comp_ident} = component {_dsl_str(comp.name)} '
                     f'{_dsl_str(_component_description(comp))} {{')
        lines.append(f'{indent}        tags {_dsl_str(",".join(comp_tags))}')
        # A component WITH a component-altitude edge is part of the relationship graph
        # (D§4.3) and stays subject to the disconnected inspection; an edgeless one is a
        # decomposition leaf (namespace/class tier, or a genuinely edge-less target) —
        # exempt it rather than inventing an edge we have no evidence for (§5/§9.2).
        if comp.cid not in connected:
            lines.append(f"{indent}        properties {{")
            lines.append(f'{indent}            "structurizr.inspection.model.element.disconnected" "ignore"')
            lines.append(f"{indent}        }}")
        lines.append(f"{indent}    }}")
    lines.append(f"{indent}}}")


def emit_components_dsl(containers: dict[str, Container], slugs: SlugRegistry,
                        connected: set[str] | None = None) -> str:
    """The container/component model fragment. Containers carrying a ``group`` label
    (Model Y themes / D§5 expanded themes) are wrapped in cosmetic ``group{}`` blocks:
    ungrouped containers first (sorted by cid — byte-identical to the pre-drill-down
    ordering when no groups exist), then groups sorted by label. Groups have no
    identifier and no model identity, so slug stability is untouched (D§3.2)."""
    connected = connected or set()
    lines = [_BANNER]
    for cid in sorted(containers):
        c = containers[cid]
        if c.group:
            continue
        _emit_container_block(lines, c, slugs, connected)
    for label in sorted({c.group for c in containers.values() if c.group}):
        lines.append(f'group {_dsl_str(label)} {{')
        for cid in sorted(cid for cid, c in containers.items() if c.group == label):
            _emit_container_block(lines, containers[cid], slugs, connected, indent="    ")
        lines.append("}")
    return "\n".join(lines) + "\n"


def emit_relationships_dsl(edges: dict, slugs: SlugRegistry,
                           component_edges: dict | None = None) -> str:
    """Container edges, then component-altitude edges (D§4), one machine-owned fragment.

    ``!impliedRelationships false`` pins the implied-relationship strategy OFF: both edge
    altitudes are emitted explicitly and deterministically, with curated labels/tags —
    the DSL default strategy would mint noisy half-duplicates (``A -> b1`` / ``a1 -> B``)
    next to them (the D§12.1 spike). Living in this overwritten-every-run fragment, the
    pin reaches existing hand-owned workspaces without a scaffold migration.
    """
    lines = [_BANNER]
    lines.append("!impliedRelationships false")
    for edge_dict in (edges, component_edges or {}):
        for (cs, ct) in sorted(edge_dict):
            e = edge_dict[(cs, ct)]
            si, ti = slugs.assign(cs), slugs.assign(ct)
            label = e.get("kind") or "Uses"
            tech = _edge_technology(e)
            tags = sorted({"Relationship", *e["tags"]})
            # Multi-line block: the Structurizr DSL parser (5.x) only accepts blocks whose
            # `{` ends the line, body on following lines, `}` on its own line — a SINGLE-line
            # `{ tags ... }` is rejected ("too many tokens"). Mirrors the container emission.
            # The technology (2nd positional) clears the `model.relationship.technology` inspection.
            lines.append(f'{si} -> {ti} {_dsl_str(label)} {_dsl_str(tech)} {{')
            lines.append(f'    tags {_dsl_str(",".join(tags))}')
            lines.append("}")
    return "\n".join(lines) + "\n"


def _scaffold_workspace_dsl(ws: Workspace, system_name: str) -> None:
    if ws.workspace_dsl.exists():
        return
    # A complete, inspection-clean skeleton (§9.1): the workspace scope is set; the actor and
    # the software system carry descriptions and are connected (`user -> system`) so neither is
    # flagged disconnected / off-view; generated documentation + decisions are attached. The
    # architect may rename the actor / refine the description in this hand-owned file afterwards.
    sys_desc = f"Architecture model of {system_name}, extracted from the build graph by Anon."
    content = f'''workspace {_dsl_str(system_name)} "Generated by Anon" {{
  model {{
    user = person "Operator" "A user or operator who interacts with the system."
    system = softwareSystem {_dsl_str(system_name)} {_dsl_str(sys_desc)} {{
      // Generated documentation + decisions (machine-owned, regenerated every run — §9).
      !docs generated/docs
      !adrs generated/adrs
      !include generated/generated-components.dsl
    }}
    user -> system "Uses" "API"
    !include generated/generated-relationships.dsl
    // Deployment/runtime topology (§4.4); banner-only when no deployment artifacts.
    !include generated/generated-deployment.dsl
  }}
  !include views.dsl
  configuration {{
    scope softwaresystem
  }}
}}
'''
    ws.workspace_dsl.write_text(content, encoding="utf-8", newline="")


def _emit_view_intents(ws: Workspace, facts: dict[str, Any]) -> list[str]:
    """Compile ``rules/view-intents.yaml`` -> ``generated/generated-views.dsl`` (§6.1).

    Opt-in / additive: when no ``view-intents.yaml`` exists (the default), a *banner-only*
    file is written so the unconditional ``!include`` in ``views.dsl`` always resolves —
    exactly mirroring the deployment/dynamic fragments (§9.3/§9.4). When intents are
    present, they compile to a deterministic Structurizr ``views.dsl`` fragment. Returns
    advisory validation/over-budget warnings (the run-report / caller may surface them)."""
    intents = view_intents.load_intents(ws.view_intents)
    if intents.get("views"):
        dsl = view_intents.compile_intents(intents, system_identifier="system")
        warnings = view_intents.validate_intents(intents, facts)
    else:
        dsl = _BANNER + "// No rules/view-intents.yaml — banner only (§6.1, opt-in).\n"
        warnings = []
    ws.generated_views_dsl.parent.mkdir(parents=True, exist_ok=True)
    ws.generated_views_dsl.write_text(dsl, encoding="utf-8", newline="")
    return warnings


def _scaffold_views_dsl(ws: Workspace, component_views: list[tuple[str, str]]) -> None:
    """Scaffold ``views.dsl`` once (§9.1). *component_views* is ``(containerIdentifier, name)``."""
    if ws.views_dsl.exists():
        return
    stubs = ""
    for ident, name in sorted(component_views):
        stubs += (f'    // Component view for {name} (auto-drawn: the container has materialized components, D§7.1).\n'
                  f'    // To hand-arrange: DELETE the autolayout line and commit workspace.json (§9.1).\n'
                  f'    component {ident} "Component-{ident}" {{\n'
                  f'        include *\n'
                  f'        autolayout lr\n'
                  f'    }}\n')
    content = f'''// HAND-OWNED (scaffolded once by Anon, then never regenerated — plan §9.1/§12).
// Views and styles live here. workspace.dsl !includes this file.
views {{
    systemContext system "SystemContext" {{
        include *
        autolayout lr
    }}
    container system "Containers" {{
        include *
        autolayout lr
        // To hand-arrange: DELETE the autolayout line above, drag in Structurizr Local,
        // and commit architecture/workspace.json (§9.1).
    }}
{stubs}    // Deployment/runtime + dynamic views (machine-owned, regenerated every run —
    // §9.3/§9.4). Banner-only when no deployment artifacts / no scenarios.yaml.
    !include generated/generated-deployment-views.dsl
    !include generated/generated-dynamic.dsl
    // Canonical/diagnostic views compiled from rules/view-intents.yaml (§6.1).
    // Banner-only when no view-intents.yaml; opt in by copying the template.
    !include generated/generated-views.dsl
    styles {{
        element "Container" {{
            shape roundedbox
        }}
        element "Component" {{
            shape component
        }}
        element "needs-curation" {{
            background #ffcc00
        }}
        element "external" {{
            background #999999
            color #ffffff
        }}
    }}
}}
'''
    ws.views_dsl.write_text(content, encoding="utf-8", newline="")


def check_budgets(containers: dict[str, Container]) -> list[str]:
    """Detect over-budget views (advisory; §9.1/§1.1#1/D§7.2): Container view <=25; each
    Component view (any container with materialized components, D§7.1) <=20. Returns the
    names of over-budget views for the run-report / CLI to surface as a warning. This only
    DETECTS — it never splits, trims, hides, or refuses to emit (D§0.1#3)."""
    over: list[str] = []
    if len(containers) > CONTAINER_BUDGET:
        over.append(f"Containers ({len(containers)} > {CONTAINER_BUDGET})")
    for cid in sorted(containers):
        c = containers[cid]
        if c.components and len(c.components) > COMPONENT_BUDGET:
            over.append(f"Component-{c.name} ({len(c.components)} > {COMPONENT_BUDGET})")
    return over


def run(ws: Workspace) -> dict[str, Any]:
    facts = load_json(ws.enriched_facts if ws.enriched_facts.exists() else ws.curated_facts)
    rules = load_mapping_rules(ws.mapping_rules)

    # §0.4#1: the single shared emission-normalized facts projection. `run` reuses the
    # containers / shape / target_to_container it already computes; `scenario_candidates`
    # / `arch scenarios` import `emission_normalized_facts` for the SAME facts shape.
    facts_emitted, containers, shape, n_targets, target_to_container = \
        _emit_projection(facts, rules)
    edges = build_container_edges(facts, target_to_container)
    # D§3.1/D§4: the targets materialized as components (members of multi-target
    # containers) and the component-altitude projection of their edges. Empty under
    # Model Y, where every module target is already a container.
    materialized = {m for c in containers.values() if len(c.members) >= 2 for m in c.members}
    component_edges = build_component_edges(facts, target_to_container, materialized)
    # D§4 (namespace-tier gap): the INTERIOR edges of a Model-Y module-container (or a D§5
    # expand promotion) — the `…/component:<ns>` namespace->namespace symbol_use edges the
    # Roslyn helper emits. Scoped to components actually materialized in the model so an
    # excluded/aggregated namespace never leaves a dangling edge. Disjoint key space from
    # component_edges (component ids vs target/container ids), so the two merge cleanly.
    emitted_components = {comp.cid for c in containers.values() for comp in c.components}
    namespace_edges = build_namespace_edges(facts, emitted_components)
    # both component-altitude edge dicts share one fragment + the disconnected-leaf
    # accounting; their key spaces are disjoint, so the merge can't collide.
    all_component_edges = {**component_edges, **namespace_edges}

    # element ids that carry at least one edge at EITHER altitude (for the disconnected-
    # leaf exemptions above): an edgeless element is an evidence-based leaf, not a slip.
    connected = ({eid for edge in edges for eid in edge}
                 | {eid for edge in all_component_edges for eid in edge})

    slugs = SlugRegistry()
    ws.components_dsl.parent.mkdir(parents=True, exist_ok=True)
    ws.components_dsl.write_text(emit_components_dsl(containers, slugs, connected),
                                 encoding="utf-8", newline="")
    ws.relationships_dsl.write_text(emit_relationships_dsl(edges, slugs, all_component_edges),
                                    encoding="utf-8", newline="")

    # `facts_emitted` (the §0.4#1 projection) was computed above by `_emit_projection`;
    # the downstream view stages bind elements via each target's emitted `container_id`.

    # P7 view families (§9.3/§9.4): deployment/runtime + dynamic. Run AFTER components so the
    # populated slug registry resolves containerInstance/scenario-step identifiers to the SAME
    # idents used above; run BEFORE the scaffolds so the unconditional !includes in
    # workspace.dsl/views.dsl always point at existing (banner-only when empty) files.
    deploy_res = generate_deployment.run(ws, facts_emitted, slugs)
    dyn_res = scenarios.run(ws, facts_emitted, slugs)
    # Advisory scenario candidates (dynamic-view plan §8): in the `arch run` advisory pass
    # Source B (runtime) runs by DEFAULT; Source C (graph-walk) is OFF by default (opt-in via
    # `arch scenarios --source graph-walk`, §6); Source A is deferred and F (llm) is opt-in
    # only (§4/§7). All reuse the SAME emission-normalized `facts_emitted` so a candidate
    # validates identically when promoted (no inbox bait-and-switch, §0.4#1).
    # Advisory — never fail the run (the §8 advisory-pass discipline).
    try:
        scenario_candidates.run(ws, facts_emitted)   # default sources=["runtime"] — B only
    except Exception:  # pragma: no cover - advisory, never breaks generate
        logging.getLogger("anon.generate_structurizr").warning(
            "scenario-candidate generation failed (advisory; skipped)", exc_info=True)
    # canonical/diagnostic views compiled from view-intents.yaml (§6.1); banner-only by
    # default so the unconditional views.dsl !include always resolves (opt-in/additive).
    view_intent_warnings = _emit_view_intents(ws, facts_emitted)

    # Machine-owned documentation + decisions (§9): regenerated every run, attached via the
    # scaffold's !docs/!adrs so the software-system documentation/decisions inspections pass.
    container_summaries = sorted((c.name, _container_description(c)) for c in containers.values())
    try:
        from . import drift_report
        l0_pct: float | None = round(drift_report._coverage_l0(facts) * 100, 1)
    except Exception:  # pragma: no cover - docs coverage is best-effort
        l0_pct = None
    generate_docs.run(ws, facts_emitted, container_summaries, len(edges), l0_pct=l0_pct)

    system_name = ws.repo.name or "System"
    _scaffold_workspace_dsl(ws, system_name)
    # D§7.1: auto-draw a Component view for EVERY container with >=1 materialized component
    # (Model X: multi-target containers; Model Y: module-containers with an L2 tier; plus
    # D§5 promotions). Identifiers come from the slug registry used above, so the view's
    # `component <ident>` matches the model. A container with NO components gets no view —
    # an empty Component view trips the `views.view.empty` inspection and shows nothing.
    component_views = [(slugs.assign(c.cid), c.name)
                       for c in containers.values() if c.components]
    _scaffold_views_dsl(ws, component_views)

    over_budget = check_budgets(containers)

    return {
        "containers": len(containers),
        "edges": len(edges),
        "component_edges": len(component_edges),
        # D§4 namespace-tier interior edges (Model Y / D§5 expand); 0 under Model X and
        # whenever the Roslyn L2 namespace tier is absent (honest degradation, §18.4).
        "namespace_edges": len(namespace_edges),
        "component_views": len(component_views),
        # D§2.3 legibility: the chosen shape, the input it was chosen from, and whether
        # the user pinned it — so a threshold-hover reshape is never silent.
        "model_shape": shape,
        "model_shape_pinned": getattr(rules, "model_shape", "auto") in ("x", "y"),
        "targets_n": n_targets,
        "model_y_max": MODEL_Y_MAX,
        "over_budget_views": over_budget,
        "deployment_nodes": deploy_res.get("deployment_nodes", 0),
        "deployment_envs": deploy_res.get("envs", []),
        "dynamic_views": dyn_res.get("scenarios", 0),
        "view_intent_warnings": view_intent_warnings,
    }


if __name__ == "__main__":  # pragma: no cover
    import argparse

    from ..paths import resolve_workspace

    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--repo", required=True)
    ap.add_argument("--arch-dir")
    ap.add_argument("--rules-dir")
    args = ap.parse_args()
    w = resolve_workspace(args.repo, args.arch_dir, getattr(args, "rules_dir", None))
    res = run(w)
    print(f"shape {res['model_shape'].upper()} (N={res['targets_n']}): "
          f"{res['containers']} containers, {res['edges']} edges, "
          f"{res['component_edges']} component edges, "
          f"{res['namespace_edges']} namespace edges, "
          f"{res['component_views']} component views; over budget: {res['over_budget_views']}")
