"""Stage 7 — dynamic (behavioral) view generation from hand-authored scenarios (plan §9.4).

Reads ``rules/scenarios.yaml`` (hand-owned, architect-curated) and emits
``generated/generated-dynamic.dsl`` — a set of Structurizr ``dynamic`` view blocks that
sequence EXISTING container relationships — plus, per scenario, the engine §6.9(c)
evidence-validated step-list artifact ``generated/views/dynamic/<scenario>.json`` that
the GUI's sequence strip renders verbatim (``GET /model/dynamic/<scenario>``).

Design principles (§9.4 / engine §6.9c):
  - **Behavior is ordering over evidenced structure (principle #3)**: a dynamic view CANNOT
    invent an edge.  Every step is validated against the curated container graph (BUILD) OR
    the runtime deployment facet (dynamic-view plan §0.3); invalid steps are SKIPPED in the
    DSL and **FLAGGED (never silently dropped) in the JSON** — call order is never invented,
    and an unevidenced step is a first-class answer.
  - **Build vs runtime evidence (dynamic-view plan §0.3/§3.1)**: a step is ``ok`` if its
    ``(from,to)`` is in the build container-edge set OR the runtime ``calls`` edge set. The
    ``evidence_layer`` (``build``/``runtime``) is stamped per step (build wins ties — the
    stronger structural layer). A build-backed step is ``dsl: true`` (Structurizr can draw
    it); a runtime-only step is ``dsl: false`` (no static relationship exists to reference)
    but stays ``ok`` and visible in Anon's JSON/GUI view (plan §0.4#3).
  - **One validator (plan §3.1#3)**: :func:`build_dynamic_view` is the single validation
    result for BOTH the JSON artifact and the DSL emission — :func:`_emit_dynamic_views`
    consumes it rather than re-validating. The GUI↔DSL **step-number correspondence is an
    invariant** (plan §11): a ``dsl:false`` / flagged step is emitted as a NUMBERED DSL
    COMMENT placeholder so GUI step N is always DSL step N.
  - **Always emit the file**: ``generated-dynamic.dsl`` is unconditionally ``!include``d
    by the views scaffold, so the file must exist and be valid inside a ``views {}`` block
    even when no scenarios are configured (banner-only comment in that case).
  - **Deterministic / byte-identical**: steps emit in declaration order (scenarios are
    ordered by the architect); identifiers come from the stable :class:`SlugRegistry`;
    the JSON artifacts carry ``derived_from_hash`` and go through :func:`jsonio.dump_json`.
"""
from __future__ import annotations

import logging
import re
from pathlib import Path
from typing import Any

import jsonschema

from ..config import load_yaml
from ..ids import SlugRegistry
from ..jsonio import dump_json, load_json
from ..model import content_hash
from ..paths import Workspace
from .validate_facts import find_schema

# dynamic-view plan §3.2: the /2 shape (SUPERSET of the file-less /1 constant) — folds in
# evidence_layer / dsl / dsl_reason / dsl_steps / order / ordering_provenance at once.
DYNAMIC_VIEW_SCHEMA = "dynamic-view/2"

# The ordering-provenance enum (plan §1a#4 / §0.4#5). The existing rules/scenarios.yaml path
# is hand-authored; candidate sources stamp their own (observed-in-test / declared-in-aspire
# / synthesized / llm-proposed). Carried into the rendered view so a promoted guess never
# renders identically to an observed flow.
DEFAULT_ORDERING_PROVENANCE = "hand-authored"

log = logging.getLogger("anon.scenarios")

_BANNER = ("// GENERATED BY ANON — DO NOT EDIT. Overwritten every run (plan §9).\n"
           "// Edit scenarios in rules/scenarios.yaml; structure lives in generated-relationships.dsl.\n")


def _dsl_str(s: str) -> str:
    """Escape a string for Structurizr DSL (mirrors generate_structurizr._dsl_str)."""
    return '"' + (s or "").replace("\\", "\\\\").replace('"', '\\"') + '"'


def derived_from_hash(facts_emitted: dict[str, Any]) -> str:
    """Provenance stamp for an emission-normalized artifact (plan §3.2/§0.4#4).

    ``content_hash(facts_emitted)`` — honest provenance of EXACTLY the emission-normalized
    facts that were validated, NOT the raw curated hash (``facts_emitted`` varies with
    ``model_shape``/``expand``). Producers stamp this; it is informational provenance only
    and is NEVER the serve ``If-Hash`` freshness comparator (that is the envelope curated
    hash, plan §9)."""
    return content_hash(facts_emitted)


# ---------------------------------------------------------------------------
# Resolution helpers
# ---------------------------------------------------------------------------

def _build_lookup(facts: dict[str, Any]) -> dict[str, str]:
    """Return a mapping from every acceptable label -> container_id.

    Accepted forms for a step ``from``/``to`` value:
      - exact ``container_id``
      - exact ``container_name`` (case-sensitive, first occurrence wins)
      - build-target ``id`` (maps to its ``container_id``)
    """
    lookup: dict[str, str] = {}
    for t in facts.get("targets", []):
        cid = t.get("container_id", t["id"])
        # build-target id -> container_id
        tid = t["id"]
        if tid not in lookup:
            lookup[tid] = cid
        # container_id -> itself (idempotent)
        if cid not in lookup:
            lookup[cid] = cid
        # container_name -> container_id (first occurrence for this name wins)
        cname = t.get("container_name", "")
        if cname and cname not in lookup:
            lookup[cname] = cid
    return lookup


def _build_container_edges(facts: dict[str, Any]) -> set[tuple[str, str]]:
    """Set of (source_cid, target_cid) inter-container BUILD edges from the curated facts."""
    target_to_container: dict[str, str] = {
        t["id"]: t.get("container_id", t["id"]) for t in facts.get("targets", [])
    }
    edges: set[tuple[str, str]] = set()
    for r in facts.get("relationships", []):
        cs = target_to_container.get(r["source"])
        ct = target_to_container.get(r["target"])
        if cs and ct and cs != ct:
            edges.add((cs, ct))
    return edges


def _runtime_container_edges(
        facts: dict[str, Any]) -> tuple[set[tuple[str, str]], dict[tuple[str, str], dict[str, Any]]]:
    """Lift ``deployment.edges`` with ``kind == "calls"`` to container→container edges
    (dynamic-view plan §0.3/§3.1#1) — the RUNTIME evidence layer (Aspire ``.WithReference``).

    Returns ``(edge_set, citation_index)`` where:
      - ``edge_set`` is the set of ``(source_cid, target_cid)`` runtime ``calls`` pairs where
        BOTH endpoints resolve to a container via the SAME target→container map
        :func:`_build_lookup` uses (a build-target id mapped to its ``container_id``);
      - ``citation_index`` is keyed by ``(source_cid, target_cid)`` and supplies the
        ``description`` / ``cited_edges`` / ``weight`` a runtime-only step needs.
        Runtime-only steps have NO ``relationships[]`` entry, so ``weight`` is ``None``
        (null), NOT summed to 0 — otherwise every runtime ``ok`` step would render
        ``cited_edges:[]`` / ``weight:0``, gutting the §10.1 citation tooltip (plan §3.1#1).
        ``cited_edges`` carry the deployment edge ``detail`` strings.

    A ``deploy:image:*`` / ``infra:*`` endpoint that does NOT resolve to a build target
    yields no container; such a hop is NOT in ``edge_set`` (it is recorded as an
    out-of-model note by the candidate generator, never hidden, plan §0.3)."""
    target_to_container: dict[str, str] = {
        t["id"]: t.get("container_id", t["id"]) for t in facts.get("targets", [])
    }
    deployment = facts.get("deployment") or {}
    by_cedge: dict[tuple[str, str], list[dict[str, Any]]] = {}
    for e in deployment.get("edges", []):
        if e.get("kind") != "calls":
            continue
        cs = target_to_container.get(e.get("source"))
        ct = target_to_container.get(e.get("target"))
        # workload->workload only: both endpoints must resolve to a container, and
        # self-loops are not inter-container edges.
        if cs and ct and cs != ct:
            by_cedge.setdefault((cs, ct), []).append(e)

    edges: set[tuple[str, str]] = set()
    citations: dict[tuple[str, str], dict[str, Any]] = {}
    for cedge, deps in by_cedge.items():
        edges.add(cedge)
        details = [d for e in deps for ev in e.get("evidence", [])
                   if (d := ev.get("detail"))]
        cited = [
            {"source": e.get("source", ""), "target": e.get("target", ""),
             "evidence_layer": "runtime",
             "weight": None,
             "detail": next((ev.get("detail", "") for ev in e.get("evidence", [])), "")}
            for e in sorted(deps, key=lambda e: (e.get("source", ""), e.get("target", "")))]
        citations[cedge] = {
            # description: the first deployment-edge detail (the .WithReference(var) string),
            # a far better label than the build-graph "Uses" fall-through (plan §1a#2).
            "description": details[0] if details else "",
            "cited_edges": cited,
            "weight": None,  # runtime edges carry no relationships[] weight (plan §3.1#1)
        }
    return edges, citations


def _default_label(facts: dict[str, Any], from_cid: str, to_cid: str) -> str:
    """The first ``kind`` found among target-level edges that map to (from_cid, to_cid)."""
    target_to_container: dict[str, str] = {
        t["id"]: t.get("container_id", t["id"]) for t in facts.get("targets", [])
    }
    for r in facts.get("relationships", []):
        cs = target_to_container.get(r["source"])
        ct = target_to_container.get(r["target"])
        if cs == from_cid and ct == to_cid:
            k = r.get("kind")
            if k:
                return k
    return "Uses"


# ---------------------------------------------------------------------------
# Engine §6.9(c) — the evidence-validated step-list JSON for the GUI sequence strip
# ---------------------------------------------------------------------------

_SLUG_RE = re.compile(r"[^a-z0-9]+")


def _scenario_slug(key: str) -> str:
    """A filesystem/URL-safe slug for the scenario key (the serve layer rejects path
    separators; ``GET /model/dynamic/<scenario>`` looks up ``<scenario>.json``)."""
    return _SLUG_RE.sub("-", (key or "").lower()).strip("-") or "scenario"


def _note_for_provenance(provenance: str) -> str:
    """The provenance-aware note (plan §0.4#5): existence is validator-checked, but call
    order is only as trustworthy as the source that produced it. Never hardcode
    'hand-authored' — a promoted Source-C guess would otherwise read as an observed flow."""
    return ("existence of every step is validator-checked against the build container graph "
            "or the runtime deployment facet; the call ORDERING is "
            f"{provenance} and is never treated as observed unless the source observed it "
            "(engine §6.9c; dynamic-view plan §1a#4)")


def build_dynamic_view(scenario: dict[str, Any], facts: dict[str, Any]) -> dict[str, Any]:
    """The §6.9(c) artifact for one scenario: the ordered step list, each step validated
    against the BUILD container graph OR the RUNTIME deployment facet and CITED to its
    contributing target/deployment edges (dynamic-view plan §3.1).

    Unlike the DSL emission (which skips invalid steps), every authored step appears
    here with a ``status`` — ``ok`` | ``unresolved`` | ``unevidenced`` — so the GUI can
    flag what the architect wrote that the evidence does not support, instead of the
    artifact silently pretending the step was never written (honest abstention, moat #5).

    Each ``ok`` step is stamped with ``evidence_layer`` (``build`` wins ties), ``dsl``
    (true iff Structurizr can draw the static relationship), and — for runtime-only steps
    — a ``dsl_reason``. A non-unique ``order`` facet (distinct from the sequential
    ``index``) lets concurrent / fan-out steps share a number (plan §2/§3.1#5); it defaults
    to the sequential position when the proposal omits it. ``ordering_provenance`` is taken
    from the scenario-level field (default ``hand-authored``) and carried into the view so
    the reader knows whether the ordering was observed / declared / synthesized / proposed.
    """
    lookup = _build_lookup(facts)
    t2c = {t["id"]: t.get("container_id", t["id"]) for t in facts.get("targets", [])}
    cname = {t.get("container_id", t["id"]): t.get("container_name", t.get("name", ""))
             for t in facts.get("targets", [])}
    # contributing target-level relationships per lifted BUILD container edge (for citation)
    by_cedge: dict[tuple[str, str], list[dict[str, Any]]] = {}
    for r in facts.get("relationships", []):
        cs, ct = t2c.get(r["source"]), t2c.get(r["target"])
        if cs and ct and cs != ct:
            by_cedge.setdefault((cs, ct), []).append(r)
    # the RUNTIME container-edge set + its citation index (deployment.edges kind==calls)
    runtime_edges, runtime_cite = _runtime_container_edges(facts)

    provenance = scenario.get("ordering_provenance") or DEFAULT_ORDERING_PROVENANCE

    key = scenario.get("key", "")
    scope = scenario.get("scope", "system")
    if scope == "system":
        scope_out: dict[str, Any] = {"value": "system", "status": "ok"}
    else:
        scope_cid = lookup.get(scope)
        scope_out = {"value": scope, "status": "ok", "container_id": scope_cid} \
            if scope_cid else \
            {"value": scope, "status": "unresolved",
             "reason": f"'{scope}' does not name a container or build target"}

    steps: list[dict[str, Any]] = []
    n_ok = 0
    n_dsl = 0
    for i, step in enumerate(scenario.get("steps") or [], start=1):
        from_label = str(step.get("from", ""))
        to_label = str(step.get("to", ""))
        from_cid = lookup.get(from_label)
        to_cid = lookup.get(to_label)
        # `order` is an explicit non-unique parallel facet; default to the sequential
        # position when the proposal omits it (plan §3.1#5). The schema requires an
        # integer ≥ 1, so coerce safely: accept the authored value ONLY when it is a
        # clean positive integer (a bool, a fractional float like 2.5, a non-numeric
        # string, or a value < 1 silently truncating/colliding bands all fall back to
        # the sequential index `i`, which is always ≥ 1). int(2.5)→2 must NOT collapse
        # two distinct authored bands.
        raw_order = step.get("order")
        order = i
        if raw_order is not None and not isinstance(raw_order, bool):
            if isinstance(raw_order, int) and raw_order >= 1:
                order = raw_order
            elif isinstance(raw_order, float) and raw_order.is_integer() and raw_order >= 1:
                order = int(raw_order)
        row: dict[str, Any] = {"index": i, "order": order,
                               "from_raw": from_label, "to_raw": to_label}
        if from_cid is None or to_cid is None:
            missing = from_label if from_cid is None else to_label
            row["status"] = "unresolved"
            row["reason"] = f"'{missing}' does not name a container or build target"
            steps.append(row)
            continue
        row["from"] = from_cid
        row["to"] = to_cid
        row["from_name"] = cname.get(from_cid, from_cid)
        row["to_name"] = cname.get(to_cid, to_cid)
        rels = by_cedge.get((from_cid, to_cid))
        runtime = (from_cid, to_cid) in runtime_edges
        if not rels and not runtime:
            row["status"] = "unevidenced"
            row["reason"] = ("no evidenced build or runtime container edge "
                            f"{from_cid} -> {to_cid} — call order is never invented "
                            "over missing structure (§9.4 principle #3)")
            steps.append(row)
            continue
        n_ok += 1
        row["status"] = "ok"
        if rels:
            # BUILD evidence wins ties — the stronger structural layer (plan §3.1#2).
            row["evidence_layer"] = "build"
            row["dsl"] = True
            n_dsl += 1
            row["description"] = step.get("description") \
                or _default_label(facts, from_cid, to_cid)
            # schema says weight is ["integer","null"] — coerce so a future float
            # relationship weight can't trip jsonschema (compute_weight is int today).
            row["weight"] = int(sum(r.get("weight", 0) for r in rels))
            row["cited_edges"] = [
                {"source": r["source"], "target": r["target"],
                 "evidence_strength": r.get("evidence_strength", ""),
                 "evidence_layer": "build",
                 "weight": r.get("weight", 0)}
                for r in sorted(rels, key=lambda r: (r["source"], r["target"]))]
        else:
            # RUNTIME-only: ok in Anon's JSON/GUI view, but NOT DSL-emittable —
            # Structurizr `dynamic{}` can only reference a static container relationship
            # (plan §0.4#3).
            cite = runtime_cite.get((from_cid, to_cid), {})
            row["evidence_layer"] = "runtime"
            row["dsl"] = False
            row["dsl_reason"] = ("no static container relationship exists for Structurizr "
                                 "to reference (runtime-only edge, plan §0.4#3)")
            row["description"] = step.get("description") or cite.get("description") \
                or _default_label(facts, from_cid, to_cid)
            # runtime edges carry no relationships[] weight — null, NOT 0 (plan §3.1#1)
            row["weight"] = cite.get("weight")
            row["cited_edges"] = cite.get("cited_edges", [])
        steps.append(row)

    return {
        "schema": DYNAMIC_VIEW_SCHEMA,
        "scenario": key,
        "slug": _scenario_slug(key),
        "name": scenario.get("name", key),
        "scope": scope_out,
        "ordering_provenance": provenance,
        "derived_from_hash": content_hash(facts),
        "steps": steps,
        "valid_steps": n_ok,            # all status==ok (build-backed + runtime-only)
        "dsl_steps": n_dsl,             # ok AND dsl:true (emitted to Structurizr DSL)
        "flagged_steps": len(steps) - n_ok,   # unresolved + unevidenced
        "note": _note_for_provenance(provenance),
    }


def validate_dynamic_view(view: dict[str, Any]) -> None:
    """Validate a ``dynamic-view/2`` artifact INLINE against schema/dynamic-view.schema.json
    (plan §3.2) — the enrich_llm.py pattern (``find_schema`` + ``jsonschema.validate``); NOT
    wired into ``arch validate`` or the schema/CHANGELOG gate (advisory, core untouched)."""
    schema = load_json(find_schema("dynamic-view.schema.json"))
    jsonschema.validate(instance=view, schema=schema)


# ---------------------------------------------------------------------------
# DSL emission — consumes the SAME build_dynamic_view result (plan §3.1#3)
# ---------------------------------------------------------------------------

def _emit_dynamic_views(scenarios: list[dict[str, Any]],
                        facts: dict[str, Any],
                        slugs: SlugRegistry) -> tuple[str, list[str], int, int]:
    """Emit all dynamic view blocks, consuming :func:`build_dynamic_view` (no second
    validation path, plan §3.1#3).

    Emits to Structurizr DSL ONLY steps with ``status == "ok"`` AND ``dsl == true``. Every
    other authored step (``unresolved`` / ``unevidenced``, or a runtime-only ``ok``/``dsl:
    false`` step) is emitted as a NUMBERED COMMENT PLACEHOLDER so GUI step N renders as DSL
    step N — the GUI↔DSL step-number correspondence invariant (plan §11). Lines are prefixed
    with the ``order`` number (``N: a -> b``); same-``order`` steps form a shared-N parallel
    band (the explicit shared-step-number form is PRIMARY over the fragile brace block,
    plan §3.1#5).

    Returns ``(dsl_text, emitted_keys, n_skipped_steps, n_runtime_only_steps)`` where
    ``n_skipped_steps`` counts unresolved + unevidenced steps and ``n_runtime_only_steps``
    counts ``ok``/``dsl:false`` (runtime-only) steps across all emitted scenarios.
    """
    lines: list[str] = [_BANNER]
    emitted_keys: list[str] = []
    n_skipped = 0
    n_runtime_only = 0

    for scenario in scenarios:
        view = build_dynamic_view(scenario, facts)
        key = view["scenario"]
        name = view["name"]
        view_steps = view["steps"]

        # A scenario with zero DSL-eligible steps emits no `dynamic{}` block, but its
        # skipped/runtime-only steps are still counted (so the run-report is honest).
        dsl_eligible = [s for s in view_steps if s.get("status") == "ok" and s.get("dsl")]

        # scope resolution: 'system' literal -> the DSL 'system' identifier; a container
        # scope -> its slug ident. An unresolvable scope skips the whole scenario.
        scope = view["scope"]
        if scope.get("value") == "system":
            scope_ident = "system"
        elif scope.get("status") == "ok" and scope.get("container_id"):
            scope_ident = slugs.assign(scope["container_id"])
        else:
            # Unresolvable scope: the WHOLE block is omitted, so EVERY would-be-emitted
            # step is dropped — including the build-backed ok/dsl:true steps that would
            # otherwise have rendered. Count ALL of them as skipped so the run-report
            # never under-reports drops for a bad-scope scenario ("flagged, never
            # silently dropped"). Runtime-only ok steps are tallied separately, as they
            # are everywhere else (they never reach the DSL even with a good scope).
            n_runtime_only += sum(1 for s in view_steps
                                  if s.get("status") == "ok" and not s.get("dsl"))
            n_skipped += sum(1 for s in view_steps
                             if not (s.get("status") == "ok" and not s.get("dsl")))
            continue

        if not dsl_eligible:
            # tally non-DSL steps even when no block is emitted
            n_skipped += sum(1 for s in view_steps if s.get("status") in ("unresolved", "unevidenced"))
            n_runtime_only += sum(1 for s in view_steps
                                  if s.get("status") == "ok" and not s.get("dsl"))
            continue

        lines.append(f'dynamic {scope_ident} {_dsl_str(key)} {_dsl_str(name)} {{')
        for s in view_steps:
            order = s.get("order", s.get("index"))
            status = s.get("status")
            if status == "ok" and s.get("dsl"):
                fi = slugs.assign(s["from"])
                ti = slugs.assign(s["to"])
                # Structurizr's explicit step-number form `N: a -> b "desc"` — same-`order`
                # steps share the number to render as a parallel band (plan §3.1#5; the
                # shared-N prefix is the safer PRIMARY form over the fragile brace block).
                lines.append(f'    {order}: {fi} -> {ti} {_dsl_str(s.get("description", "Uses"))}')
            elif status == "ok" and not s.get("dsl"):
                # runtime-only: a numbered comment placeholder keeps step numbering aligned
                n_runtime_only += 1
                fn = s.get("from_name", s.get("from_raw", ""))
                tn = s.get("to_name", s.get("to_raw", ""))
                lines.append(f'    // {order}: {fn} -> {tn} '
                             '(runtime-only — not in Structurizr model)')
            else:
                # unresolved / unevidenced: a numbered comment placeholder, never silent
                n_skipped += 1
                fr = s.get("from_raw", "")
                tr = s.get("to_raw", "")
                lines.append(f'    // {order}: {fr} -> {tr} '
                             f'(skipped — {status})')
        lines.append("    autolayout lr")
        lines.append("}")
        emitted_keys.append(key)

    return "\n".join(lines) + "\n", emitted_keys, n_skipped, n_runtime_only


def _write_dynamic_views(ws: Workspace, scenarios: list[dict[str, Any]],
                         facts: dict[str, Any]) -> int:
    """Overwrite ``generated/views/dynamic/`` with one §6.9(c) artifact per scenario.

    The directory is machine-owned: stale artifacts for scenarios no longer in
    ``scenarios.yaml`` are removed, so the serve layer can never echo a step list
    against a scenario the architect deleted."""
    out_dir = ws.dynamic_views_dir
    out_dir.mkdir(parents=True, exist_ok=True)
    for old in out_dir.glob("*.json"):
        old.unlink()
    n = 0
    seen: set[str] = set()
    for scenario in scenarios:
        if not scenario.get("key"):
            continue
        view = build_dynamic_view(scenario, facts)
        if view["slug"] in seen:
            # two keys sanitizing to the same slug ("Order Intake" / "order intake")
            # must not silently overwrite each other: disambiguate deterministically
            # by the authored key's hash, declaration order keeps the bare slug.
            import hashlib
            suffix = hashlib.sha256(view["scenario"].encode("utf-8")).hexdigest()[:8]
            view["slug"] = f"{view['slug']}-{suffix}"
        seen.add(view["slug"])
        # Validate the hand-authored view against schema/dynamic-view.schema.json before
        # writing — the candidate path does this, the scenarios.yaml path historically did
        # not, so a hand-authored bad field (e.g. order: 0) could write a schema-invalid
        # artifact that serve echoes unchecked. FAIL-SOFT (advisory discipline): warn and
        # still write so a user's bad scenarios.yaml can never crash `arch run`.
        try:
            validate_dynamic_view(view)
        except jsonschema.ValidationError as exc:
            log.warning(
                "scenario %r produced a schema-invalid dynamic-view/2 artifact "
                "(%s); writing it anyway (advisory) — fix rules/scenarios.yaml.",
                view.get("scenario", view["slug"]), exc.message)
        dump_json(view, out_dir / f"{view['slug']}.json")
        n += 1
    return n


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def run(ws: Workspace, facts: dict[str, Any], slugs: SlugRegistry) -> dict[str, Any]:
    """Emit ``ws.dynamic_dsl`` from ``ws.scenarios_yaml`` + emission-normalized *facts*.

    Parameters
    ----------
    ws:
        Resolved workspace paths (plan §12).
    facts:
        Emission-normalized fact model (``facts_emitted`` — see
        :func:`generate_structurizr.emission_normalized_facts`).  Each target carries the
        EMITTED ``container_id`` / ``container_name``; ``relationships[]`` carry
        ``source``/``target`` build-target ids; ``deployment.edges`` carry the runtime facet.
    slugs:
        A :class:`SlugRegistry` already populated with all container identifiers so that
        ``slugs.assign(container_id)`` returns the same identifier used in
        ``generated-components.dsl`` and ``generated-relationships.dsl``.

    Returns
    -------
    dict with keys:
        ``scenarios``          — number of dynamic view blocks emitted
        ``views``              — list of scenario keys emitted
        ``skipped_steps``      — number of unresolved/unevidenced steps (flagged in JSON)
        ``runtime_only_steps`` — number of ok/dsl:false steps (valid in JSON, not in DSL)
        ``dynamic_artifacts``  — number of §6.9(c) JSON artifacts written
    """
    ws.dynamic_dsl.parent.mkdir(parents=True, exist_ok=True)

    data = load_yaml(ws.scenarios_yaml)
    scenarios = (data.get("scenarios") or []) if data else []

    if not scenarios:
        # Write a banner-only comment — still valid inside a views {} block. Still
        # sweep generated/views/dynamic/ so a deleted scenarios.yaml leaves no stale
        # §6.9(c) artifact behind for the serve layer to echo.
        ws.dynamic_dsl.write_text(_BANNER, encoding="utf-8", newline="")
        if ws.dynamic_views_dir.exists():
            for old in ws.dynamic_views_dir.glob("*.json"):
                old.unlink()
        return {"scenarios": 0, "views": [], "skipped_steps": 0,
                "runtime_only_steps": 0, "dynamic_artifacts": 0}

    dsl, emitted_keys, n_skipped, n_runtime_only = _emit_dynamic_views(scenarios, facts, slugs)
    ws.dynamic_dsl.write_text(dsl, encoding="utf-8", newline="")
    n_artifacts = _write_dynamic_views(ws, scenarios, facts)

    return {
        "scenarios": len(emitted_keys),
        "views": emitted_keys,
        "skipped_steps": n_skipped,
        "runtime_only_steps": n_runtime_only,
        "dynamic_artifacts": n_artifacts,
    }
