// GENERATED BY ANON — DO NOT EDIT. Overwritten every run (plan §9).
// Edit curation in rules/mapping-rules.yaml; views/styles live in views.dsl.

ilmImf = container "IlmImf" "Build target group: IlmImf." "C/C++" {
    tags "Container,cpp,needs-curation"
}
ade = container "ade" "Build target group: ade." "C/C++" {
    tags "Container,cpp,needs-curation"
}
copyOpencvTypingStubs = container "copy_opencv_typing_stubs" "Build target group: copy_opencv_typing_stubs." "C/C++" {
    tags "Container,cpp,needs-curation"
    properties {
        "structurizr.inspection.model.element.disconnected" "ignore"
    }
}
genOpencvJavaSource = container "gen_opencv_java_source" "Build target group: gen_opencv_java_source." "C/C++" {
    tags "Container,cpp,needs-curation,partial:codegen"
    properties {
        "structurizr.inspection.model.element.disconnected" "ignore"
    }
}
genOpencvJsSource = container "gen_opencv_js_source" "Build target group: gen_opencv_js_source." "C/C++" {
    tags "Container,cpp,needs-curation,partial:codegen"
    properties {
        "structurizr.inspection.model.element.disconnected" "ignore"
    }
}
genOpencvObjcSource = container "gen_opencv_objc_source" "Build target group: gen_opencv_objc_source." "C/C++" {
    tags "Container,cpp,needs-curation,partial:codegen"
    properties {
        "structurizr.inspection.model.element.disconnected" "ignore"
    }
}
genOpencvObjcSourceIos = container "gen_opencv_objc_source_ios" "Build target group: gen_opencv_objc_source_ios." "C/C++" {
    tags "Container,cpp,needs-curation,partial:codegen"
    properties {
        "structurizr.inspection.model.element.disconnected" "ignore"
    }
}
genOpencvObjcSourceOsx = container "gen_opencv_objc_source_osx" "Build target group: gen_opencv_objc_source_osx." "C/C++" {
    tags "Container,cpp,needs-curation,partial:codegen"
    properties {
        "structurizr.inspection.model.element.disconnected" "ignore"
    }
}
genOpencvObjcSourceVisionos = container "gen_opencv_objc_source_visionos" "Build target group: gen_opencv_objc_source_visionos." "C/C++" {
    tags "Container,cpp,needs-curation,partial:codegen"
    properties {
        "structurizr.inspection.model.element.disconnected" "ignore"
    }
}
genOpencvPythonSource = container "gen_opencv_python_source" "Build target group: gen_opencv_python_source." "C/C++" {
    tags "Container,cpp,needs-curation,partial:codegen"
    properties {
        "structurizr.inspection.model.element.disconnected" "ignore"
    }
}
jsimd = container "jsimd" "Build target group: jsimd." "C/C++" {
    tags "Container,cpp,needs-curation"
}
jsimdcfg = container "jsimdcfg" "Build target group: jsimdcfg." "C/C++" {
    tags "Container,cpp,needs-curation,partial:codegen"
    properties {
        "structurizr.inspection.model.element.disconnected" "ignore"
    }
}
libjpegTurbo = container "libjpeg-turbo" "Build target group: libjpeg-turbo." "C/C++" {
    tags "Container,cpp,needs-curation,partial:codegen"
}
libopenjp2 = container "libopenjp2" "Build target group: libopenjp2." "C/C++" {
    tags "Container,cpp,needs-curation"
}
libpng = container "libpng" "Build target group: libpng." "C/C++" {
    tags "Container,cpp,needs-curation"
}
libprotobuf = container "libprotobuf" "Build target group: libprotobuf." "C/C++" {
    tags "Container,cpp,needs-curation"
}
libtiff = container "libtiff" "Build target group: libtiff." "C/C++" {
    tags "Container,cpp,needs-curation"
}
libwebp = container "libwebp" "Build target group: libwebp." "C/C++" {
    tags "Container,cpp,needs-curation"
}
ocv3rdpartyDshow = container "ocv.3rdparty.dshow" "Build target group: ocv.3rdparty.dshow." "C/C++" {
    tags "Container,cpp,needs-curation"
}
ocv3rdpartyFfmpeg = container "ocv.3rdparty.ffmpeg" "Build target group: ocv.3rdparty.ffmpeg." "C/C++" {
    tags "Container,cpp,needs-curation"
}
ocv3rdpartyFlatbuffers = container "ocv.3rdparty.flatbuffers" "Build target group: ocv.3rdparty.flatbuffers." "C/C++" {
    tags "Container,cpp,needs-curation"
}
opencvAnnotation = container "opencv_annotation" "Build target group: opencv_annotation." "C/C++" {
    tags "Container,cpp,needs-curation"
}
opencvCalib3d = container "opencv_calib3d" "Build target group: opencv_calib3d." "C/C++" {
    tags "Container,cpp,needs-curation,partial:codegen"
}
opencvCore = container "opencv_core" "Build target group: opencv_core." "C/C++" {
    tags "Container,cpp,needs-curation,partial:codegen"
}
opencvDnn = container "opencv_dnn" "Build target group: opencv_dnn." "C/C++" {
    tags "Container,cpp,needs-curation,partial:codegen"
}
opencvDnnPlugins = container "opencv_dnn_plugins" "Build target group: opencv_dnn_plugins." "C/C++" {
    tags "Container,cpp,needs-curation"
    properties {
        "structurizr.inspection.model.element.disconnected" "ignore"
    }
}
opencvFeatures2d = container "opencv_features2d" "Build target group: opencv_features2d." "C/C++" {
    tags "Container,cpp,needs-curation,partial:codegen"
}
opencvFlann = container "opencv_flann" "Build target group: opencv_flann." "C/C++" {
    tags "Container,cpp,needs-curation"
}
opencvGapi = container "opencv_gapi" "Build target group: opencv_gapi." "C/C++" {
    tags "Container,cpp,needs-curation"
}
opencvHighgui = container "opencv_highgui" "Build target group: opencv_highgui." "C/C++" {
    tags "Container,cpp,needs-curation"
}
opencvHighguiPlugins = container "opencv_highgui_plugins" "Build target group: opencv_highgui_plugins." "C/C++" {
    tags "Container,cpp,needs-curation"
    properties {
        "structurizr.inspection.model.element.disconnected" "ignore"
    }
}
opencvImgcodecs = container "opencv_imgcodecs" "Build target group: opencv_imgcodecs." "C/C++" {
    tags "Container,cpp,needs-curation"
}
opencvImgproc = container "opencv_imgproc" "Build target group: opencv_imgproc." "C/C++" {
    tags "Container,cpp,needs-curation,partial:codegen"
}
opencvInteractiveCalibration = container "opencv_interactive-calibration" "Build target group: opencv_interactive-calibration." "C/C++" {
    tags "Container,cpp,needs-curation"
}
opencvJava = container "opencv_java" "Build target group: opencv_java." "C/C++" {
    tags "Container,cpp,needs-curation"
}
opencvJavaJar = container "opencv_java_jar" "Build target group: opencv_java_jar." "C/C++" {
    tags "Container,cpp,needs-curation,partial:codegen"
    properties {
        "structurizr.inspection.model.element.disconnected" "ignore"
    }
}
opencvJavaJarSourceCopy = container "opencv_java_jar_source_copy" "Build target group: opencv_java_jar_source_copy." "C/C++" {
    tags "Container,cpp,needs-curation,partial:codegen"
    properties {
        "structurizr.inspection.model.element.disconnected" "ignore"
    }
}
opencvJavaJarSources = container "opencv_java_jar_sources" "Build target group: opencv_java_jar_sources." "C/C++" {
    tags "Container,cpp,needs-curation,partial:codegen"
    properties {
        "structurizr.inspection.model.element.disconnected" "ignore"
    }
}
opencvMl = container "opencv_ml" "Build target group: opencv_ml." "C/C++" {
    tags "Container,cpp,needs-curation"
}
opencvModelDiagnostics = container "opencv_model_diagnostics" "Build target group: opencv_model_diagnostics." "C/C++" {
    tags "Container,cpp,needs-curation"
}
opencvModules = container "opencv_modules" "Build target group: opencv_modules." "C/C++" {
    tags "Container,cpp,needs-curation"
    properties {
        "structurizr.inspection.model.element.disconnected" "ignore"
    }
}
opencvObjdetect = container "opencv_objdetect" "Build target group: opencv_objdetect." "C/C++" {
    tags "Container,cpp,needs-curation,partial:codegen"
}
opencvPerfCalib3d = container "opencv_perf_calib3d" "Build target group: opencv_perf_calib3d." "C/C++" {
    tags "Container,cpp,needs-curation"
}
opencvPerfCore = container "opencv_perf_core" "Build target group: opencv_perf_core." "C/C++" {
    tags "Container,cpp,needs-curation"
}
opencvPerfDnn = container "opencv_perf_dnn" "Build target group: opencv_perf_dnn." "C/C++" {
    tags "Container,cpp,needs-curation"
}
opencvPerfFeatures2d = container "opencv_perf_features2d" "Build target group: opencv_perf_features2d." "C/C++" {
    tags "Container,cpp,needs-curation"
}
opencvPerfGapi = container "opencv_perf_gapi" "Build target group: opencv_perf_gapi." "C/C++" {
    tags "Container,cpp,needs-curation"
}
opencvPerfImgcodecs = container "opencv_perf_imgcodecs" "Build target group: opencv_perf_imgcodecs." "C/C++" {
    tags "Container,cpp,needs-curation"
}
opencvPerfImgproc = container "opencv_perf_imgproc" "Build target group: opencv_perf_imgproc." "C/C++" {
    tags "Container,cpp,needs-curation"
}
opencvPerfObjdetect = container "opencv_perf_objdetect" "Build target group: opencv_perf_objdetect." "C/C++" {
    tags "Container,cpp,needs-curation"
}
opencvPerfPhoto = container "opencv_perf_photo" "Build target group: opencv_perf_photo." "C/C++" {
    tags "Container,cpp,needs-curation"
}
opencvPerfStitching = container "opencv_perf_stitching" "Build target group: opencv_perf_stitching." "C/C++" {
    tags "Container,cpp,needs-curation"
}
opencvPerfTests = container "opencv_perf_tests" "Build target group: opencv_perf_tests." "C/C++" {
    tags "Container,cpp,needs-curation"
    properties {
        "structurizr.inspection.model.element.disconnected" "ignore"
    }
}
opencvPerfVideo = container "opencv_perf_video" "Build target group: opencv_perf_video." "C/C++" {
    tags "Container,cpp,needs-curation"
}
opencvPerfVideoio = container "opencv_perf_videoio" "Build target group: opencv_perf_videoio." "C/C++" {
    tags "Container,cpp,needs-curation"
}
opencvPhoto = container "opencv_photo" "Build target group: opencv_photo." "C/C++" {
    tags "Container,cpp,needs-curation,partial:codegen"
}
opencvPython3 = container "opencv_python3" "Build target group: opencv_python3." "C/C++" {
    tags "Container,cpp,needs-curation"
}
opencvStitching = container "opencv_stitching" "Build target group: opencv_stitching." "C/C++" {
    tags "Container,cpp,needs-curation,partial:codegen"
}
opencvTestCalib3d = container "opencv_test_calib3d" "Build target group: opencv_test_calib3d." "C/C++" {
    tags "Container,cpp,needs-curation"
}
opencvTestCore = container "opencv_test_core" "Build target group: opencv_test_core." "C/C++" {
    tags "Container,cpp,needs-curation"
}
opencvTestDnn = container "opencv_test_dnn" "Build target group: opencv_test_dnn." "C/C++" {
    tags "Container,cpp,needs-curation"
}
opencvTestFeatures2d = container "opencv_test_features2d" "Build target group: opencv_test_features2d." "C/C++" {
    tags "Container,cpp,needs-curation"
}
opencvTestFlann = container "opencv_test_flann" "Build target group: opencv_test_flann." "C/C++" {
    tags "Container,cpp,needs-curation"
}
opencvTestGapi = container "opencv_test_gapi" "Build target group: opencv_test_gapi." "C/C++" {
    tags "Container,cpp,needs-curation"
}
opencvTestHighgui = container "opencv_test_highgui" "Build target group: opencv_test_highgui." "C/C++" {
    tags "Container,cpp,needs-curation"
}
opencvTestImgcodecs = container "opencv_test_imgcodecs" "Build target group: opencv_test_imgcodecs." "C/C++" {
    tags "Container,cpp,needs-curation"
}
opencvTestImgproc = container "opencv_test_imgproc" "Build target group: opencv_test_imgproc." "C/C++" {
    tags "Container,cpp,needs-curation"
}
opencvTestMl = container "opencv_test_ml" "Build target group: opencv_test_ml." "C/C++" {
    tags "Container,cpp,needs-curation"
}
opencvTestObjdetect = container "opencv_test_objdetect" "Build target group: opencv_test_objdetect." "C/C++" {
    tags "Container,cpp,needs-curation"
}
opencvTestPhoto = container "opencv_test_photo" "Build target group: opencv_test_photo." "C/C++" {
    tags "Container,cpp,needs-curation"
}
opencvTestStitching = container "opencv_test_stitching" "Build target group: opencv_test_stitching." "C/C++" {
    tags "Container,cpp,needs-curation"
}
opencvTestVideo = container "opencv_test_video" "Build target group: opencv_test_video." "C/C++" {
    tags "Container,cpp,needs-curation"
}
opencvTestVideoio = container "opencv_test_videoio" "Build target group: opencv_test_videoio." "C/C++" {
    tags "Container,cpp,needs-curation"
}
opencvTests = container "opencv_tests" "Build target group: opencv_tests." "C/C++" {
    tags "Container,cpp,needs-curation"
    properties {
        "structurizr.inspection.model.element.disconnected" "ignore"
    }
}
opencvTs = container "opencv_ts" "Build target group: opencv_ts." "C/C++" {
    tags "Container,cpp,needs-curation"
}
opencvVersion = container "opencv_version" "Build target group: opencv_version." "C/C++" {
    tags "Container,cpp,needs-curation"
}
opencvVersionWin32 = container "opencv_version_win32" "Build target group: opencv_version_win32." "C/C++" {
    tags "Container,cpp,needs-curation"
}
opencvVideo = container "opencv_video" "Build target group: opencv_video." "C/C++" {
    tags "Container,cpp,needs-curation,partial:codegen"
}
opencvVideoio = container "opencv_videoio" "Build target group: opencv_videoio." "C/C++" {
    tags "Container,cpp,needs-curation"
}
opencvVideoioPlugins = container "opencv_videoio_plugins" "Build target group: opencv_videoio_plugins." "C/C++" {
    tags "Container,cpp,needs-curation"
    properties {
        "structurizr.inspection.model.element.disconnected" "ignore"
    }
}
opencvVisualisation = container "opencv_visualisation" "Build target group: opencv_visualisation." "C/C++" {
    tags "Container,cpp,needs-curation"
}
uninstall = container "uninstall" "Build target group: uninstall." "C/C++" {
    tags "Container,cpp,needs-curation,partial:codegen"
    properties {
        "structurizr.inspection.model.element.disconnected" "ignore"
    }
}
zlib = container "zlib" "Build target group: zlib." "C/C++" {
    tags "Container,cpp,needs-curation"
}
