// GENERATED BY ANON — DO NOT EDIT. Overwritten every run (plan §9).
// Edit curation in rules/mapping-rules.yaml; views/styles live in views.dsl.

!impliedRelationships false
ilmImf -> zlib "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link"
}
libjpegTurbo -> jsimd "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link"
}
libpng -> zlib "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link"
}
libtiff -> zlib "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link"
}
opencvAnnotation -> opencvCore "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvAnnotation -> opencvHighgui "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvAnnotation -> opencvImgcodecs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvAnnotation -> opencvImgproc "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvAnnotation -> opencvVideoio "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvCalib3d -> opencvCore "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link"
}
opencvCalib3d -> opencvFeatures2d "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link"
}
opencvCalib3d -> opencvFlann "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link"
}
opencvCalib3d -> opencvImgproc "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link"
}
opencvCore -> zlib "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvDnn -> libprotobuf "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvDnn -> ocv3rdpartyFlatbuffers "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvDnn -> opencvCore "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link"
}
opencvDnn -> opencvImgproc "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link"
}
opencvFeatures2d -> opencvCore "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link"
}
opencvFeatures2d -> opencvFlann "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link"
}
opencvFeatures2d -> opencvImgproc "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link"
}
opencvFlann -> opencvCore "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link"
}
opencvGapi -> ade "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvGapi -> opencvCalib3d "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link"
}
opencvGapi -> opencvCore "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link"
}
opencvGapi -> opencvDnn "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link"
}
opencvGapi -> opencvFeatures2d "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link"
}
opencvGapi -> opencvFlann "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link"
}
opencvGapi -> opencvImgproc "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link"
}
opencvGapi -> opencvVideo "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link"
}
opencvHighgui -> opencvCore "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link"
}
opencvHighgui -> opencvImgcodecs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link"
}
opencvHighgui -> opencvImgproc "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link"
}
opencvHighgui -> opencvVideoio "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link"
}
opencvImgcodecs -> ilmImf "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvImgcodecs -> libjpegTurbo "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvImgcodecs -> libopenjp2 "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvImgcodecs -> libpng "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvImgcodecs -> libtiff "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvImgcodecs -> libwebp "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvImgcodecs -> opencvCore "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link"
}
opencvImgcodecs -> opencvImgproc "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link"
}
opencvImgcodecs -> zlib "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvImgproc -> opencvCore "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link"
}
opencvInteractiveCalibration -> opencvCalib3d "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvInteractiveCalibration -> opencvCore "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvInteractiveCalibration -> opencvFeatures2d "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvInteractiveCalibration -> opencvHighgui "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvInteractiveCalibration -> opencvImgproc "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvInteractiveCalibration -> opencvObjdetect "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvInteractiveCalibration -> opencvVideoio "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvJava -> opencvCalib3d "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvJava -> opencvCore "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvJava -> opencvDnn "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvJava -> opencvFeatures2d "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvJava -> opencvFlann "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvJava -> opencvHighgui "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvJava -> opencvImgcodecs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvJava -> opencvImgproc "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvJava -> opencvMl "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvJava -> opencvObjdetect "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvJava -> opencvPhoto "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvJava -> opencvVideo "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvJava -> opencvVideoio "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvMl -> opencvCore "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link"
}
opencvModelDiagnostics -> opencvCore "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvModelDiagnostics -> opencvDnn "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvObjdetect -> opencvCalib3d "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link"
}
opencvObjdetect -> opencvCore "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link"
}
opencvObjdetect -> opencvDnn "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link"
}
opencvObjdetect -> opencvFeatures2d "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link"
}
opencvObjdetect -> opencvFlann "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link"
}
opencvObjdetect -> opencvImgproc "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link"
}
opencvPerfCalib3d -> opencvCalib3d "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfCalib3d -> opencvCore "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfCalib3d -> opencvFeatures2d "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfCalib3d -> opencvFlann "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfCalib3d -> opencvHighgui "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfCalib3d -> opencvImgcodecs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfCalib3d -> opencvImgproc "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfCalib3d -> opencvTs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfCalib3d -> opencvVideoio "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfCore -> opencvCore "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfCore -> opencvHighgui "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfCore -> opencvImgcodecs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfCore -> opencvImgproc "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfCore -> opencvTs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfCore -> opencvVideoio "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfDnn -> opencvCore "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfDnn -> opencvDnn "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfDnn -> opencvHighgui "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfDnn -> opencvImgcodecs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfDnn -> opencvImgproc "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfDnn -> opencvTs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfDnn -> opencvVideoio "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfFeatures2d -> opencvCore "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfFeatures2d -> opencvFeatures2d "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfFeatures2d -> opencvFlann "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfFeatures2d -> opencvHighgui "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfFeatures2d -> opencvImgcodecs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfFeatures2d -> opencvImgproc "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfFeatures2d -> opencvTs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfFeatures2d -> opencvVideoio "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfGapi -> opencvCalib3d "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfGapi -> opencvCore "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfGapi -> opencvDnn "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfGapi -> opencvFeatures2d "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfGapi -> opencvFlann "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfGapi -> opencvGapi "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfGapi -> opencvHighgui "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfGapi -> opencvImgcodecs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfGapi -> opencvImgproc "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfGapi -> opencvTs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfGapi -> opencvVideo "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfGapi -> opencvVideoio "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfImgcodecs -> opencvCore "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfImgcodecs -> opencvHighgui "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfImgcodecs -> opencvImgcodecs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfImgcodecs -> opencvImgproc "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfImgcodecs -> opencvTs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfImgcodecs -> opencvVideoio "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfImgproc -> opencvCore "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfImgproc -> opencvHighgui "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfImgproc -> opencvImgcodecs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfImgproc -> opencvImgproc "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfImgproc -> opencvTs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfImgproc -> opencvVideoio "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfObjdetect -> opencvCalib3d "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfObjdetect -> opencvCore "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfObjdetect -> opencvDnn "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfObjdetect -> opencvFeatures2d "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfObjdetect -> opencvFlann "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfObjdetect -> opencvHighgui "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfObjdetect -> opencvImgcodecs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfObjdetect -> opencvImgproc "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfObjdetect -> opencvObjdetect "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfObjdetect -> opencvTs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfObjdetect -> opencvVideoio "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfPhoto -> opencvCore "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfPhoto -> opencvHighgui "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfPhoto -> opencvImgcodecs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfPhoto -> opencvImgproc "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfPhoto -> opencvPhoto "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfPhoto -> opencvTs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfPhoto -> opencvVideoio "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfStitching -> opencvCalib3d "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfStitching -> opencvCore "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfStitching -> opencvFeatures2d "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfStitching -> opencvFlann "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfStitching -> opencvHighgui "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfStitching -> opencvImgcodecs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfStitching -> opencvImgproc "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfStitching -> opencvStitching "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfStitching -> opencvTs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfStitching -> opencvVideoio "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfVideo -> opencvCalib3d "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfVideo -> opencvCore "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfVideo -> opencvDnn "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfVideo -> opencvFeatures2d "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfVideo -> opencvFlann "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfVideo -> opencvHighgui "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfVideo -> opencvImgcodecs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfVideo -> opencvImgproc "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfVideo -> opencvTs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfVideo -> opencvVideo "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfVideo -> opencvVideoio "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfVideoio -> ocv3rdpartyDshow "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfVideoio -> ocv3rdpartyFfmpeg "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfVideoio -> opencvCore "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfVideoio -> opencvHighgui "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfVideoio -> opencvImgcodecs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfVideoio -> opencvImgproc "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfVideoio -> opencvTs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPerfVideoio -> opencvVideoio "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPhoto -> opencvCore "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link"
}
opencvPhoto -> opencvImgproc "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link"
}
opencvPython3 -> opencvCalib3d "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPython3 -> opencvCore "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPython3 -> opencvDnn "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPython3 -> opencvFeatures2d "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPython3 -> opencvFlann "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPython3 -> opencvGapi "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPython3 -> opencvHighgui "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPython3 -> opencvImgcodecs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPython3 -> opencvImgproc "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPython3 -> opencvMl "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPython3 -> opencvObjdetect "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPython3 -> opencvPhoto "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPython3 -> opencvStitching "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPython3 -> opencvVideo "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvPython3 -> opencvVideoio "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvStitching -> opencvCalib3d "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link"
}
opencvStitching -> opencvCore "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link"
}
opencvStitching -> opencvFeatures2d "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link"
}
opencvStitching -> opencvFlann "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link"
}
opencvStitching -> opencvImgproc "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link"
}
opencvTestCalib3d -> opencvCalib3d "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestCalib3d -> opencvCore "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestCalib3d -> opencvFeatures2d "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestCalib3d -> opencvFlann "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestCalib3d -> opencvHighgui "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestCalib3d -> opencvImgcodecs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestCalib3d -> opencvImgproc "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestCalib3d -> opencvTs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestCalib3d -> opencvVideoio "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestCore -> opencvCore "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestCore -> opencvHighgui "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestCore -> opencvImgcodecs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestCore -> opencvImgproc "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestCore -> opencvTs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestCore -> opencvVideoio "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestDnn -> opencvCore "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestDnn -> opencvDnn "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestDnn -> opencvHighgui "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestDnn -> opencvImgcodecs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestDnn -> opencvImgproc "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestDnn -> opencvTs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestDnn -> opencvVideoio "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestFeatures2d -> opencvCore "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestFeatures2d -> opencvFeatures2d "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestFeatures2d -> opencvFlann "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestFeatures2d -> opencvHighgui "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestFeatures2d -> opencvImgcodecs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestFeatures2d -> opencvImgproc "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestFeatures2d -> opencvTs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestFeatures2d -> opencvVideoio "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestFlann -> opencvCore "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestFlann -> opencvFlann "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestFlann -> opencvHighgui "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestFlann -> opencvImgcodecs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestFlann -> opencvImgproc "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestFlann -> opencvTs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestFlann -> opencvVideoio "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestGapi -> ade "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestGapi -> opencvCalib3d "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestGapi -> opencvCore "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestGapi -> opencvDnn "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestGapi -> opencvFeatures2d "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestGapi -> opencvFlann "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestGapi -> opencvGapi "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestGapi -> opencvHighgui "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestGapi -> opencvImgcodecs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestGapi -> opencvImgproc "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestGapi -> opencvTs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestGapi -> opencvVideo "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestGapi -> opencvVideoio "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestHighgui -> opencvCore "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestHighgui -> opencvHighgui "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestHighgui -> opencvImgcodecs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestHighgui -> opencvImgproc "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestHighgui -> opencvTs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestHighgui -> opencvVideoio "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestImgcodecs -> opencvCore "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestImgcodecs -> opencvHighgui "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestImgcodecs -> opencvImgcodecs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestImgcodecs -> opencvImgproc "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestImgcodecs -> opencvTs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestImgcodecs -> opencvVideoio "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestImgproc -> opencvCore "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestImgproc -> opencvHighgui "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestImgproc -> opencvImgcodecs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestImgproc -> opencvImgproc "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestImgproc -> opencvTs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestImgproc -> opencvVideoio "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestMl -> opencvCore "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestMl -> opencvHighgui "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestMl -> opencvImgcodecs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestMl -> opencvImgproc "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestMl -> opencvMl "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestMl -> opencvTs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestMl -> opencvVideoio "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestObjdetect -> opencvCalib3d "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestObjdetect -> opencvCore "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestObjdetect -> opencvDnn "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestObjdetect -> opencvFeatures2d "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestObjdetect -> opencvFlann "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestObjdetect -> opencvHighgui "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestObjdetect -> opencvImgcodecs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestObjdetect -> opencvImgproc "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestObjdetect -> opencvObjdetect "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestObjdetect -> opencvTs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestObjdetect -> opencvVideoio "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestPhoto -> opencvCore "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestPhoto -> opencvHighgui "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestPhoto -> opencvImgcodecs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestPhoto -> opencvImgproc "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestPhoto -> opencvPhoto "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestPhoto -> opencvTs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestPhoto -> opencvVideoio "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestStitching -> opencvCalib3d "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestStitching -> opencvCore "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestStitching -> opencvFeatures2d "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestStitching -> opencvFlann "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestStitching -> opencvHighgui "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestStitching -> opencvImgcodecs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestStitching -> opencvImgproc "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestStitching -> opencvStitching "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestStitching -> opencvTs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestStitching -> opencvVideoio "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestVideo -> opencvCalib3d "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestVideo -> opencvCore "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestVideo -> opencvDnn "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestVideo -> opencvFeatures2d "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestVideo -> opencvFlann "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestVideo -> opencvHighgui "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestVideo -> opencvImgcodecs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestVideo -> opencvImgproc "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestVideo -> opencvTs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestVideo -> opencvVideo "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestVideo -> opencvVideoio "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestVideoio -> ocv3rdpartyDshow "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestVideoio -> ocv3rdpartyFfmpeg "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestVideoio -> opencvCore "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestVideoio -> opencvHighgui "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestVideoio -> opencvImgcodecs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestVideoio -> opencvImgproc "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestVideoio -> opencvTs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTestVideoio -> opencvVideoio "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvTs -> opencvCore "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link"
}
opencvTs -> opencvHighgui "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link"
}
opencvTs -> opencvImgcodecs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link"
}
opencvTs -> opencvImgproc "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link"
}
opencvTs -> opencvVideoio "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link"
}
opencvVersion -> opencvCore "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvVersionWin32 -> opencvCore "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvVideo -> opencvCalib3d "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link"
}
opencvVideo -> opencvCore "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link"
}
opencvVideo -> opencvDnn "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link"
}
opencvVideo -> opencvFeatures2d "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link"
}
opencvVideo -> opencvFlann "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link"
}
opencvVideo -> opencvImgproc "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link"
}
opencvVideoio -> ocv3rdpartyDshow "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvVideoio -> ocv3rdpartyFfmpeg "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvVideoio -> opencvCore "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link"
}
opencvVideoio -> opencvImgcodecs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link"
}
opencvVideoio -> opencvImgproc "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link"
}
opencvVisualisation -> opencvCore "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvVisualisation -> opencvHighgui "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvVisualisation -> opencvImgcodecs "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvVisualisation -> opencvImgproc "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
opencvVisualisation -> opencvVideoio "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
