<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Label="Globals">
    <ProjectName>NativeHost</ProjectName>
  </PropertyGroup>
  <PropertyGroup>
    <ConfigurationType>Application</ConfigurationType>
    <CLRSupport>true</CLRSupport>
  </PropertyGroup>
  <ItemGroup>
    <ClCompile Include="NativeHost.cpp" />
  </ItemGroup>
</Project>
