"""Generator-neutral ``view-intents.yaml`` -> ``views.dsl`` compiler (plan §6.1).

A **view-intent** describes *what a view should answer and what it includes/excludes*
in **fact-model terms** (element/tag selectors, C4 altitude, element budget) — **with no
DSL syntax baked in** (§6.1). This module keeps the two halves deliberately separate:

  - :func:`load_intents` parses the neutral intent document (DSL-agnostic). A future
    PlantUML / Mermaid / Graphviz backend reuses this verbatim.
  - :func:`compile_intents` is the **Structurizr backend**: it lowers the neutral intents
    into a deterministic ``views.dsl`` fragment string. Swap this function for another
    backend and the same intents render to another tool.
  - :func:`validate_intents` returns advisory, human-readable warnings (over-budget views,
    dangling ``filtered`` bases, empty includes). It never raises.

Intent document shape (``rules/view-intents.yaml``)
---------------------------------------------------
::

    views:
      - key: containers            # required; the Structurizr view key + filtered base ref
        type: container            # systemContext | container | component | filtered
        title: "Containers"        # optional human title (defaults to key)
        scope: system              # optional element identifier the view is scoped to
                                   #   (systemContext/container/component); default "system"
        include: ["*"]             # element/tag selectors in FACT-MODEL terms (default ["*"])
        exclude: ["external"]      # element/tag selectors to hide (default [])
        budget: 25                 # §1.1 readability budget for validation (optional)
        autolayout: lr             # lr | tb | bt | rl | false (omit line); default "lr"
        description: "..."         # optional view description

      - key: messaging             # a FILTERED view (§9.2) over a base view's shared layout
        type: filtered
        base: containers           # required for filtered: the base view key
        mode: include              # include | exclude (default include)
        include: ["messaging", "Relationship"]   # tags to keep (or drop, if mode=exclude)

Selectors are emitted verbatim into Structurizr ``include``/``exclude`` statements: ``"*"``
becomes the bare ``*`` wildcard, every other token is quoted. Filtered views join their
selector tokens with commas (Structurizr's ``filtered`` grammar, §9.2).

Determinism (a hard CI gate, see CLAUDE.md): output is a **pure function** of the input
dict — author list order is preserved (intentional, never sorted), LF newlines only, no
timestamps or randomness. ``compile_intents(x) == compile_intents(x)`` byte-for-byte.
"""
from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml

# Banner matches the machine-generated marker used by generate_structurizr.py / scenarios.py
# so the three-tier lifecycle (§9.1) is visible in the emitted fragment.
_BANNER = ("// GENERATED BY ANON — DO NOT EDIT. Overwritten every run (plan §9).\n"
           "// Edit view intents in rules/view-intents.yaml; styles live in views.dsl.\n")

# The C4 altitude keywords Structurizr accepts as a view's opening token (§9.1/§9.3).
_SCOPED_TYPES = ("systemContext", "container", "component")
_VALID_TYPES = (*_SCOPED_TYPES, "filtered")
_AUTOLAYOUT_DIRS = ("lr", "tb", "bt", "rl")


def _dsl_str(s: str) -> str:
    """Escape a string for Structurizr DSL (mirrors generate_structurizr._dsl_str)."""
    return '"' + (s or "").replace("\\", "\\\\").replace('"', '\\"') + '"'


def _as_list(value: Any) -> list[str]:
    """Coerce a scalar / list / None selector field into a list of strings (order-preserving)."""
    if value is None:
        return []
    if isinstance(value, str):
        return [value]
    return [str(v) for v in value]


# ---------------------------------------------------------------------------
# Loading (backend-neutral)
# ---------------------------------------------------------------------------

def load_intents(path: Path) -> dict:
    """Load ``view-intents.yaml`` (§6.1). Absent / empty file -> ``{}``.

    Returns the raw, DSL-agnostic intent document (a ``dict`` with a ``views`` list).
    This parsing is intentionally separate from any DSL emission so that an alternate
    (PlantUML/Mermaid/...) backend can reuse it unchanged.
    """
    p = Path(path)
    if not p.exists():
        return {}
    with open(p, encoding="utf-8") as fh:
        data = yaml.safe_load(fh)
    return data or {}


# ---------------------------------------------------------------------------
# Selector lowering (Structurizr backend)
# ---------------------------------------------------------------------------

def _selector_token(sel: str) -> str:
    """Lower one fact-model selector to a Structurizr include/exclude token.

    ``"*"`` is the bare wildcard (Structurizr requires it unquoted); every other selector
    is a tag/identifier and is quoted.
    """
    return "*" if sel == "*" else _dsl_str(sel)


def _emit_scoped_view(view: dict[str, Any], system_identifier: str) -> list[str]:
    """Emit a systemContext / container / component view block (multi-line)."""
    vtype = view["type"]
    key = str(view.get("key", ""))
    scope = str(view.get("scope") or system_identifier)
    title = view.get("title", key)
    description = view.get("description", "")

    includes = _as_list(view.get("include")) or ["*"]
    excludes = _as_list(view.get("exclude"))
    autolayout = view.get("autolayout", "lr")

    header = f'{vtype} {scope} {_dsl_str(key)} {_dsl_str(title)}'
    if description:
        header += f' {_dsl_str(description)}'
    lines = [header + " {"]
    for sel in includes:
        lines.append(f'    include {_selector_token(sel)}')
    for sel in excludes:
        lines.append(f'    exclude {_selector_token(sel)}')
    # autolayout: a direction string emits the line; an explicit False/None omits it so the
    # view becomes hand-arrangeable (manual layout in workspace.json, §9.1).
    if isinstance(autolayout, str) and autolayout in _AUTOLAYOUT_DIRS:
        lines.append(f'    autolayout {autolayout}')
    lines.append("}")
    return lines


def _emit_filtered_view(view: dict[str, Any]) -> list[str]:
    """Emit a one-line filtered view over a base view's shared layout (§9.2).

    Grammar: ``filtered "<base>" include|exclude "<comma-tags>" "<newKey>"``.
    """
    key = str(view.get("key", ""))
    base = str(view.get("base", ""))
    mode = view.get("mode", "include")
    if mode not in ("include", "exclude"):
        mode = "include"
    tags = _as_list(view.get("include")) if mode == "include" else _as_list(view.get("exclude"))
    # filtered tags are joined into ONE comma-separated quoted string (§9.2 grammar).
    tag_str = _dsl_str(",".join(tags))
    return [f'filtered {_dsl_str(base)} {mode} {tag_str} {_dsl_str(key)}']


def compile_intents(intents: dict, *, system_identifier: str = "system") -> str:
    """Compile neutral *intents* into a deterministic Structurizr ``views.dsl`` fragment (§6.1).

    Emits only the **view block lines** (no surrounding ``views { }`` wrapper — the caller's
    scaffold owns that, §9.1), prefixed with the machine-generated banner. Author list order
    is preserved (intentional curation order, never sorted). Unknown/invalid view types are
    skipped so a malformed entry cannot produce un-parseable DSL.

    *system_identifier* is the DSL identifier of the single ``softwareSystem`` (default
    ``"system"`` to match the §9.1 workspace scaffold); used as the default scope for
    scoped views that omit ``scope``.
    """
    views = (intents or {}).get("views") or []
    lines: list[str] = [_BANNER.rstrip("\n")]
    for view in views:
        if not isinstance(view, dict):
            continue
        vtype = view.get("type")
        if vtype in _SCOPED_TYPES:
            lines.extend(_emit_scoped_view(view, system_identifier))
        elif vtype == "filtered":
            lines.extend(_emit_filtered_view(view))
        # unknown type -> skip (validate_intents surfaces it as a warning).
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Validation (advisory)
# ---------------------------------------------------------------------------

def validate_intents(intents: dict, curated_facts: dict | None = None) -> list[str]:
    """Return human-readable, advisory warnings about *intents* (§6.1). Never raises.

    Checks (all advisory — the pipeline does not gate on them):
      - **over budget**: a view declaring a ``budget`` whose selected element count would
        exceed it. Without per-view element resolution we conservatively compare the curated
        container count against the budget for a ``"*"``-including container/systemContext
        view (the §1.1 readability budget, the only count the fact model can supply cheaply).
      - **dangling base**: a ``filtered`` view whose ``base`` key matches no other view key.
      - **empty include**: a non-filtered view with no include selectors (renders an empty
        diagram), or a filtered view whose active selector list is empty.
      - **unknown type**: a view ``type`` outside the supported set.
      - **missing key**: a view with no ``key`` (un-addressable / un-referenceable).
    """
    warnings: list[str] = []
    views = (intents or {}).get("views") or []
    facts = curated_facts or {}

    # cheap element count for budget checks: number of curated containers (the Container-view
    # population). target.container_id groups targets into containers (§7.4).
    container_ids = {
        t.get("container_id", t.get("id"))
        for t in facts.get("targets", [])
        if t.get("container_id", t.get("id"))
    }
    container_count = len(container_ids)

    known_keys = {str(v.get("key")) for v in views if isinstance(v, dict) and v.get("key")}

    for view in views:
        if not isinstance(view, dict):
            warnings.append("View entry is not a mapping; skipped.")
            continue
        key = str(view.get("key") or "")
        label = key or "<no key>"
        vtype = view.get("type")

        if not key:
            warnings.append("A view has no 'key'; it cannot be referenced or rendered.")

        if vtype not in _VALID_TYPES:
            warnings.append(
                f"View '{label}' has unknown type {vtype!r} "
                f"(expected one of {', '.join(_VALID_TYPES)})."
            )
            continue

        if vtype == "filtered":
            base = str(view.get("base") or "")
            if not base:
                warnings.append(f"Filtered view '{label}' has no 'base' view key.")
            elif base not in known_keys:
                warnings.append(
                    f"Filtered view '{label}' references base '{base}', "
                    f"which is not a defined view key."
                )
            mode = view.get("mode", "include")
            active = _as_list(view.get("include")) if mode != "exclude" else _as_list(view.get("exclude"))
            if not active:
                warnings.append(
                    f"Filtered view '{label}' has an empty {('exclude' if mode == 'exclude' else 'include')} "
                    f"selector; it filters nothing."
                )
            continue

        # scoped view (systemContext / container / component)
        includes = _as_list(view.get("include"))
        if not includes:
            warnings.append(
                f"View '{label}' has an empty 'include'; it would render an empty diagram "
                f"(use ['*'] to include everything)."
            )

        budget = view.get("budget")
        if isinstance(budget, int) and budget > 0:
            # only the wildcard container/context population is countable from the fact model;
            # a tag-scoped view's true count needs full element resolution we don't do here.
            if vtype in ("container", "systemContext") and ("*" in includes) and container_count > budget:
                warnings.append(
                    f"View '{label}' may exceed its element budget "
                    f"({container_count} containers > {budget}); consider grouping or a split (§1.1)."
                )

    return warnings
