#!/usr/bin/env python3
"""Emit latex/generated/macros.tex: every in-prose number as a \\newcommand,
so the paper never hard-codes a statistic (evaluation plan §15.5).

Reads stats.json's flat "summary_macros" map {macroName: value} and writes one
\\newcommand per entry. Names must match those used in latex/sections/*.tex
(e.g. \\rqOneMedianMoJo, \\rqTwoAcdcMoJo, \\corpusSystemCount).
"""
from __future__ import annotations
import argparse, json, pathlib, sys

HEADER = ("%% GENERATED by analysis/make_macros.py -- DO NOT EDIT BY HAND.\n"
          "%% Refreshing the data re-typesets the paper (plan §15).\n")


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--stats", type=pathlib.Path, default=pathlib.Path("stats.json"))
    ap.add_argument("--out", type=pathlib.Path,
                    default=pathlib.Path("../latex/generated/macros.tex"))
    args = ap.parse_args(argv)

    macros = {}
    if args.stats.exists():
        macros = json.loads(args.stats.read_text()).get("summary_macros", {})

    lines = [HEADER]
    if macros:
        for name, value in sorted(macros.items()):
            if any(ch.isdigit() for ch in name):   # TeX macro names cannot carry digits
                raise SystemExit(f"macro name with a digit: {name} (rename it in stats.py)")
            lines.append(f"\\newcommand{{\\{name}}}{{{value}}}\n")
    else:
        lines.append("%% scaffold: no summary_macros yet — placeholders remain in macros.tex\n")
    args.out.write_text("".join(lines), encoding="utf-8", newline="\n")
    print(f"wrote {len(macros)} macros -> {args.out}", file=sys.stderr)


if __name__ == "__main__":
    main()
