#!/usr/bin/env python3
"""Emit the booktabs tables under latex/tables/ from results.csv (eval plan §15.3 / §15.2).

STDLIB ONLY (no pandas) — pivots the tidy results.csv into LaTeX booktabs, deterministically.
Tables with data today: corpus, rq1_fidelity, rq2_baselines, rq3_ablation, rq5_stability,
rq6_drift (seeded mutations + degradation, 2026-07-16), rq7_perf (cold/warm perf, 2026-07-16).
rq8_human stays a placeholder (study spun out to a companion plan).

Reporting rules baked in from the 2026-06 findings (plan §1.2a/§4.1/§13):
  * **a2a-led** — RQ1 leads with a2a (MoJoFM is gamed by `dir` on aligned C++).
  * **no-curation floor shown** — every fidelity row carries the A2 `none` rung beside it.
  * **projection labelled** — pipeline/acdc/wca/limbo/dir/cc are the fair all-common projection
    (WCA/LIMBO consolidated onto it 2026-07-13); ARC stays on its own covered subset (topic-based
    partial coverage, daggered); the §6.2 LLM-recovery baseline is llm-rerun-mean. Never silent.
  * **Tier-P marked, never blended (plan §5.5/§14.3)** — anonymized industrial rows (P-codes,
    ingested via aggregate_results.py --anon) render AFTER the OSS corpus, name-marked
    $^\\ddagger$ with a non-replicable footnote; with no Tier-P rows present the output is
    byte-identical to the OSS-only tables.
"""
from __future__ import annotations

import argparse
import csv
import pathlib
import re
import sys

TABLES = ["corpus", "rq1_fidelity", "rq2_baselines", "rq2_clusters", "rq5_stability",
          "rq3_ablation", "rq6_drift", "rq6_combined", "rq6_history", "rq7_perf", "rq8_human",
          "rq9_curation", "rq9_effort"]
HAVE_DATA = {"corpus", "rq1_fidelity", "rq2_baselines", "rq2_clusters", "rq3_ablation",
             "rq5_stability", "rq6_drift", "rq6_combined", "rq6_history", "rq7_perf",
             "rq9_curation", "rq9_effort"}
# RQ numbering (review 2026-09-04, presentation): the PAPER numbers its evaluated questions
# consecutively, the pre-registration (eval plan §3) keeps its ids. File names, labels and
# macro prefixes stay on the pre-registered ids; only the rendered caption text carries the
# paper number. Map: RQ1-3 = RQ1-3, RQ5 -> RQ4, RQ6 -> RQ5, RQ7 -> RQ6, RQ9 -> RQ7 (RQ4 and
# RQ8 are the deferred companion studies).
PAPER_RQ = {"RQ1": "RQ1", "RQ2": "RQ2", "RQ3": "RQ3", "RQ5": "RQ4", "RQ6": "RQ5",
            "RQ7": "RQ6", "RQ9": "RQ7"}

SYS_ORDER = ["itk", "abseil", "opencv", "bash", "libxml2", "eshop", "orchardcore", "nopcommerce",
             "squidex"]   # squidex admitted 2026-08-30 (companion plan §5 step 7; eval §12 note)
SYS_DISPLAY = {"itk": "ITK", "abseil": "abseil", "opencv": "OpenCV", "bash": "bash",
               "libxml2": "libxml2", "eshop": "eShop",
               "orchardcore": "OrchardCore", "nopcommerce": "nopCommerce", "squidex": "Squidex"}
# Build idiom per system (a design fact, not a measured number) — Table I column (item 2.4).
BUILD_IDIOM = {"itk": "CMake", "abseil": "CMake", "opencv": "CMake", "bash": "Makefile.in",
               "libxml2": "automake", "eshop": ".NET SDK", "orchardcore": ".NET SDK",
               "nopcommerce": ".NET SDK", "squidex": ".NET SDK"}
# Curation provenance per system (item 1.3, answers reviewer Q1): how the scored curated model
# was authored. `sighted` = with the reference in view (the three C# GT-doc curations, §VII);
# `assisted` = LLM-assisted from names/directories/docs, the published reference's tier known
# but its mapping not consulted (the C++ overlays, plans/notes/2026-06-14-llm-in-curation…);
# `blind` = the pre-registered reference-blind RQ9 curator (Squidex; eShop's RQ9 row);
# `none` = the scored curated model is identical to the floor (libxml2: one library target,
# floor == curated == 11.4, so no curation decision reached the scored partition).
CURATION = {"itk": "assisted", "abseil": "assisted", "opencv": "assisted", "bash": "assisted",
            "libxml2": "none", "eshop": "sighted", "orchardcore": "sighted",
            "nopcommerce": "sighted", "squidex": "blind",
            # owner 2026-09-16 (response plan §14.12): one author curated P-1 with the 2022
            # inception diagram in view -- the diagram the GT-diag reference was reconciled from;
            # targets added since were placed without guidance. Sighted, as the paper defines it.
            "P-1": "sighted"}
GEN = "%% GENERATED by analysis/make_tables.py from results.csv -- DO NOT EDIT BY HAND.\n"
# Sizing for the wide (7-8 column) tabulars in single-column floats, which otherwise
# overrun the IEEE \columnwidth (overfull hbox -> table bleeds into the margin). The
# tighter \tabcolsep does the work; \footnotesize only pins what IEEEtran already
# defaults table floats to, so the tables stay put under a documentclass change.
FIT = "  \\footnotesize\\setlength{\\tabcolsep}{3.5pt}\n"

P_RE = re.compile(r"^P-\d{1,2}$")   # Tier-P codes (anonymize_results.py / aggregate --anon)
# Caption legends shortened 2026-09-13 (review P4 "captions overloaded"; response plan §13): the
# terminology paragraph (latex/shared/terms.tex, shared by paper and TR, cited as the enclosing
# section sec:design) carries the shared legend, captions keep only table-local marks.
TIER_P_NOTE = " $^\\ddagger$Anonymized proprietary system, non-replicable, corroborating only."
# Tier-P floor / propose cells come from the A2 rungs (see a2_fallback); said once per table.
TIER_P_A2_NOTE = " P-1 floor/propose: its A2 rungs."

# Display language (review 2026-09-13): bash and libxml2 are C. results.csv's `language=cpp`
# names the extractor family (the C/C++ L0 path), not the source language.
LANG_DISPLAY = {"bash": "C", "libxml2": "C"}


def _lang(system: str, code: str | None) -> str:
    return LANG_DISPLAY.get(system, "C++" if code == "cpp" else "C\\#")


def _p_present(rows) -> bool:
    return any(P_RE.match(r["system"]) for r in rows)


# Systems whose RQ1 `pipeline` row is the reference-blind RQ9 curation (decision 2026-08-30):
# marked in Table RQ1 so a reader sees it is curated-expression, non-circular by construction.
BLIND_CURATED = {"squidex"}
BLIND_NOTE = " $^\\S$Squidex's only curated model is its reference-blind RQ7 curation."


def _disp(s: str) -> str:
    """Display name; Tier-P systems carry the $\\ddagger$ non-replicable marker."""
    return f"{s}$^\\ddagger$" if P_RE.match(s) else SYS_DISPLAY.get(s, s)


def load(results_csv: pathlib.Path) -> list[dict]:
    with results_csv.open(encoding="utf-8") as f:
        return list(csv.DictReader(f))


def pivot(rows, *, axis, metric, projection=None) -> dict[str, dict[str, float]]:
    """(system -> technique -> value) for one axis/metric (optionally one projection)."""
    out: dict[str, dict[str, float]] = {}
    for r in rows:
        if r["axis"] != axis or r["metric"] != metric:
            continue
        if projection is not None and r["projection"] != projection:
            continue
        try:
            out.setdefault(r["system"], {})[r["technique"]] = float(r["value"])
        except (TypeError, ValueError):
            continue
    return out


def pipeline_overlay(rows, base: dict[str, dict[str, float]], metric: str) -> dict[str, dict[str, float]]:
    """Overlay the module-granularity `pipeline` value (the opencv structure-vs-presentation
    override, projection=module-gran) onto an all-common pivot so the headline pipeline number is
    the structural one, not the coarse presentation curation."""
    for s, d in pivot(rows, axis="fidelity", metric=metric, projection="module-gran").items():
        if "pipeline" in d:
            base.setdefault(s, {})["pipeline"] = d["pipeline"]
    return base


# Tier-P rows arrive through the anonymized channel with the A2 rungs but no `fidelity` axis
# (review 2026-09-13: "P-1 has no floor, no propose row"). The no-curation floor IS the A2 `none`
# rung and the propose draft the `propose_all` rung (the same partitions, on the a2-ablation's
# own common projection), so those two cells are filled from A2 wherever the fidelity axis is
# silent. OSS systems always carry the fidelity rows, so their output is byte-identical.
A2_FALLBACK = {"floor": "none", "propose": "propose_all"}


def a2_fallback(rows, base: dict[str, dict[str, float]], metric: str) -> dict[str, dict[str, float]]:
    a2 = pivot(rows, axis="A2", metric=metric, projection="common-a2")
    for s, d in a2.items():
        for key, rung in A2_FALLBACK.items():
            if key not in base.get(s, {}) and rung in d:
                base.setdefault(s, {})[key] = d[rung]
    return base


#: SAR + naïve techniques scored on the pre-registered all-common projection (§6.4). ARC is
#: excluded (topic-based partial coverage, reported on its own subset) as is the LLM baseline.
ALL_COMMON = ("acdc", "wca", "limbo", "dir", "cc")


def _win_count(rows, metric: str, row: str = "pipeline", strict: bool = True) -> str:
    """"k of n" — systems where the candidate row (pipeline / floor / propose) beats every
    all-common classical baseline; STRICT (>) by default, >= with strict=False. Mirrors
    stats.py's `_wins` rule exactly so caption and macros can never disagree (item 5.1)."""
    base = pivot(rows, axis="fidelity", metric=metric, projection="all-common")
    cand = pipeline_overlay(rows, pivot(rows, axis="fidelity", metric=metric), metric) \
        if row == "pipeline" else base
    oss = [s for s in systems_in(rows) if not P_RE.match(s)]
    scored = [s for s in oss
              if cand.get(s, {}).get(row) is not None
              and any(t in base.get(s, {}) for t in ALL_COMMON)]
    wins = sum(1 for s in scored
               if all((cand[s][row] > base[s][t]) if strict else (cand[s][row] >= base[s][t])
                      for t in ALL_COMMON if t in base[s]))
    return f"{wins} of {len(scored)}"


def systems_in(rows) -> list[str]:
    """OSS corpus in canonical order, then any Tier-P codes (sorted) — never interleaved."""
    present = {r["system"] for r in rows}
    return ([s for s in SYS_ORDER if s in present]
            + sorted(s for s in present if P_RE.match(s)))


def _meta(rows) -> dict[str, dict]:
    m = {}
    for r in rows:
        m.setdefault(r["system"], {"language": r["language"], "ref_grade": r["ref_grade"],
                                   "ref_clusters": r["ref_clusters"], "ref_entities": r["ref_entities"]})
    return m


def _fmt(x) -> str:
    return f"{x:.1f}" if isinstance(x, (int, float)) else "--"


# ----------------------------------------------------------------- tables

def t_corpus(rows) -> str:
    return (GEN + "%% Merged into rq1_fidelity.tex (one table*, labels tab:corpus + tab:rq1 + "
            "tab:rq3) for the page budget -- review response 2026-08-30.\n")


def t_rq1(rows) -> str:
    """Corpus + RQ1 + the A1/A5 ablation columns in ONE table* (page budget): every fidelity
    number on the all-common projection; floor and propose are the autonomous rows, the curated
    model is the expression row; A1 = container edges at L0 -> all layers; A5 = edges the
    declared-never-dropped rule saves at the operating threshold 3 / at threshold 8."""
    a2a = a2_fallback(rows, pipeline_overlay(rows, pivot(rows, axis="fidelity", metric="a2a", projection="all-common"), "a2a"), "a2a")
    mojo = a2_fallback(rows, pipeline_overlay(rows, pivot(rows, axis="fidelity", metric="mojofm", projection="all-common"), "mojofm"), "mojofm")
    a5 = pivot(rows, axis="A5", metric="edges_saved")
    a1e = pivot(rows, axis="A1", metric="edges")
    meta = _meta(rows)
    targets = {}
    for r in rows:
        if r["axis"] == "RQ7" and r["technique"] == "pipeline" and r["metric"] == "targets":
            try:
                targets[r["system"]] = int(float(r["value"]))
            except (TypeError, ValueError):
                pass
    # Same first-party definition read from the workspace facts (axis=size) for systems the RQ7
    # sweep never ran (Squidex) — the column was `--` there although the facts exist.
    for r in rows:
        if (r["axis"] == "size" and r["metric"] == "first_party_targets"
                and r["system"] not in targets):
            try:
                targets[r["system"]] = int(float(r["value"]))
            except (TypeError, ValueError):
                pass
    body = []
    for s in systems_in(rows):
        m_ = meta[s]
        lang = _lang(s, m_["language"])
        a, m = a2a.get(s, {}), mojo.get(s, {})
        bl = [m.get(t) for t in ALL_COMMON if m.get(t) is not None]
        best = max(bl) if bl else None
        mark = "$^\\S$" if s in BLIND_CURATED else ""
        tgt = targets.get(s)
        l0, full = a1e.get(s, {}).get("L0"), a1e.get(s, {}).get("+L3")
        a1cell = f"{int(l0)}$\\to${int(full)}" if (l0 is not None and full is not None) else "--"
        s3, s8 = a5.get(s, {}).get("t3"), a5.get(s, {}).get("t8")
        a5cell = (f"{int(s3)}/{int(s8)}" if (s3 is not None and s8 is not None) else "--")
        body.append(f"    {_disp(s)}{mark} & {lang} & {BUILD_IDIOM.get(s, '--')} & {m_['ref_grade']} & "
                    f"{CURATION.get(s, '--')} & {m_['ref_clusters']} & {m_['ref_entities']} & "
                    f"{tgt if tgt is not None else '--'} & "
                    f"{_fmt(a.get('floor'))} & {_fmt(m.get('floor'))} & "
                    f"{_fmt(a.get('propose'))} & {_fmt(m.get('propose'))} & "
                    f"{_fmt(a.get('pipeline'))} & {_fmt(m.get('pipeline'))} & "
                    f"{_fmt(best)} & {a1cell} & {a5cell} \\\\")
    extra = ((" GT-diag = inception-era diagram, architect-reconciled (P-1 curated with that "
              "diagram in view); $^\\ddagger$anonymized "
              "proprietary system, non-replicable, corroborating only (entity count bucketed)."
              + TIER_P_A2_NOTE)
             if _p_present(rows) else "") + \
        (BLIND_NOTE if any(s in BLIND_CURATED for s in systems_in(rows)) else "")
    return (GEN + "\\begin{table*}[t]\n  \\centering\n"
            "  \\caption{Corpus, RQ1 fidelity, and the A1/A5 ablation columns (terms: "
            "\\S\\ref{sec:design}). \\#Cl./\\#Ent./\\#Tgt.\\ = reference clusters, scored "
            "entities, first-party targets; Best = best all-common classical baseline by MoJoFM; "
            "A1 = container edges at L0 $\\to$ all layers; A5 = container edges the "
            "never-drop-declared rule saves at threshold 3 / 8." + extra
            + "}\n  \\label{tab:corpus}\\label{tab:rq1}\\label{tab:rq3}\n"
            "  \\footnotesize\\setlength{\\tabcolsep}{3pt}\n"
            "  \\begin{tabular}{@{}lllll rrr rr rr rr r rr@{}}\n    \\toprule\n"
            # (a detection/expression group row was tried 2026-09-13 and cost a table* page)
            "    & & & & & & & & \\multicolumn{2}{c}{Floor} & \\multicolumn{2}{c}{Propose} & "
            "\\multicolumn{2}{c}{Curated} & Best & A1 & A5 \\\\\n"
            "    \\cmidrule(lr){9-10}\\cmidrule(lr){11-12}\\cmidrule(lr){13-14}\n"
            "    System & Lang & Build & Ref & Cur. & \\#Cl. & \\#Ent. & \\#Tgt. & a2a & MoJo & "
            "a2a & MoJo & a2a & MoJo & MoJo & edges & t3/t8 \\\\\n"
            "    \\midrule\n" + "\n".join(body) + "\n    \\bottomrule\n  \\end{tabular}\n\\end{table*}\n")


def t_rq2(rows) -> str:
    """RQ2: every technique on the all-common set, MoJoFM and a2a as two stacked blocks.
    Columns lead with the two AUTONOMOUS pipeline rows (floor, propose) so the detection
    comparison is read against them; the curated model is the expression row. ARC keeps its
    own covered subset (daggered, outside the paired test); the LLM is the rerun mean. The
    best value per row is bold whatever technique produced it (item 5.1: the win rule is in
    the caption and computed, never asserted)."""
    def block(metric):
        allc = a2_fallback(rows, pipeline_overlay(rows, pivot(rows, axis="fidelity", metric=metric, projection="all-common"), metric), metric)
        pair = pivot(rows, axis="fidelity", metric=metric, projection="pairwise")
        llmp = pivot(rows, axis="fidelity", metric=metric, projection="llm-rerun-mean")
        # rerun dispersion of the LLM baseline, printed beside its mean (review 2026-09-04)
        llms = pivot(rows, axis="fidelity", metric=f"{metric}_stdev", projection="llm-rerun-mean")
        cols = [("floor", "Floor", allc), ("propose", "Prop.", allc),
                ("pipeline", "Curated", allc), ("acdc", "ACDC", allc),
                ("arc", "ARC$^\\dagger$", pair), ("wca", "WCA", allc), ("limbo", "LIMBO", allc),
                ("dir", "dir", allc), ("cc", "cc", allc), ("llm", "LLM$^\\S$", llmp)]
        lines = []
        for s in systems_in(rows):
            vals = {}
            for key, _h, src in cols:
                v = src.get(s, {}).get(key)
                if v is None and src is allc:
                    v = pair.get(s, {}).get(key)
                vals[key] = v
            present = [v for v in vals.values() if v is not None]
            best = max(present) if present else None
            cells = []
            for key, v in vals.items():
                cell = ("\\textbf{%s}" % _fmt(v)) if (v is not None and v == best) else _fmt(v)
                sd = llms.get(s, {}).get("llm") if key == "llm" else None
                if v is not None and isinstance(sd, (int, float)):
                    cell += f"$\\pm${sd:.1f}"
                cells.append(cell)
            lines.append(f"    {_disp(s)} & " + " & ".join(cells) + " \\\\")
        header = ("    System & " + " & ".join(h for _k, h, _s in cols) + " \\\\\n")
        return cols, header, lines

    cols, head_m, body_m = block("mojofm")
    _c, head_a, body_a = block("a2a")
    win = ("Strict wins against the five all-common baselines: curated %s systems on MoJoFM "
           "and %s on a2a; floor %s and %s; propose %s and %s."
           % (_win_count(rows, "mojofm"), _win_count(rows, "a2a"),
              _win_count(rows, "mojofm", "floor"), _win_count(rows, "a2a", "floor"),
              _win_count(rows, "mojofm", "propose"), _win_count(rows, "a2a", "propose")))
    extra = ((TIER_P_NOTE + TIER_P_A2_NOTE) if _p_present(rows) else "")
    # the detection/expression group row lives in Table I only (page budget, 2026-09-13)
    groups = ""
    return (GEN + "\\begin{table*}[t]\n  \\centering\n"
            "  \\caption{RQ2: MoJoFM (top) and a2a (bottom) vs.\\ the reference on the "
            "all-common projection, best per row in bold. " + win
            + " $^\\dagger$ARC on its own covered subset. $^\\S$LLM, mean $\\pm$ sd of five "
            "reruns; -- = refused or not run." + extra
            + "}\n  \\label{tab:rq2}\n  \\footnotesize\\setlength{\\tabcolsep}{4pt}\n"
            "  \\begin{tabular}{@{}l" + "r" * len(cols) + "@{}}\n    \\toprule\n"
            + groups + head_m + "    \\midrule\n" + "\n".join(body_m)
            + "\n    \\midrule\n" + head_a.replace("System", "System (a2a)")
            + "    \\midrule\n" + "\n".join(body_a)
            + "\n    \\bottomrule\n  \\end{tabular}\n\\end{table*}\n")


def t_rq2_clusters(rows) -> str:
    """Cluster count k of every scored partition (review 2026-09-04: MoJoFM and a2a are to be
    read beside k, and Table I's #Tgt is neither the floor's k nor anyone else's) and, since
    2026-09-09 (eval plan section 12 (m)), the post-hoc adjusted Rand index of the same partitions
    as a second block set BESIDE the first in a two-column-wide float (stacked, the twelve columns
    overflow a single column by ~35pt). All-common projection; ARC falls back to its own covered
    subset (pairwise) where it has no all-common row; Ref = reference clusters. The k block has no
    LLM column (it was asked for the reference count; its per-rerun k lives in the artifact); the
    ARI block prints the LLM rerun mean +- sd. The opencv module-granularity pipeline override
    applies as in Table II. A row whose ARI cells are all absent (Tier-P: the anonymized export
    carries no ARI) is left out of the ARI block."""
    k = a2_fallback(rows, pipeline_overlay(rows, pivot(rows, axis="fidelity", metric="clusters",
                                                       projection="all-common"), "clusters"), "clusters")
    kp = pivot(rows, axis="fidelity", metric="clusters", projection="pairwise")
    ar = pipeline_overlay(rows, pivot(rows, axis="fidelity", metric="ari", projection="all-common"), "ari")
    arp = pivot(rows, axis="fidelity", metric="ari", projection="pairwise")
    arl = pivot(rows, axis="fidelity", metric="ari", projection="llm-rerun-mean")
    arls = pivot(rows, axis="fidelity", metric="ari_stdev", projection="llm-rerun-mean")
    meta = _meta(rows)
    cols = [("floor", "Floor"), ("propose", "Prop."), ("pipeline", "Cur."), ("acdc", "ACDC"),
            ("arc", "ARC$^\\dagger$"), ("wca", "WCA"), ("limbo", "LIMBO"), ("dir", "dir"),
            ("cc", "cc")]
    acols = cols + [("llm", "LLM$^\\S$")]
    body_k, body_ari = [], []
    for s in systems_in(rows):
        cells = []
        for key, _h in cols:
            v = k.get(s, {}).get(key)
            if v is None:
                v = kp.get(s, {}).get(key)
            cells.append(str(int(v)) if isinstance(v, (int, float)) else "--")
        body_k.append(f"    {_disp(s)} & {meta[s]['ref_clusters']} & " + " & ".join(cells) + " \\\\")
        vals = {}
        for key, _h in acols:
            src = arl if key == "llm" else ar
            v = src.get(s, {}).get(key)
            if v is None and key != "llm":
                v = arp.get(s, {}).get(key)
            vals[key] = v
        present = [v for v in vals.values() if v is not None]
        if not present:
            continue
        best = max(present)
        acells = []
        for key, v in vals.items():
            cell = ("\\textbf{%s}" % _fmt(v)) if (v is not None and v == best) else _fmt(v)
            sd = arls.get(s, {}).get("llm") if key == "llm" else None
            if v is not None and isinstance(sd, (int, float)):
                cell += f"$\\pm${sd:.1f}"
            acells.append(cell)
        body_ari.append(f"    {_disp(s)} & " + " & ".join(acells) + " \\\\")
    extra = ((TIER_P_NOTE + TIER_P_A2_NOTE) if _p_present(rows) else "")
    tab_k = ("  \\begin{tabular}{@{}l r" + " r" * len(cols) + "@{}}\n    \\toprule\n"
             "    System & Ref & " + " & ".join(h for _k, h in cols) + " \\\\\n    \\midrule\n"
             + "\n".join(body_k) + "\n    \\bottomrule\n  \\end{tabular}")
    tab_ari = ("  \\begin{tabular}{@{}l" + " r" * len(acols) + "@{}}\n    \\toprule\n"
               "    System & " + " & ".join(h for _k, h in acols) + " \\\\\n    \\midrule\n"
               + "\n".join(body_ari) + "\n    \\bottomrule\n  \\end{tabular}")
    return (GEN + "\\begin{table*}[t]\n  \\centering\n"
            "  \\caption{Cluster count $k$ (left; Ref = reference clusters; -- = not recorded) "
            "and post-hoc ARI ($\\times$100, right; best per row in bold; $^\\S$mean $\\pm$ sd of "
            "the LLM reruns) of every partition in Tables~\\ref{tab:rq1} and~\\ref{tab:rq2}. "
            "$^\\dagger$ARC on its own covered subset." + extra
            + "}\n  \\label{tab:rq2k}\n"
            "  \\scriptsize\\setlength{\\tabcolsep}{2.5pt}\n"
            + tab_k + "\\hfill\n" + tab_ari + "\n\\end{table*}\n")


def t_rq3(rows) -> str:
    return (GEN + "%% Merged into rq1_fidelity.tex (A1 / A5 columns) for the page budget -- "
            "review response 2026-08-30.\n")


def t_rq5(rows) -> str:
    return (GEN + "%% Dropped for the page budget (review response 2026-08-30): the RQ5/A8 churn "
            "numbers (paper RQ4) are cited as macros in the prose (rqFive*).\n")


def t_rq6(rows) -> str:
    """RQ6: (a) seeded-mutation detection per operator (§8.1, counts pooled across the
    mutation systems); (b) the §8.2 degradation / stopping-rules check per induced mode."""
    ops = ["add_forbidden_dep", "remove_dep", "add_target", "remove_target",
           "rename_target", "merge_targets"]
    acc: dict[str, dict[str, float]] = {}
    mut_systems = set()
    for r in rows:
        if r["axis"] != "RQ6-mut":
            continue
        mut_systems.add(r["system"])
        try:
            d = acc.setdefault(r["technique"], {})
            d[r["metric"]] = d.get(r["metric"], 0) + float(r["value"])
        except (TypeError, ValueError):
            continue

    def _prf(d):
        tp, fn, fp = d.get("tp", 0), d.get("fn", 0), d.get("fp", 0)
        prec = tp / (tp + fp) if tp + fp else None
        rec = tp / (tp + fn) if tp + fn else None
        f1 = 2 * prec * rec / (prec + rec) if prec and rec else \
            (0.0 if (prec is not None and rec is not None) else None)
        return prec, rec, f1

    def _pct(x):
        return f"{100 * x:.1f}" if x is not None else "--"

    body = []
    total: dict[str, float] = {}
    for op in [o for o in ops if o in acc]:
        d = acc[op]
        for k, v in d.items():
            total[k] = total.get(k, 0) + v
        prec, rec, f1 = _prf(d)
        disp = "\\texttt{" + op.replace("_", "\\_") + "}"
        body.append(f"    {disp} & {int(d.get('n', 0))} & {int(d.get('detected', 0))} & "
                    f"{int(d.get('tp', 0))} & "
                    f"{int(d.get('fn', 0))} & {int(d.get('fp', 0))} & "
                    f"{_pct(prec)} & {_pct(rec)} & {_pct(f1)} \\\\")
    prec, rec, f1 = _prf(total)
    body.append("    \\midrule")
    body.append(f"    \\textbf{{overall}} & {int(total.get('n', 0))} & "
                f"{int(total.get('detected', 0))} & "
                f"{int(total.get('tp', 0))} & {int(total.get('fn', 0))} & "
                f"{int(total.get('fp', 0))} & \\textbf{{{_pct(prec)}}} & "
                f"\\textbf{{{_pct(rec)}}} & \\textbf{{{_pct(f1)}}} \\\\")

    # --- (b) degradation modes ---
    deg: dict[str, dict[str, float]] = {}
    deg_adv: dict[str, list[float]] = {}
    for r in rows:
        if r["axis"] != "RQ6-deg":
            continue
        try:
            v = float(r["value"])
        except (TypeError, ValueError):
            continue
        if r["metric"] == "advisory":
            deg_adv.setdefault(r["technique"], []).append(v)
        elif r["metric"] in ("would_be_false", "suppressed", "leaked"):
            d = deg.setdefault(r["technique"], {})
            d[r["metric"]] = d.get(r["metric"], 0) + v
    deg_body = []
    mode_disp = {"disable_l2": "L2 toolchain lost", "starve_l0_10": "10\\% targets starved",
                 "starve_l0_30": "30\\% targets starved (floor)",
                 "lose_l0": "L0 extractor lost"}
    for mode in ("disable_l2", "starve_l0_10", "starve_l0_30", "lose_l0"):
        if mode not in deg:
            continue
        d = deg[mode]
        wb, sup = d.get("would_be_false", 0), d.get("suppressed", 0)
        adv = deg_adv.get(mode, [])
        # the advisory downgrade is the L0-floor mechanism — only the starvation modes
        # exercise it; per-finding reclassification carries the other two
        adv_cell = (f"{int(sum(adv))}/{len(adv)}"
                    if adv and mode.startswith("starve") else "--")
        deg_body.append(f"    {mode_disp[mode]} & {int(wb)} & {int(sup)} & "
                        f"{_pct(sup / wb) if wb else '--'} & {adv_cell} \\\\")

    n_sys = len(mut_systems)
    del deg_body   # block (b) is prose-only in the paper (macros); its rows stay in stats.json
    return (GEN + "\\begin{table}[t]\n  \\centering\n"
            "  \\caption{" + PAPER_RQ["RQ6"] + " seeded-mutation detection per operator, pooled over "
            + str(n_sys) + " systems (first-party L0 scope): Mut.\\ = injected mutations, "
            "Det.\\ = mutations every expected finding of which was reported, TP/FN/FP = "
            "drift-report findings (one per vanished or new target, edge, rename, or "
            "violation, so a removed target yields several).}\n"
            "  \\label{tab:rq6}\n" + FIT
            + "  \\begin{tabular}{@{}l rrrrr rrr@{}}\n    \\toprule\n"
            "    Operator & Mut. & Det. & TP & FN & FP & Prec. & Rec. & F1 \\\\\n    \\midrule\n"
            + "\n".join(body) + "\n    \\bottomrule\n  \\end{tabular}\n\\end{table}\n")


def _rq6_comb_hist(rows):
    """RQ6 (c) a real change AND evidence loss at once (mutate/combined.py): per induced
    mode, pooled over the mutation systems, where every injected finding surfaced; (d) the
    real-history arm (mutate/history.py): consecutive release pairs under frozen rules.
    Returns (n_sys, combined-table body rows, history-table body rows); the two tables are
    emitted by t_rq6_combined / t_rq6_history."""
    comb = [r for r in rows if r["axis"] == "RQ6-comb" and ":" not in r["technique"] and r["projection"] == "combined"]
    hist = [r for r in rows if r["axis"] == "RQ6-hist"]

    def _sum(rs, technique, metric, system=None):
        return int(sum(float(r["value"]) for r in rs if r["technique"] == technique
                       and r["metric"] == metric and (system is None or r["system"] == system)))

    mode_disp = {"starve_l0_10": "10\\% targets starved", "starve_l0_30": "30\\% starved (floor)",
                 "starve_mutated": "mutated targets starved", "lose_l0": "L0 extractor lost"}
    n_sys = len({r["system"] for r in comb})
    cbody = []
    for mode in ("starve_l0_10", "starve_l0_30", "starve_mutated", "lose_l0"):
        if not any(r["technique"] == mode for r in comb):
            continue
        cells = [_sum(comb, mode, m) for m in ("n", "findings", "drift", "gap", "advisory",
                                                 "silent", "fp")]
        silent = f"\\textbf{{{cells[5]}}}" if cells[5] else "0"
        cbody.append(f"    {mode_disp.get(mode, mode)} & {cells[0]} & {cells[1]} & {cells[2]} & "
                     f"{cells[3]} & {cells[4]} & {silent} & {cells[6]} \\\\")

    hbody = []
    pairs = sorted({(r["system"], r["technique"]) for r in hist},
                   key=lambda st: (SYS_ORDER.index(st[0]) if st[0] in SYS_ORDER else 99, st[1]))
    label_cols = ("architectural", "non-architectural", "extraction-noise")
    for s, t in pairs:
        def v(metric):
            return _sum(hist, t, metric, s)
        pending = v("labels_pending") > 0
        # the counts shown are the findings BOTH raters gave the label (aggregate_results
        # emits `label_<lab>_agreed`); one rater's column would hide the disagreements,
        # which the text reports through raw agreement and kappa
        lab = "--" if pending else "/".join(str(v(f"label_{lc}_agreed")) for lc in label_cols)
        a, b = (x.replace("release-", "") for x in t.split("..", 1))   # nopCommerce tag prefix
        hbody.append(f"    {_disp(s)} {a}$\\to${b} & {v('commits_total')} & "
                     f"{v('commits_build_files')} & {v('drift_total')} & "
                     f"{v('coverage_gap_targets') + v('coverage_gap_edges')} & "
                     f"{v('needs_curation_new_b')} & {lab} \\\\")

    return n_sys, cbody, hbody


def t_rq6_combined(rows) -> str:
    """tab:rq6b, the combined-loss replay. Since the shortening pass (response plan §13, M1)
    this float lives in the companion technical report only; the paper keeps the prose."""
    n_sys, cbody, _ = _rq6_comb_hist(rows)
    if not cbody:
        return GEN + "%% no RQ6-comb rows in results.csv yet -- placeholder.\n"
    return (GEN + "\\begin{table}[t]\n  \\centering\n"
            "  \\caption{" + PAPER_RQ["RQ6"] + ": seeded mutations replayed with evidence loss "
            "induced on the mutated run, pooled over " + str(n_sys) + " systems -- where each "
            "injected finding surfaced. Drift = reported as named drift; Gap = a labelled "
            "coverage gap; Adv. = visible only through the run's advisory downgrade; "
            "Silent = hidden.}\n"
            "  \\label{tab:rq6b}\n" + FIT
            + "  \\begin{tabular}{@{}l rrrrrrr@{}}\n    \\toprule\n"
            "    Evidence loss & Mut. & Find. & Drift & Gap & Adv. & Silent & FP \\\\\n"
            "    \\midrule\n" + "\n".join(cbody) + "\n    \\bottomrule\n  \\end{tabular}\n"
            "\\end{table}\n")


def t_rq6_history(rows) -> str:
    """tab:rq6hist, the real-history arm. Two separate floats (review 2026-09-07): the
    combined-loss replay and the real-history arm are unrelated experiments and must not
    share one table; since plan §13 they are two files, and this one stays in the paper."""
    _, _, hbody = _rq6_comb_hist(rows)
    if not hbody:
        return GEN + "%% no RQ6-hist rows in results.csv yet -- placeholder.\n"
    return (GEN + "\\begin{table}[t]\n  \\centering\n"
            "  \\caption{" + PAPER_RQ["RQ6"] + ": real release history, fixed consecutive "
            "releases (not selected by changelog), rules held constant across each pair. "
            "Build = commits touching build files; New = first-party targets the later release "
            "adds that the rules leave unmapped; Labels = findings both raters labelled "
            "identically (architectural/non-architectural/noise; -- = pending; disagreements "
            "and $\\kappa$ in the text).}\n"
            "  \\label{tab:rq6hist}\n"
            # 3.5pt overruns \columnwidth by ~5pt with the release-pair column; this table only
            + "  \\footnotesize\\setlength{\\tabcolsep}{3pt}\n"
            + "  \\begin{tabular}{@{}l rrrrrl@{}}\n    \\toprule\n"
            "    Release pair & Commits & Build & Find. & Gaps & New & Labels \\\\\n"
            "    \\midrule\n" + "\n".join(hbody)
            + "\n    \\bottomrule\n  \\end{tabular}\n\\end{table}\n")


def t_rq7(rows) -> str:
    """RQ7: cold/warm end-to-end pipeline runs, peak process-tree RSS, and size axes —
    ordered by KLOC so the table IS the scaling curve's data (§10)."""
    perf: dict[str, dict[str, float]] = {}
    langs: dict[str, str] = {}
    for r in rows:
        if r["axis"] != "RQ7" or r["technique"] != "pipeline":
            continue
        try:
            perf.setdefault(r["system"], {})[r["metric"]] = float(r["value"])
        except (TypeError, ValueError):
            continue
        langs[r["system"]] = r["language"]
    order = sorted(perf, key=lambda s: (perf[s].get("kloc") is None,
                                        perf[s].get("kloc", 0.0), s))

    def _cell(v, nd=1):
        return f"{v:.{nd}f}" if isinstance(v, (int, float)) else "--"

    body = []
    for s in order:
        d = perf[s]
        lang = _lang(s, langs.get(s))
        disp = _disp(s)
        kloc_v = d.get("kloc")
        kloc_cell = _cell(kloc_v, 1 if isinstance(kloc_v, float) and kloc_v < 10 else 0)
        body.append(
            f"    {disp} & {lang} & {kloc_cell} & "
            f"{int(d['targets']) if d.get('targets') is not None else '--'} & "
            f"{_cell(d.get('cold_s'))} & {_cell(d.get('warm_s'))} & "
            f"{_cell(d.get('speedup'))}$\\times$ & "
            f"{int(d['cold_peak_rss_mb']) if d.get('cold_peak_rss_mb') is not None else '--'} \\\\")
    extra = TIER_P_NOTE if _p_present(rows) else ""
    return (GEN + "\\begin{table}[t]\n  \\centering\n"
            "  \\caption{" + PAPER_RQ["RQ7"] + ": end-to-end wall-clock (s), cold vs.\\ warm (incremental "
            "cache), speedup, and peak RSS (MB) of the whole process tree, ordered by "
            "first-party KLOC. Budgets: cold $\\le$30\\,min, warm $\\le$3\\,min." + extra
            + "}\n  \\label{tab:rq7}\n"
            # units live in the caption: unit-carrying headers set the column widths
            # and push the 8-column tabular past \columnwidth
            + FIT + "  \\begin{tabular}{@{}ll rr rrrr@{}}\n    \\toprule\n"
            "    System & Lang & KLOC & Targets & Cold & Warm & Speedup & "
            "RSS \\\\\n    \\midrule\n"
            + "\n".join(body) + "\n    \\bottomrule\n  \\end{tabular}\n\\end{table}\n")


def _rq9_systems(rows) -> list[str]:
    present = {r["system"] for r in rows if r["axis"] == "RQ9"}
    return [s for s in SYS_ORDER if s in present] + sorted(present - set(SYS_ORDER))


def _rq9_val(rows, s, tech, metric, projection, *, prefix=False):
    if tech is None:
        return None
    for r in rows:
        if r["system"] != s or r["axis"] != "RQ9" or r["metric"] != metric \
                or r["projection"] != projection:
            continue
        if (r["technique"].startswith(tech) if prefix else r["technique"] == tech):
            try:
                return float(r["value"])
            except (TypeError, ValueError):
                return None
    return None


# RQ9: the pre-registered (first) curator per system — mirrors stats.RQ9_PRIMARY_CURATOR so
# the table's "blind curator" row and the macros can never name different people; a further
# curator (the variance arm, response plan 1.5b) gets its own indented row.
RQ9_PRIMARY_CURATOR = {"eshop": "R-A", "squidex": "R-C"}


def _rq9_curators(rows, s) -> tuple[str | None, list[str]]:
    """(technique name of the primary curator, codes of the further curators)."""
    codes = sorted({r["technique"].split(":", 1)[1] for r in rows
                    if r["system"] == s and r["axis"] == "RQ9"
                    and r["technique"].startswith("curator:")})
    plain = any(r["system"] == s and r["axis"] == "RQ9" and r["technique"] == "curator"
                for r in rows)
    primary = (RQ9_PRIMARY_CURATOR.get(s) if RQ9_PRIMARY_CURATOR.get(s) in codes
               else (codes[0] if codes else None))
    tech = f"curator:{primary}" if primary else ("curator" if plain else None)
    return tech, [c for c in codes if c != primary]


def t_rq9(rows) -> str:
    """RQ9: the pre-registered four-row table per system (eval §10a.4) — floor and best
    all-common SAR (detection), the reference-blind curator (expression), the R1-vs-R2
    inter-rater agreement (results.csv keeps the pre-registered technique name `ceiling`; the
    table never calls it that — it bounds nothing about a third partition, review M3) — plus,
    where a raters' consensus exists beside the committed reference, the
    curator re-scored against it as a labelled sensitivity row. Kinds never cross (§10a.7)."""
    systems = _rq9_systems(rows)
    if not systems:
        return GEN + "%% no RQ9 rows in results.csv yet -- placeholder.\n"

    def f1(v):
        return f"{v:.2f}" if isinstance(v, (int, float)) else "--"

    body = []
    for i, s in enumerate(systems):
        if i:
            body.append("    \\midrule")
        sar = next((r["technique"][4:] for r in rows if r["system"] == s and r["axis"] == "RQ9"
                    and r["technique"].startswith("sar:") and r["projection"] == "detection"),
                   None)
        v = lambda tech, metric, proj, **kw: _rq9_val(rows, s, tech, metric, proj, **kw)  # noqa: E731
        cur, extras = _rq9_curators(rows, s)
        kappa = v("ceiling", "kappa", "rater-pair")
        conflicts = [float(r["value"]) for r in rows if r["system"] == s and r["axis"] == "RQ9"
                     and r["technique"].startswith("rater:")
                     and r["metric"] == "boundary_conflicts"]
        lines = [
            (f"{_disp(s)}", "no-curation floor", "det.",
             _fmt(v("floor", "mojofm", "detection")), _fmt(v("floor", "a2a", "detection")), "--"),
            # "best" is scoped to the ALL-COMMON set (ARC, on its own entity subset, is not
            # a candidate here — audit 2026-08-31: ARC out-scores LIMBO on eShop)
            ("", f"best SAR ({sar.upper() if sar else '--'})", "det.",
             _fmt(v("sar:", "mojofm", "detection", prefix=True)),
             _fmt(v("sar:", "a2a", "detection", prefix=True)), "--"),
            ("", "\\textbf{blind curator}", "expr.",
             f"\\textbf{{{_fmt(v(cur, 'mojofm', 'expression'))}}}",
             f"\\textbf{{{_fmt(v(cur, 'a2a', 'expression'))}}}",
             f1(v(cur, "edge_f1", "expression"))),
        ]
        # the curator-variance arm (1.5b): further curators beside the pre-registered one
        for c in extras:
            lines.append(("", f"\\quad second blind curator ({c})", "expr.",
                          _fmt(v(f"curator:{c}", "mojofm", "expression")),
                          _fmt(v(f"curator:{c}", "a2a", "expression")),
                          f1(v(f"curator:{c}", "edge_f1", "expression"))))
        if extras and v("curator-pair", "mojofm", "curator-pair") is not None:
            ari = v("curator-pair", "ari", "curator-pair")
            lines.append(("", "\\quad curator vs.\\ curator agreement", "agr.",
                          _fmt(v("curator-pair", "mojofm", "curator-pair")),
                          _fmt(v("curator-pair", "a2a", "curator-pair")),
                          (f"ARI\\,{ari:.2f}" if ari is not None else "--")))
        if v(cur, "mojofm", "expression-vs-consensus") is not None:
            lines.append(("", "\\quad vs.\\ consensus", "expr.",
                          _fmt(v(cur, "mojofm", "expression-vs-consensus")),
                          _fmt(v(cur, "a2a", "expression-vs-consensus")),
                          f1(v(cur, "edge_f1", "expression-vs-consensus"))))
        lines.append(("", "R$_1$ vs.\\ R$_2$ agreement", "agr.",
                      _fmt(v("ceiling", "mojofm", "rater-pair")),
                      _fmt(v("ceiling", "a2a", "rater-pair")),
                      (f"$\\kappa$\\,{kappa:.2f}" if kappa is not None else "--")
                      + (f"; {int(sum(conflicts))}\\,confl." if conflicts else "")))
        body += [f"    {a} & {b} & {c} & {d} & {e} & {g} \\\\" for a, b, c, d, e, g in lines]
    return (GEN + "\\begin{table}[t]\n  \\centering\n"
            "  \\caption{" + PAPER_RQ["RQ9"] + " blind curation (terms: \\S\\ref{sec:design}; "
            "all-common projection; best SAR = best of ACDC/WCA/LIMBO, \\texttt{dir} coinciding with the floor here). R$_1$ vs.\\ R$_2$ = the reference authors' "
            "agreement, an inter-rater baseline; Edge-F1 = container-edge F1; $\\kappa$ = raw "
            "Cohen's $\\kappa$ on rater labels; confl. = rater clusters cutting a reference "
            "boundary; the consensus row is a sensitivity re-score, the second-curator row the "
            "curator-variance arm.}\n"
            "  \\label{tab:rq9}\n"
            # the row-label column overruns \columnwidth by ~13pt at the shared FIT spacing
            + "  \\footnotesize\\setlength{\\tabcolsep}{2.2pt}\n"
            + "  \\begin{tabular}{@{}lll rrl@{}}\n    \\toprule\n"
            "    System & Row & Kind & MoJo & a2a & Edge-F1\\,/\\,$\\kappa$ \\\\\n    \\midrule\n"
            + "\n".join(body) + "\n    \\bottomrule\n  \\end{tabular}\n\\end{table}\n")


def t_rq9_effort(rows) -> str:
    """RQ9 effort (eval §10a.4): curator wall-clock, curate-editor operations, rule lines,
    groups, and the share of groups that survived from the `arch propose` draft — beside the
    ceiling's structure (rater boundary conflicts vs the scored reference, consensus size)."""
    systems = _rq9_systems(rows)
    if not systems:
        return GEN + "%% no RQ9 rows in results.csv yet -- placeholder.\n"
    body = []
    for s in systems:
        v = lambda tech, metric, proj, **kw: _rq9_val(rows, s, tech, metric, proj, **kw)  # noqa: E731
        cur, extras = _rq9_curators(rows, s)
        groups = v(cur, "groups", "effort")
        derived = v(cur, "final_groups_propose_derived", "effort")
        conflicts = [float(r["value"]) for r in rows if r["system"] == s and r["axis"] == "RQ9"
                     and r["technique"].startswith("rater:")
                     and r["metric"] == "boundary_conflicts"]
        cons = v("consensus", "clusters", "partition")

        def i_(x):
            return f"{int(x)}" if isinstance(x, (int, float)) else "--"

        def f_(x):
            return f"{x:.2f}" if isinstance(x, (int, float)) else "--"
        body.append(f"    {_disp(s)} & {i_(v(cur, 'wall_clock_minutes_reported', 'effort'))} & "
                    f"{i_(v(cur, 'ops_total', 'effort'))} & "
                    f"{i_(v(cur, 'rule_lines', 'effort'))} & "
                    f"{i_(groups)} & "
                    f"{i_(derived)}/{i_(groups)} & "
                    f"{f_(v('ceiling', 'kappa', 'rater-pair'))} & "
                    f"{f_(v('ceiling', 'kappa_aligned', 'rater-pair'))} & "
                    f"{f_(v('ceiling', 'ari', 'rater-pair'))} & "
                    f"{f_(v('ceiling', 'nmi', 'rater-pair'))} & "
                    f"{i_(sum(conflicts)) if conflicts else '--'} & {i_(cons)} \\\\")
        # the curator-variance arm (1.5b): one indented effort line per further curator; the
        # agreement cells belong to the raters, not to a curator, so they stay blank
        for c in extras:
            t = f"curator:{c}"
            g = v(t, "groups", "effort")
            body.append(f"    \\quad {c} & {i_(v(t, 'wall_clock_minutes_reported', 'effort'))} & "
                        f"{i_(v(t, 'ops_total', 'effort'))} & {i_(v(t, 'rule_lines', 'effort'))} & "
                        f"{i_(g)} & {i_(v(t, 'final_groups_propose_derived', 'effort'))}/{i_(g)} & "
                        "-- & -- & -- & -- & -- & -- \\\\")
    return (GEN + "\\begin{table}[t]\n  \\centering\n"
            "  \\caption{" + PAPER_RQ["RQ9"] + " curation effort (Min = self-reported wall-clock; Ops = editor "
            "operations from the edit trace; Rules/Groups = the frozen rules; Prop. = groups "
            "kept from the \\cli~\\texttt{propose} draft) and inter-rater agreement structure "
            "($\\kappa_{\\mathrm{al}}$ = $\\kappa$ after optimal label matching; ARI = adjusted "
            "Rand index; NMI = normalized mutual information; Confl. as in "
            "Table~\\ref{tab:rq9}; Cons. = clusters in the raters' consensus).}\n"
            "  \\label{tab:rq9effort}\n" + FIT
            # 11 columns overflow the IEEE single column at the shared FIT spacing (9.4pt);
            # tighten this table only rather than loosening FIT for every other table.
            + "  \\setlength{\\tabcolsep}{1.9pt}\n"
            + "  \\begin{tabular}{@{}l rrrr r rrrr rr@{}}\n    \\toprule\n"
            "    & \\multicolumn{5}{c}{Curation effort} & \\multicolumn{6}{c}{Rater agreement} \\\\\n"
            "    \\cmidrule(lr){2-6}\\cmidrule(lr){7-12}\n"
            "    System & Min & Ops & Rules & Groups & Prop. & $\\kappa$ & "
            "$\\kappa_{\\mathrm{al}}$ & ARI & NMI & Confl. & Cons. \\\\\n"
            "    \\midrule\n" + "\n".join(body) + "\n    \\bottomrule\n  \\end{tabular}\n\\end{table}\n")


BUILDERS = {"corpus": t_corpus, "rq1_fidelity": t_rq1, "rq2_baselines": t_rq2,
            "rq2_clusters": t_rq2_clusters,
            "rq3_ablation": t_rq3, "rq5_stability": t_rq5,
            "rq6_drift": t_rq6, "rq6_combined": t_rq6_combined, "rq6_history": t_rq6_history,
            "rq7_perf": t_rq7,
            "rq9_curation": t_rq9, "rq9_effort": t_rq9_effort}


def build_table(name: str, rows: list[dict]) -> str:
    if name in BUILDERS:
        return BUILDERS[name](rows)
    return (GEN + f"%% '{name}' has no data yet (experiment not run) -- placeholder.\n"
            f"%% Implemented once out/** carries the {name} artifacts.\n")


PIVOT_METRICS = ("mojofm", "a2a", "ari", "nested", "clusters", "mojofm_stdev", "a2a_stdev",
                 "ari_stdev", "entities_common")


def write_fidelity_pivot(rows: list[dict], path: pathlib.Path) -> None:
    """The per-system x per-technique view the review asked for (item 5.8): one row per
    (system, technique, projection) with MoJoFM, a2a, cluster count, rerun spread (LLM) and the
    common-entity count (pairwise rows) side by side — the tidy ``results.csv`` holds the same
    numbers one per line. c2c is NOT among them: it was never scored (ARCADE's c2c exists but
    was not run), and the paper says so. Sorted, LF, byte-stable."""
    cells: dict[tuple[str, str, str], dict[str, str]] = {}
    for r in rows:
        if r["axis"] != "fidelity" or r["metric"] not in PIVOT_METRICS:
            continue
        key = (r["system"], r["technique"], r["projection"])
        cells.setdefault(key, {"language": r["language"], "granularity": r["granularity"],
                               "tier": r.get("tier", "")})[r["metric"]] = r["value"]
    header = ["system", "language", "granularity", "tier", "technique", "projection",
              *PIVOT_METRICS]
    lines = [",".join(header)]
    for (system, technique, projection), d in sorted(cells.items()):
        lines.append(",".join([system, d["language"], d["granularity"], d["tier"], technique,
                               projection, *[str(d.get(m, "")) for m in PIVOT_METRICS]]))
    path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    here = pathlib.Path(__file__).resolve().parent
    ap.add_argument("--results", type=pathlib.Path, default=here / "results.csv")
    ap.add_argument("--out", type=pathlib.Path, default=here.parent / "latex" / "tables")
    ap.add_argument("--only", nargs="*", choices=TABLES, help="subset to emit")
    args = ap.parse_args(argv)

    if not args.results.exists():
        print(f"no {args.results} — run aggregate_results.py first", file=sys.stderr)
        return 1
    rows = load(args.results)
    args.out.mkdir(parents=True, exist_ok=True)
    names = args.only or TABLES
    for name in names:
        (args.out / f"{name}.tex").write_text(build_table(name, rows), encoding="utf-8", newline="\n")
    if not args.only:
        write_fidelity_pivot(rows, here / "fidelity-by-system.csv")
    have = [n for n in names if n in HAVE_DATA]
    print(f"wrote {len(names)} table(s) -> {args.out}  ({len(have)} with data: {', '.join(have)})",
          file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
