#!/usr/bin/env python3
"""Emit the .pgf/.tex figures under latex/figures/ from results.csv + stats.json
(evaluation plan §15.4 / §15.2 inventory).

Implemented today (both self-contained TikZ — no matplotlib/scipy, only ``\\usepackage{tikz}``):
  * **cd_diagram** (RQ2) — critical-difference diagram from ``stats.json``'s ``rq2.cd_diagram``
    (average ranks + the Nemenyi critical difference, computed stdlib-only in stats.py).
  * **ablation_tornado** (RQ3) — horizontal bars of the median edge-set impact (1 - edge_f1 vs the
    full config) per design choice at its extreme setting, from ``rq3.ablation_tornado``. A5
    (declared-never-dropped) tops it; A4 (down-weight-private) is ~0 (the honest inert result).

  * **scaling** (RQ7) — log-log cold/warm wall-clock vs KLOC scatter from ``stats.json``'s
    ``rq7`` block (baselines/rq7_perf.py), with the fitted scaling slope.

drift_pr (RQ6) is intentionally a comment stub: the §8.1 detector has no score threshold to
sweep, so RQ6 reports point estimates + Wilson CIs (tab:rq6), not a PR curve. Still a
scaffold: human (RQ8, spun out to a companion plan).
"""
from __future__ import annotations

import argparse
import json
import pathlib
import sys

FIGURES = ["cd_diagram", "ablation_tornado", "drift_pr", "scaling", "human", "two_regime"]

# "pipeline" renders via the \tool macro, never the literal name: main.tex resolves it to an
# anonymous placeholder under \anonymoustrue (eval §1.4 #5 — the SANER manuscript anonymizes the
# TOOL, not just the authors). The CD diagram leaked the real name into the anonymous PDF.
DISPLAY = {"pipeline": "\\tool", "acdc": "ACDC", "wca": "WCA", "limbo": "LIMBO",
           "dir": "dir", "cc": "cc", "arc": "ARC", "llm": "LLM"}
GEN = "% GENERATED by analysis/make_figures.py from stats.json -- DO NOT EDIT BY HAND.\n"


def _significance_bars(ordered: list[tuple[str, float]], cd: float) -> list[tuple[int, int]]:
    """Maximal runs of rank-consecutive techniques within the critical difference (no-significant-
    difference cliques). ``ordered`` is (tech, avg_rank) sorted by rank asc."""
    n = len(ordered)
    spans: list[tuple[int, int]] = []
    for i in range(n):
        j = i
        while j + 1 < n and ordered[j + 1][1] - ordered[i][1] <= cd:
            j += 1
        if j > i:
            spans.append((i, j))
    # drop spans wholly contained in another (keep only maximal cliques)
    return [(a, b) for (a, b) in spans
            if not any(a2 <= a and b <= b2 and (a2, b2) != (a, b) for (a2, b2) in spans)]


def _cd_tikz(cd_data: dict) -> str:
    ranks: dict[str, float] = cd_data.get("avg_ranks") or {}
    cd = cd_data.get("cd")
    if not ranks or cd is None:
        return (GEN + "% cd_diagram: no rq2.cd_diagram data yet "
                "(run stats.py once results.csv carries the all-common baselines).\n")
    ordered = sorted(ranks.items(), key=lambda kv: kv[1])          # best (lowest) rank first
    k = len(ordered)
    lo, hi = 1, k
    mid = (lo + hi) / 2
    L = []
    L.append(GEN)
    L.append("\\begin{tikzpicture}[xscale=1.6, yscale=1.0]\n")
    # rank axis (reversed: best rank 1 on the LEFT) with integer ticks
    L.append("  \\draw[thick] (%d,0) -- (%d,0);\n" % (lo, hi))
    for r in range(lo, hi + 1):
        L.append("  \\draw (%d,0) -- (%d,0.12); \\node[above,font=\\footnotesize] at (%d,0.12) {%d};\n"
                 % (r, r, r, r))
    # critical-difference reference bar
    L.append("  \\draw[|-|] (%g,0.95) -- (%g,0.95);\n" % (lo, lo + cd))
    L.append("  \\node[above,font=\\footnotesize] at (%g,0.95) {CD $=$ %.2f};\n"
             % (lo + cd / 2.0, cd))
    # technique labels: lower ranks anchor left, higher ranks anchor right (classic layout)
    left = [(t, r) for t, r in ordered if r <= mid]
    right = [(t, r) for t, r in ordered if r > mid]
    for idx, (t, r) in enumerate(left):
        y = -0.45 - 0.45 * idx
        L.append("  \\draw (%g,0) |- (%g,%g);\n" % (r, lo - 0.5, y))
        L.append("  \\node[anchor=east,font=\\small] at (%g,%g) {%s (%.2f)};\n"
                 % (lo - 0.5, y, DISPLAY.get(t, t), r))
    for idx, (t, r) in enumerate(reversed(right)):
        y = -0.45 - 0.45 * idx
        L.append("  \\draw (%g,0) |- (%g,%g);\n" % (r, hi + 0.5, y))
        L.append("  \\node[anchor=west,font=\\small] at (%g,%g) {%s (%.2f)};\n"
                 % (hi + 0.5, y, DISPLAY.get(t, t), r))
    # non-significance cliques (thick bars just above the axis)
    for bi, (a, b) in enumerate(_significance_bars(ordered, cd)):
        y = 0.22 + 0.16 * bi
        L.append("  \\draw[line width=2pt] (%g,%g) -- (%g,%g);\n"
                 % (ordered[a][1], y, ordered[b][1], y))
    # honest N + any excluded systems (e.g. ITK, where WCA/LIMBO do not complete — §6.1)
    n = cd_data.get("n_systems")
    excl = cd_data.get("excluded_systems") or []
    caption = "N $=$ %s systems" % n if n is not None else ""
    if excl:
        caption += " (excl.\\ %s: WCA/LIMBO do not complete at file granularity)" % ", ".join(excl)
    if caption:
        y = -0.45 - 0.45 * max(len(left), len(right))
        L.append("  \\node[font=\\footnotesize] at (%g,%g) {%s};\n" % ((lo + hi) / 2.0, y, caption))
    L.append("\\end{tikzpicture}\n")
    return "".join(L)


def _tornado_tikz(data: dict) -> str:
    """RQ3 ablation tornado: horizontal bars = median edge-set impact (1 - edge_f1 vs the full
    config) per design choice at its extreme setting, sorted largest-first. Self-contained TikZ
    (same stdlib ethos as the CD diagram — needs only \\usepackage{tikz})."""
    items = [(k, v) for k, v in (data or {}).items() if v is not None]
    if not items:
        return (GEN + "% ablation_tornado: no rq3.ablation_tornado data yet "
                "(run stats.py once results.csv carries the A1/A3/A4/A5 edge-vs-full rows).\n")
    items.sort(key=lambda kv: kv[1], reverse=True)          # biggest impact on top
    vmax = max(v for _, v in items) or 1.0
    scale = 5.0 / vmax          # longest bar ~5 units: bars + side labels must stay inside \columnwidth
    L = [GEN, "\\begin{tikzpicture}[yscale=0.62]\n"]
    n = len(items)
    for i, (label, v) in enumerate(items):
        y = n - i
        w = v * scale
        L.append("  \\node[anchor=east,font=\\small] at (0,%g) {%s};\n" % (y, label.replace("_", "\\_")))
        L.append("  \\fill[black!72] (0,%g) rectangle (%g,%g);\n" % (y - 0.32, w, y + 0.32))
        L.append("  \\node[anchor=west,font=\\footnotesize] at (%g,%g) {%.2f};\n" % (w + 0.12, y, v))
    # baseline axis
    L.append("  \\draw[thick] (0,%g) -- (0,%g);\n" % (0.4, n + 0.6))
    L.append("  \\node[font=\\footnotesize,anchor=north] at (%g,%g) "
             "{median edge-set impact (1 $-$ F1 vs.\\ full config)};\n" % (3.0, 0.3))
    L.append("\\end{tikzpicture}\n")
    return "".join(L)


def _scaling_tikz(rq7: dict) -> str:
    """RQ7 scaling curve (§10): log-log scatter of end-to-end wall-clock vs system size
    (KLOC), cold (filled) vs warm (open) with the fitted log-log slope. Self-contained
    TikZ, same stdlib ethos as the CD diagram."""
    import math
    kloc = rq7.get("kloc_by_system") or {}
    cold = rq7.get("cold_s_by_system") or {}
    warm = rq7.get("warm_s_by_system") or {}
    systems = [s for s in sorted(kloc, key=lambda x: kloc[x])
               if kloc.get(s, 0) > 0 and cold.get(s, 0) > 0]
    if len(systems) < 3:
        return (GEN + "% scaling: no rq7 data yet (run baselines/rq7_perf.py, then "
                "aggregate + stats).\n")
    xs = {s: math.log10(kloc[s]) for s in systems}
    ys = {s: math.log10(cold[s]) for s in systems}
    yw = {s: math.log10(warm[s]) for s in systems if warm.get(s, 0) > 0}
    x0 = math.floor(min(xs.values()))
    x1 = math.ceil(max(xs.values()))
    y0 = math.floor(min(list(ys.values()) + list(yw.values())))
    y1 = math.ceil(max(list(ys.values()) + list(yw.values())))
    sx = 6.5 / max(1, (x1 - x0))
    sy = 4.2 / max(1, (y1 - y0))

    def X(v):
        return round((v - x0) * sx, 3)

    def Y(v):
        return round((v - y0) * sy, 3)

    L = [GEN, "\\begin{tikzpicture}\n"]
    # axes + decade ticks
    L.append("  \\draw[thick] (0,0) rectangle (%g,%g);\n" % (X(x1), Y(y1)))
    for d in range(x0, x1 + 1):
        L.append("  \\draw (%g,0) -- (%g,-0.1); \\node[below,font=\\footnotesize] at "
                 "(%g,-0.1) {$10^{%d}$};\n" % (X(d), X(d), X(d), d))
    for d in range(y0, y1 + 1):
        L.append("  \\draw (0,%g) -- (-0.1,%g); \\node[left,font=\\footnotesize] at "
                 "(-0.1,%g) {$10^{%d}$};\n" % (Y(d), Y(d), Y(d), d))
    L.append("  \\node[below,font=\\small] at (%g,-0.55) {system size (KLOC, log)};\n"
             % (X(x1) / 2))
    L.append("  \\node[rotate=90,font=\\small] at (-0.85,%g) {wall-clock (s, log)};\n"
             % (Y(y1) / 2))
    # cold-warm droplines + points + labels
    for s in systems:
        x = X(xs[s])
        L.append("  \\fill (%g,%g) circle (2pt);\n" % (x, Y(ys[s])))
        if s in yw:
            L.append("  \\draw[black!45,densely dotted] (%g,%g) -- (%g,%g);\n"
                     % (x, Y(ys[s]), x, Y(yw[s])))
            L.append("  \\draw (%g,%g) circle (2pt);\n" % (x, Y(yw[s])))
        L.append("  \\node[anchor=west,font=\\tiny,xshift=2pt] at (%g,%g) {%s};\n"
                 % (x, Y(ys[s]), s))
    # legend + fitted slope
    slope = rq7.get("scaling_slope_cold_vs_kloc")
    ylegend = Y(y1) - 0.35
    L.append("  \\fill (0.35,%g) circle (2pt); \\node[anchor=west,font=\\footnotesize] "
             "at (0.5,%g) {cold};\n" % (ylegend, ylegend))
    L.append("  \\draw (0.35,%g) circle (2pt); \\node[anchor=west,font=\\footnotesize] "
             "at (0.5,%g) {warm};\n" % (ylegend - 0.4, ylegend - 0.4))
    if slope is not None:
        L.append("  \\node[anchor=west,font=\\footnotesize] at (0.35,%g) "
                 "{cold slope $\\approx$ %.2f};\n" % (ylegend - 0.8, slope))
    L.append("\\end{tikzpicture}\n")
    return "".join(L)


# Per-point label placement for the two-regime scatter: (anchor, dx, dy) in cm. The scored
# corpus clusters tightly (ITK/OpenCV top-left, abseil/bash mid, four C# systems on the
# ratio-1.0 edge), so default placement collides; unknown systems fall back to west/+0.06/0.
_TR_LABEL = {"opencv": ("west", 0.07, -0.04), "itk": ("west", 0.07, -0.13),
             "abseil": ("east", -0.07, 0.0), "bash": ("west", 0.07, -0.06),
             "libxml2": ("east", -0.07, 0.0),
             "eshop": ("east", -0.08, -0.07), "nopcommerce": ("east", -0.08, 0.10),
             "orchardcore": ("east", -0.08, 0.0), "squidex": ("east", -0.08, 0.0)}
_TR_DISP = {"itk": "ITK", "opencv": "OpenCV", "eshop": "eShop", "orchardcore": "OrchardCore",
            "nopcommerce": "nopCommerce", "squidex": "Squidex"}


def _two_regime_tikz(stats: dict, results_csv: pathlib.Path) -> str:
    """RQ1's two-regime finding in one view (review 2026-09-07): the autonomous floor's
    MoJoFM (all-common) against the build graph's unit ratio (log) — both axes computable
    without a reference. Dashed lines are the post-hoc rule's ratio threshold and the
    recovery threshold; open markers fail the rule (libxml2 fails it by the largest-unit-share
    clause despite its ratio, which is the annotation's job to show). Self-contained TikZ."""
    import csv
    import math
    adq = (stats.get("adequacy") or {}).get("by_system") or {}
    macros = stats.get("summary_macros") or {}
    try:
        ratio_max = float(macros["rqAdequacyRatioMax"])
        largest_max = float(macros["rqAdequacyLargestMax"])
        rec_ok = float(macros["rqTwoRecoveredMin"])
    except (KeyError, TypeError, ValueError):
        return (GEN + "% two_regime: no adequacy rule macros in stats.json yet "
                "(run stats.py over a results.csv with the adequacy axis).\n")
    floor: dict[str, float] = {}
    if results_csv.exists():
        with results_csv.open(encoding="utf-8") as f:
            for r in csv.DictReader(f):
                if (r["axis"] == "fidelity" and r["technique"] == "floor"
                        and r["metric"] == "mojofm" and r["projection"] == "all-common"):
                    try:
                        floor[r["system"]] = float(r["value"])
                    except (TypeError, ValueError):
                        continue
    pts = sorted(s for s in floor if s in adq and adq[s].get("unit_ratio"))
    if len(pts) < 3:
        return (GEN + "% two_regime: fewer than 3 systems carry both a floor score and an "
                "adequacy row -- run aggregate + stats first.\n")
    x0, x1 = -2.0, 0.0                      # log10(unit ratio): 0.01 .. 1.0
    sx, sy = 6.4 / (x1 - x0), 4.0 / 100.0   # plot area 6.4 x 4.0 cm

    def X(ratio):
        return round((max(math.log10(ratio), x0) - x0) * sx, 3)

    def Y(mojo):
        return round(mojo * sy, 3)

    L = [GEN, "\\begin{tikzpicture}\n"]
    L.append("  \\draw[thick] (0,0) rectangle (%g,%g);\n" % (X(1.0), Y(100)))
    for tick in (0.02, 0.05, 0.1, 0.2, 0.5, 1.0):
        t = "1" if tick == 1.0 else ("%g" % tick)
        L.append("  \\draw (%g,0) -- (%g,-0.09); \\node[below,font=\\footnotesize] at "
                 "(%g,-0.09) {%s};\n" % (X(tick), X(tick), X(tick), t))
    for tick in range(0, 101, 20):
        L.append("  \\draw (0,%g) -- (-0.09,%g); \\node[left,font=\\footnotesize] at "
                 "(-0.09,%g) {%d};\n" % (Y(tick), Y(tick), Y(tick), tick))
    L.append("  \\node[below,font=\\small] at (%g,-0.5) "
             "{unit ratio (build units / scored entities, log)};\n" % (X(1.0) / 2))
    L.append("  \\node[rotate=90,font=\\small] at (-0.95,%g) {floor MoJoFM (all-common)};\n"
             % (Y(100) / 2))
    # the two thresholds (dashed), each labelled where the plot is empty
    L.append("  \\draw[densely dashed,black!60] (%g,0) -- (%g,%g);\n"
             % (X(ratio_max), X(ratio_max), Y(100)))
    L.append("  \\node[anchor=south east,rotate=90,font=\\tiny,black!60] at (%g,%g) "
             "{ratio $\\le$ %g};\n" % (X(ratio_max), Y(30), ratio_max))
    L.append("  \\draw[densely dashed,black!60] (0,%g) -- (%g,%g);\n"
             % (Y(rec_ok), X(1.0), Y(rec_ok)))
    L.append("  \\node[anchor=south west,font=\\tiny,black!60] at (%g,%g) "
             "{recovered $\\ge$ %g};\n" % (X(0.011), Y(rec_ok), rec_ok))
    # regime annotations, clear of every point at today's coordinates
    L.append("  \\node[font=\\footnotesize,black!55] at (%g,%g) {build-modular};\n"
             % (X(0.05), Y(62)))
    L.append("  \\node[font=\\footnotesize,black!55] at (%g,%g) {project-coarse};\n"
             % (X(0.45), Y(50)))
    for s in pts:
        ratio, largest = adq[s]["unit_ratio"], adq[s].get("largest_share", 0.0)
        adequate = ratio <= ratio_max and largest <= largest_max
        x, y = X(ratio), Y(floor[s])
        L.append(("  \\fill (%g,%g) circle (2pt);\n" if adequate
                  else "  \\draw (%g,%g) circle (2pt);\n") % (x, y))
        anchor, dx, dy = _TR_LABEL.get(s, ("west", 0.06, 0.0))
        disp = _TR_DISP.get(s, s)
        if s == "libxml2":   # fails the rule by the largest-unit-share clause, not the ratio
            disp += " (largest unit %d\\,\\%%)" % round(100 * largest)
        L.append("  \\node[anchor=%s,font=\\tiny] at (%g,%g) {%s};\n"
                 % (anchor, x + dx, y + dy, disp))
    L.append("\\end{tikzpicture}\n")
    return "".join(L)


def build_figure(name: str, results_csv: pathlib.Path, stats_json: pathlib.Path,
                 out_dir: pathlib.Path) -> None:
    """Render one figure to out_dir/<name>.pgf."""
    stats = (json.loads(stats_json.read_text(encoding="utf-8")) if stats_json.exists() else {})
    if name == "cd_diagram":
        cd_data = stats.get("rq2", {}).get("cd_diagram", {})
        (out_dir / "cd_diagram.pgf").write_text(_cd_tikz(cd_data), encoding="utf-8", newline="\n")
        return
    if name == "ablation_tornado":
        tdata = stats.get("rq3", {}).get("ablation_tornado", {})
        (out_dir / "ablation_tornado.pgf").write_text(_tornado_tikz(tdata),
                                                      encoding="utf-8", newline="\n")
        return
    if name == "scaling":
        (out_dir / "scaling.pgf").write_text(_scaling_tikz(stats.get("rq7", {})),
                                             encoding="utf-8", newline="\n")
        return
    if name == "two_regime":
        (out_dir / "two_regime.pgf").write_text(_two_regime_tikz(stats, results_csv),
                                                encoding="utf-8", newline="\n")
        return
    if name == "drift_pr":
        (out_dir / "drift_pr.pgf").write_text(
            GEN + "% drift_pr: intentionally not a curve -- the \\S8.1 detector has no\n"
            "% score threshold to sweep, so RQ6 reports point estimates (P/R/F1 per\n"
            "% operator with Wilson CIs) in tab:rq6 instead of a PR curve.\n",
            encoding="utf-8", newline="\n")
        return
    (out_dir / f"{name}.pgf").write_text(
        GEN + f"% scaffold for '{name}' -- implement once its experiment lands.\n",
        encoding="utf-8", newline="\n")


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    here = pathlib.Path(__file__).resolve().parent
    ap.add_argument("--results", type=pathlib.Path, default=here / "results.csv")
    ap.add_argument("--stats", type=pathlib.Path, default=here / "stats.json")
    ap.add_argument("--out", type=pathlib.Path, default=here.parent / "latex" / "figures")
    ap.add_argument("--only", nargs="*", choices=FIGURES, help="subset to emit")
    args = ap.parse_args(argv)

    args.out.mkdir(parents=True, exist_ok=True)
    names = args.only or FIGURES
    for name in names:
        build_figure(name, args.results, args.stats, args.out)
    done = [n for n in names if n in ("cd_diagram", "ablation_tornado", "scaling", "two_regime")]
    print(f"wrote {len(names)} figure(s) -> {args.out}"
          + (f" ({', '.join(done)} rendered from data)" if done else " (scaffolds)"),
          file=sys.stderr)


if __name__ == "__main__":
    main()
