// GENERATED BY ANON — DO NOT EDIT. Overwritten every run (plan §9).
// Edit curation in rules/mapping-rules.yaml; views/styles live in views.dsl.

argsTest = container "args-test" "Build target group: args-test." "C/C++" {
    tags "Container,cpp,needs-curation"
}
assertTest = container "assert-test" "Build target group: assert-test." "C/C++" {
    tags "Container,cpp,needs-curation"
}
chronoTest = container "chrono-test" "Build target group: chrono-test." "C/C++" {
    tags "Container,cpp,needs-curation"
}
colorTest = container "color-test" "Build target group: color-test." "C/C++" {
    tags "Container,cpp,needs-curation"
}
compileFpTest = container "compile-fp-test" "Build target group: compile-fp-test." "C/C++" {
    tags "Container,cpp,needs-curation"
}
compileTest = container "compile-test" "Build target group: compile-test." "C/C++" {
    tags "Container,cpp,needs-curation"
}
coreTest = container "core-test" "Build target group: core-test." "C/C++" {
    tags "Container,cpp,needs-curation"
}
doc = container "doc" "Build target group: doc." "C/C++" {
    tags "Container,cpp,needs-curation,partial:codegen"
    properties {
        "structurizr.inspection.model.element.disconnected" "ignore"
    }
}
enforceChecksTest = container "enforce-checks-test" "Build target group: enforce-checks-test." "C/C++" {
    tags "Container,cpp,needs-curation"
}
fmt = container "fmt" "Build target group: fmt." "C/C++" {
    tags "Container,cpp,needs-curation"
}
fmtHeaderOnly = container "fmt-header-only" "Build target group: fmt-header-only." "C/C++" {
    tags "Container,cpp,needs-curation"
}
formatImplTest = container "format-impl-test" "Build target group: format-impl-test." "C/C++" {
    tags "Container,cpp,needs-curation"
}
formatTest = container "format-test" "Build target group: format-test." "C/C++" {
    tags "Container,cpp,needs-curation"
}
gtest = container "gtest" "Build target group: gtest." "C/C++" {
    tags "Container,cpp,needs-curation"
}
gtestExtraTest = container "gtest-extra-test" "Build target group: gtest-extra-test." "C/C++" {
    tags "Container,cpp,needs-curation"
}
osTest = container "os-test" "Build target group: os-test." "C/C++" {
    tags "Container,cpp,needs-curation"
}
ostreamTest = container "ostream-test" "Build target group: ostream-test." "C/C++" {
    tags "Container,cpp,needs-curation"
}
posixMockTest = container "posix-mock-test" "Build target group: posix-mock-test." "C/C++" {
    tags "Container,cpp,needs-curation"
}
printfTest = container "printf-test" "Build target group: printf-test." "C/C++" {
    tags "Container,cpp,needs-curation"
}
rangesTest = container "ranges-test" "Build target group: ranges-test." "C/C++" {
    tags "Container,cpp,needs-curation"
}
scanTest = container "scan-test" "Build target group: scan-test." "C/C++" {
    tags "Container,cpp,needs-curation"
}
stdTest = container "std-test" "Build target group: std-test." "C/C++" {
    tags "Container,cpp,needs-curation"
}
testMain = container "test-main" "Build target group: test-main." "C/C++" {
    tags "Container,cpp,needs-curation"
}
unicodeTest = container "unicode-test" "Build target group: unicode-test." "C/C++" {
    tags "Container,cpp,needs-curation"
}
xcharTest = container "xchar-test" "Build target group: xchar-test." "C/C++" {
    tags "Container,cpp,needs-curation"
}
