// GENERATED BY ANON — DO NOT EDIT. Overwritten every run (plan §9).
// Edit curation in rules/mapping-rules.yaml; views/styles live in views.dsl.

!impliedRelationships false
argsTest -> fmt "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
argsTest -> testMain "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
assertTest -> fmt "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
assertTest -> testMain "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
chronoTest -> fmt "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
chronoTest -> testMain "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
colorTest -> fmt "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
colorTest -> testMain "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
compileFpTest -> fmtHeaderOnly "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
compileFpTest -> gtest "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
compileTest -> fmt "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
compileTest -> testMain "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
coreTest -> fmt "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
coreTest -> testMain "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
enforceChecksTest -> fmt "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
enforceChecksTest -> testMain "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
formatImplTest -> fmtHeaderOnly "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
formatImplTest -> gtest "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
formatTest -> fmt "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
formatTest -> testMain "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
gtestExtraTest -> fmt "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
gtestExtraTest -> testMain "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
osTest -> fmt "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
osTest -> testMain "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
ostreamTest -> fmt "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
ostreamTest -> testMain "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
posixMockTest -> gtest "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
printfTest -> fmt "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
printfTest -> testMain "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
rangesTest -> fmt "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
rangesTest -> testMain "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
scanTest -> fmt "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
scanTest -> testMain "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
stdTest -> fmt "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
stdTest -> testMain "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
testMain -> fmt "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link"
}
testMain -> gtest "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link"
}
unicodeTest -> fmtHeaderOnly "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
unicodeTest -> gtest "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
xcharTest -> fmt "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
xcharTest -> testMain "Uses" "Native link (static/shared library)" {
    tags "Relationship,confidence:low,declared,link,private-link"
}
